// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package errors

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 未知错误
func IsUnknown(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNKNOWN.String() && e.Code == 500
}

// 未知错误
func ErrorUnknown(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UNKNOWN.String(), fmt.Sprintf(format, args...))
}

// 数据源相关错误 (1xx)
func IsDataSourceNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATA_SOURCE_NOT_FOUND.String() && e.Code == 404
}

// 数据源相关错误 (1xx)
func ErrorDataSourceNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_DATA_SOURCE_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsDataSourceAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATA_SOURCE_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorDataSourceAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_DATA_SOURCE_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsDataSourceHasAssociatedTasks(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATA_SOURCE_HAS_ASSOCIATED_TASKS.String() && e.Code == 409
}

func ErrorDataSourceHasAssociatedTasks(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_DATA_SOURCE_HAS_ASSOCIATED_TASKS.String(), fmt.Sprintf(format, args...))
}

func IsDataSourceDisabled(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATA_SOURCE_DISABLED.String() && e.Code == 400
}

func ErrorDataSourceDisabled(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_DATA_SOURCE_DISABLED.String(), fmt.Sprintf(format, args...))
}

func IsDataSourceConnectionFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATA_SOURCE_CONNECTION_FAILED.String() && e.Code == 503
}

func ErrorDataSourceConnectionFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(503, ErrorReason_DATA_SOURCE_CONNECTION_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsDataSourceInvalidType(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATA_SOURCE_INVALID_TYPE.String() && e.Code == 400
}

func ErrorDataSourceInvalidType(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_DATA_SOURCE_INVALID_TYPE.String(), fmt.Sprintf(format, args...))
}

func IsDataSourceInvalidStatus(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATA_SOURCE_INVALID_STATUS.String() && e.Code == 400
}

func ErrorDataSourceInvalidStatus(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_DATA_SOURCE_INVALID_STATUS.String(), fmt.Sprintf(format, args...))
}

func IsDataSourceInvalidConfig(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATA_SOURCE_INVALID_CONFIG.String() && e.Code == 400
}

func ErrorDataSourceInvalidConfig(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_DATA_SOURCE_INVALID_CONFIG.String(), fmt.Sprintf(format, args...))
}

// 任务相关错误 (2xx)
func IsTaskNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TASK_NOT_FOUND.String() && e.Code == 404
}

// 任务相关错误 (2xx)
func ErrorTaskNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_TASK_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsTaskAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TASK_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorTaskAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_TASK_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsTaskInvalidType(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TASK_INVALID_TYPE.String() && e.Code == 400
}

func ErrorTaskInvalidType(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_TASK_INVALID_TYPE.String(), fmt.Sprintf(format, args...))
}

func IsTaskInvalidStatus(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TASK_INVALID_STATUS.String() && e.Code == 400
}

func ErrorTaskInvalidStatus(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_TASK_INVALID_STATUS.String(), fmt.Sprintf(format, args...))
}

func IsTaskInvalidSchedule(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TASK_INVALID_SCHEDULE.String() && e.Code == 400
}

func ErrorTaskInvalidSchedule(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_TASK_INVALID_SCHEDULE.String(), fmt.Sprintf(format, args...))
}

func IsTaskCannotStart(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TASK_CANNOT_START.String() && e.Code == 400
}

func ErrorTaskCannotStart(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_TASK_CANNOT_START.String(), fmt.Sprintf(format, args...))
}

func IsTaskCannotStop(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TASK_CANNOT_STOP.String() && e.Code == 400
}

func ErrorTaskCannotStop(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_TASK_CANNOT_STOP.String(), fmt.Sprintf(format, args...))
}

func IsTaskCannotPause(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TASK_CANNOT_PAUSE.String() && e.Code == 400
}

func ErrorTaskCannotPause(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_TASK_CANNOT_PAUSE.String(), fmt.Sprintf(format, args...))
}

// 执行相关错误 (3xx)
func IsExecutionNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_EXECUTION_NOT_FOUND.String() && e.Code == 404
}

// 执行相关错误 (3xx)
func ErrorExecutionNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_EXECUTION_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsExecutionAlreadyRunning(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_EXECUTION_ALREADY_RUNNING.String() && e.Code == 409
}

func ErrorExecutionAlreadyRunning(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_EXECUTION_ALREADY_RUNNING.String(), fmt.Sprintf(format, args...))
}

func IsRetryNotAllowed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RETRY_NOT_ALLOWED.String() && e.Code == 400
}

func ErrorRetryNotAllowed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_RETRY_NOT_ALLOWED.String(), fmt.Sprintf(format, args...))
}

func IsMaxRetriesExceeded(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MAX_RETRIES_EXCEEDED.String() && e.Code == 400
}

func ErrorMaxRetriesExceeded(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_MAX_RETRIES_EXCEEDED.String(), fmt.Sprintf(format, args...))
}

// 模板相关错误 (4xx)
func IsTemplateNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TEMPLATE_NOT_FOUND.String() && e.Code == 404
}

// 模板相关错误 (4xx)
func ErrorTemplateNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_TEMPLATE_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsTemplateAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TEMPLATE_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorTemplateAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_TEMPLATE_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsSystemTemplateCannotModify(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SYSTEM_TEMPLATE_CANNOT_MODIFY.String() && e.Code == 403
}

func ErrorSystemTemplateCannotModify(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_SYSTEM_TEMPLATE_CANNOT_MODIFY.String(), fmt.Sprintf(format, args...))
}

func IsSystemTemplateCannotDelete(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SYSTEM_TEMPLATE_CANNOT_DELETE.String() && e.Code == 403
}

func ErrorSystemTemplateCannotDelete(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_SYSTEM_TEMPLATE_CANNOT_DELETE.String(), fmt.Sprintf(format, args...))
}

// 认证授权错误 (5xx)
func IsUnauthorized(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNAUTHORIZED.String() && e.Code == 401
}

// 认证授权错误 (5xx)
func ErrorUnauthorized(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_UNAUTHORIZED.String(), fmt.Sprintf(format, args...))
}

func IsForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FORBIDDEN.String() && e.Code == 403
}

func ErrorForbidden(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_FORBIDDEN.String(), fmt.Sprintf(format, args...))
}

func IsTokenExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TOKEN_EXPIRED.String() && e.Code == 401
}

func ErrorTokenExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_TOKEN_EXPIRED.String(), fmt.Sprintf(format, args...))
}

func IsTokenInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TOKEN_INVALID.String() && e.Code == 401
}

func ErrorTokenInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_TOKEN_INVALID.String(), fmt.Sprintf(format, args...))
}

func IsRateLimitExceeded(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RATE_LIMIT_EXCEEDED.String() && e.Code == 429
}

func ErrorRateLimitExceeded(format string, args ...interface{}) *errors.Error {
	return errors.New(429, ErrorReason_RATE_LIMIT_EXCEEDED.String(), fmt.Sprintf(format, args...))
}

// 验证错误 (6xx)
func IsValidationFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_VALIDATION_FAILED.String() && e.Code == 400
}

// 验证错误 (6xx)
func ErrorValidationFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_VALIDATION_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsInvalidParameter(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_PARAMETER.String() && e.Code == 400
}

func ErrorInvalidParameter(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_PARAMETER.String(), fmt.Sprintf(format, args...))
}

func IsMissingRequiredField(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MISSING_REQUIRED_FIELD.String() && e.Code == 400
}

func ErrorMissingRequiredField(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_MISSING_REQUIRED_FIELD.String(), fmt.Sprintf(format, args...))
}
