// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: errors.proto

package errors

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason 业务错误码枚举
type ErrorReason int32

const (
	// 未知错误
	ErrorReason_UNKNOWN ErrorReason = 0
	// 数据源相关错误 (1xx)
	ErrorReason_DATA_SOURCE_NOT_FOUND            ErrorReason = 100
	ErrorReason_DATA_SOURCE_ALREADY_EXISTS       ErrorReason = 101
	ErrorReason_DATA_SOURCE_HAS_ASSOCIATED_TASKS ErrorReason = 102
	ErrorReason_DATA_SOURCE_DISABLED             ErrorReason = 103
	ErrorReason_DATA_SOURCE_CONNECTION_FAILED    ErrorReason = 104
	ErrorReason_DATA_SOURCE_INVALID_TYPE         ErrorReason = 105
	ErrorReason_DATA_SOURCE_INVALID_STATUS       ErrorReason = 106
	ErrorReason_DATA_SOURCE_INVALID_CONFIG       ErrorReason = 107
	// 任务相关错误 (2xx)
	ErrorReason_TASK_NOT_FOUND        ErrorReason = 200
	ErrorReason_TASK_ALREADY_EXISTS   ErrorReason = 201
	ErrorReason_TASK_INVALID_TYPE     ErrorReason = 202
	ErrorReason_TASK_INVALID_STATUS   ErrorReason = 203
	ErrorReason_TASK_INVALID_SCHEDULE ErrorReason = 204
	ErrorReason_TASK_CANNOT_START     ErrorReason = 205
	ErrorReason_TASK_CANNOT_STOP      ErrorReason = 206
	ErrorReason_TASK_CANNOT_PAUSE     ErrorReason = 207
	// 执行相关错误 (3xx)
	ErrorReason_EXECUTION_NOT_FOUND       ErrorReason = 300
	ErrorReason_EXECUTION_ALREADY_RUNNING ErrorReason = 301
	ErrorReason_RETRY_NOT_ALLOWED         ErrorReason = 302
	ErrorReason_MAX_RETRIES_EXCEEDED      ErrorReason = 303
	// 模板相关错误 (4xx)
	ErrorReason_TEMPLATE_NOT_FOUND            ErrorReason = 400
	ErrorReason_TEMPLATE_ALREADY_EXISTS       ErrorReason = 401
	ErrorReason_SYSTEM_TEMPLATE_CANNOT_MODIFY ErrorReason = 402
	ErrorReason_SYSTEM_TEMPLATE_CANNOT_DELETE ErrorReason = 403
	// 认证授权错误 (5xx)
	ErrorReason_UNAUTHORIZED        ErrorReason = 500
	ErrorReason_FORBIDDEN           ErrorReason = 501
	ErrorReason_TOKEN_EXPIRED       ErrorReason = 502
	ErrorReason_TOKEN_INVALID       ErrorReason = 503
	ErrorReason_RATE_LIMIT_EXCEEDED ErrorReason = 504
	// 验证错误 (6xx)
	ErrorReason_VALIDATION_FAILED      ErrorReason = 600
	ErrorReason_INVALID_PARAMETER      ErrorReason = 601
	ErrorReason_MISSING_REQUIRED_FIELD ErrorReason = 602
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:   "UNKNOWN",
		100: "DATA_SOURCE_NOT_FOUND",
		101: "DATA_SOURCE_ALREADY_EXISTS",
		102: "DATA_SOURCE_HAS_ASSOCIATED_TASKS",
		103: "DATA_SOURCE_DISABLED",
		104: "DATA_SOURCE_CONNECTION_FAILED",
		105: "DATA_SOURCE_INVALID_TYPE",
		106: "DATA_SOURCE_INVALID_STATUS",
		107: "DATA_SOURCE_INVALID_CONFIG",
		200: "TASK_NOT_FOUND",
		201: "TASK_ALREADY_EXISTS",
		202: "TASK_INVALID_TYPE",
		203: "TASK_INVALID_STATUS",
		204: "TASK_INVALID_SCHEDULE",
		205: "TASK_CANNOT_START",
		206: "TASK_CANNOT_STOP",
		207: "TASK_CANNOT_PAUSE",
		300: "EXECUTION_NOT_FOUND",
		301: "EXECUTION_ALREADY_RUNNING",
		302: "RETRY_NOT_ALLOWED",
		303: "MAX_RETRIES_EXCEEDED",
		400: "TEMPLATE_NOT_FOUND",
		401: "TEMPLATE_ALREADY_EXISTS",
		402: "SYSTEM_TEMPLATE_CANNOT_MODIFY",
		403: "SYSTEM_TEMPLATE_CANNOT_DELETE",
		500: "UNAUTHORIZED",
		501: "FORBIDDEN",
		502: "TOKEN_EXPIRED",
		503: "TOKEN_INVALID",
		504: "RATE_LIMIT_EXCEEDED",
		600: "VALIDATION_FAILED",
		601: "INVALID_PARAMETER",
		602: "MISSING_REQUIRED_FIELD",
	}
	ErrorReason_value = map[string]int32{
		"UNKNOWN":                          0,
		"DATA_SOURCE_NOT_FOUND":            100,
		"DATA_SOURCE_ALREADY_EXISTS":       101,
		"DATA_SOURCE_HAS_ASSOCIATED_TASKS": 102,
		"DATA_SOURCE_DISABLED":             103,
		"DATA_SOURCE_CONNECTION_FAILED":    104,
		"DATA_SOURCE_INVALID_TYPE":         105,
		"DATA_SOURCE_INVALID_STATUS":       106,
		"DATA_SOURCE_INVALID_CONFIG":       107,
		"TASK_NOT_FOUND":                   200,
		"TASK_ALREADY_EXISTS":              201,
		"TASK_INVALID_TYPE":                202,
		"TASK_INVALID_STATUS":              203,
		"TASK_INVALID_SCHEDULE":            204,
		"TASK_CANNOT_START":                205,
		"TASK_CANNOT_STOP":                 206,
		"TASK_CANNOT_PAUSE":                207,
		"EXECUTION_NOT_FOUND":              300,
		"EXECUTION_ALREADY_RUNNING":        301,
		"RETRY_NOT_ALLOWED":                302,
		"MAX_RETRIES_EXCEEDED":             303,
		"TEMPLATE_NOT_FOUND":               400,
		"TEMPLATE_ALREADY_EXISTS":          401,
		"SYSTEM_TEMPLATE_CANNOT_MODIFY":    402,
		"SYSTEM_TEMPLATE_CANNOT_DELETE":    403,
		"UNAUTHORIZED":                     500,
		"FORBIDDEN":                        501,
		"TOKEN_EXPIRED":                    502,
		"TOKEN_INVALID":                    503,
		"RATE_LIMIT_EXCEEDED":              504,
		"VALIDATION_FAILED":                600,
		"INVALID_PARAMETER":                601,
		"MISSING_REQUIRED_FIELD":           602,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\x12metadata.errors.v1\x1a\x13errors/errors.proto*\xbe\b\n" +
	"\vErrorReason\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x1f\n" +
	"\x15DATA_SOURCE_NOT_FOUND\x10d\x1a\x04\xa8E\x94\x03\x12$\n" +
	"\x1aDATA_SOURCE_ALREADY_EXISTS\x10e\x1a\x04\xa8E\x99\x03\x12*\n" +
	" DATA_SOURCE_HAS_ASSOCIATED_TASKS\x10f\x1a\x04\xa8E\x99\x03\x12\x1e\n" +
	"\x14DATA_SOURCE_DISABLED\x10g\x1a\x04\xa8E\x90\x03\x12'\n" +
	"\x1dDATA_SOURCE_CONNECTION_FAILED\x10h\x1a\x04\xa8E\xf7\x03\x12\"\n" +
	"\x18DATA_SOURCE_INVALID_TYPE\x10i\x1a\x04\xa8E\x90\x03\x12$\n" +
	"\x1aDATA_SOURCE_INVALID_STATUS\x10j\x1a\x04\xa8E\x90\x03\x12$\n" +
	"\x1aDATA_SOURCE_INVALID_CONFIG\x10k\x1a\x04\xa8E\x90\x03\x12\x19\n" +
	"\x0eTASK_NOT_FOUND\x10\xc8\x01\x1a\x04\xa8E\x94\x03\x12\x1e\n" +
	"\x13TASK_ALREADY_EXISTS\x10\xc9\x01\x1a\x04\xa8E\x99\x03\x12\x1c\n" +
	"\x11TASK_INVALID_TYPE\x10\xca\x01\x1a\x04\xa8E\x90\x03\x12\x1e\n" +
	"\x13TASK_INVALID_STATUS\x10\xcb\x01\x1a\x04\xa8E\x90\x03\x12 \n" +
	"\x15TASK_INVALID_SCHEDULE\x10\xcc\x01\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x11TASK_CANNOT_START\x10\xcd\x01\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x10TASK_CANNOT_STOP\x10\xce\x01\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x11TASK_CANNOT_PAUSE\x10\xcf\x01\x1a\x04\xa8E\x90\x03\x12\x1e\n" +
	"\x13EXECUTION_NOT_FOUND\x10\xac\x02\x1a\x04\xa8E\x94\x03\x12$\n" +
	"\x19EXECUTION_ALREADY_RUNNING\x10\xad\x02\x1a\x04\xa8E\x99\x03\x12\x1c\n" +
	"\x11RETRY_NOT_ALLOWED\x10\xae\x02\x1a\x04\xa8E\x90\x03\x12\x1f\n" +
	"\x14MAX_RETRIES_EXCEEDED\x10\xaf\x02\x1a\x04\xa8E\x90\x03\x12\x1d\n" +
	"\x12TEMPLATE_NOT_FOUND\x10\x90\x03\x1a\x04\xa8E\x94\x03\x12\"\n" +
	"\x17TEMPLATE_ALREADY_EXISTS\x10\x91\x03\x1a\x04\xa8E\x99\x03\x12(\n" +
	"\x1dSYSTEM_TEMPLATE_CANNOT_MODIFY\x10\x92\x03\x1a\x04\xa8E\x93\x03\x12(\n" +
	"\x1dSYSTEM_TEMPLATE_CANNOT_DELETE\x10\x93\x03\x1a\x04\xa8E\x93\x03\x12\x17\n" +
	"\fUNAUTHORIZED\x10\xf4\x03\x1a\x04\xa8E\x91\x03\x12\x14\n" +
	"\tFORBIDDEN\x10\xf5\x03\x1a\x04\xa8E\x93\x03\x12\x18\n" +
	"\rTOKEN_EXPIRED\x10\xf6\x03\x1a\x04\xa8E\x91\x03\x12\x18\n" +
	"\rTOKEN_INVALID\x10\xf7\x03\x1a\x04\xa8E\x91\x03\x12\x1e\n" +
	"\x13RATE_LIMIT_EXCEEDED\x10\xf8\x03\x1a\x04\xa8E\xad\x03\x12\x1c\n" +
	"\x11VALIDATION_FAILED\x10\xd8\x04\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x11INVALID_PARAMETER\x10\xd9\x04\x1a\x04\xa8E\x90\x03\x12!\n" +
	"\x16MISSING_REQUIRED_FIELD\x10\xda\x04\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x03B\x1fZ\x1dgo-metadata/api/errors;errorsb\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_proto_goTypes = []any{
	(ErrorReason)(0), // 0: metadata.errors.v1.ErrorReason
}
var file_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
