import { DataSourceStrategy, DataSourceConfig } from './types';

const clickhouseStrategy: DataSourceStrategy = {
  type: 'clickhouse',
  label: 'ClickHouse',
  defaultPort: 8123,
  fields: [
    {
      name: 'host',
      label: '主机地址',
      type: 'text',
      required: true,
      placeholder: 'localhost',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'port',
      label: 'HTTP 端口',
      type: 'number',
      required: true,
      defaultValue: 8123,
      width: 'sm',
      group: '基础配置',
      tooltip: 'ClickHouse HTTP 接口端口，默认 8123',
    },
    {
      name: 'database',
      label: '数据库名',
      type: 'text',
      required: true,
      placeholder: 'default',
      defaultValue: 'default',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'username',
      label: '用户名',
      type: 'text',
      placeholder: 'default',
      defaultValue: 'default',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'password',
      label: '密码',
      type: 'password',
      placeholder: '请输入密码',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'native_port',
      label: 'Native 端口',
      type: 'number',
      defaultValue: 9000,
      width: 'sm',
      group: '高级配置',
      tooltip: 'ClickHouse Native 协议端口，默认 9000',
    },
    {
      name: 'cluster',
      label: '集群名称',
      type: 'text',
      placeholder: '如: default_cluster',
      width: 'md',
      group: '高级配置',
      tooltip: '如果是集群部署，填写集群名称',
    },
    {
      name: 'ssl',
      label: '启用 SSL',
      type: 'switch',
      defaultValue: false,
      group: '高级配置',
    },
    {
      name: 'compression',
      label: '启用压缩',
      type: 'switch',
      defaultValue: true,
      group: '高级配置',
    },
    {
      name: 'timeout',
      label: '查询超时(秒)',
      type: 'number',
      defaultValue: 60,
      min: 1,
      width: 'sm',
      group: '高级配置',
    },
    {
      name: 'max_execution_time',
      label: '最大执行时间(秒)',
      type: 'number',
      defaultValue: 300,
      min: 1,
      width: 'sm',
      group: '高级配置',
    },
  ],
  toApiConfig: (values: any): DataSourceConfig => ({
    host: values.host,
    port: values.port || 8123,
    native_port: values.native_port || 9000,
    database: values.database || 'default',
    username: values.username || 'default',
    password: values.password,
    cluster: values.cluster,
    ssl: values.ssl || false,
    compression: values.compression !== false,
    timeout: values.timeout || 60,
    max_execution_time: values.max_execution_time || 300,
  }),
  fromApiConfig: (config: DataSourceConfig): any => ({
    host: config.host,
    port: config.port,
    native_port: config.native_port,
    database: config.database,
    username: config.username,
    password: config.password,
    cluster: config.cluster,
    ssl: config.ssl,
    compression: config.compression,
    timeout: config.timeout,
    max_execution_time: config.max_execution_time,
  }),
};

export { clickhouseStrategy };
