import { DataSourceStrategy, DataSourceConfig } from './types';

const elasticsearchStrategy: DataSourceStrategy = {
  type: 'elasticsearch',
  label: 'Elasticsearch',
  defaultPort: 9200,
  fields: [
    {
      name: 'hosts',
      label: '节点地址',
      type: 'text',
      required: true,
      placeholder: 'http://localhost:9200',
      width: 'lg',
      group: '基础配置',
      tooltip: '多个节点用逗号分隔，如: http://node1:9200,http://node2:9200',
    },
    {
      name: 'username',
      label: '用户名',
      type: 'text',
      placeholder: 'elastic',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'password',
      label: '密码',
      type: 'password',
      placeholder: '请输入密码',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'api_key',
      label: 'API Key',
      type: 'password',
      placeholder: '使用 API Key 认证（可选）',
      width: 'lg',
      group: '高级配置',
      tooltip: '如果使用 API Key 认证，可以不填用户名密码',
    },
    {
      name: 'cloud_id',
      label: 'Cloud ID',
      type: 'text',
      placeholder: 'Elastic Cloud ID（可选）',
      width: 'lg',
      group: '高级配置',
      tooltip: '如果使用 Elastic Cloud，填写 Cloud ID',
    },
    {
      name: 'index_pattern',
      label: '索引模式',
      type: 'text',
      placeholder: '*',
      defaultValue: '*',
      width: 'md',
      group: '高级配置',
      tooltip: '要采集元数据的索引模式，支持通配符',
    },
  ],
  toApiConfig: (values: any): DataSourceConfig => ({
    hosts: values.hosts,
    username: values.username,
    password: values.password,
    api_key: values.api_key,
    cloud_id: values.cloud_id,
    index_pattern: values.index_pattern || '*',
    ssl_verify: values.ssl_verify !== false,
    timeout: values.timeout || 30,
    max_retries: values.max_retries || 3,
  }),
  fromApiConfig: (config: DataSourceConfig): any => ({
    hosts: config.hosts,
    username: config.username,
    password: config.password,
    api_key: config.api_key,
    cloud_id: config.cloud_id,
    index_pattern: config.index_pattern,
    ssl_verify: config.ssl_verify,
    timeout: config.timeout,
    max_retries: config.max_retries,
  }),
};

export { elasticsearchStrategy };
