import { DataSourceStrategy, DataSourceConfig } from './types';

const hiveStrategy: DataSourceStrategy = {
  type: 'hive',
  label: 'Hive',
  defaultPort: 10000,
  fields: [
    {
      name: 'host',
      label: 'HiveServer2 地址',
      type: 'text',
      required: true,
      placeholder: 'localhost',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'port',
      label: '端口',
      type: 'number',
      required: true,
      defaultValue: 10000,
      width: 'sm',
      group: '基础配置',
    },
    {
      name: 'database',
      label: '数据库名',
      type: 'text',
      placeholder: 'default',
      defaultValue: 'default',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'username',
      label: '用户名',
      type: 'text',
      placeholder: 'hive',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'password',
      label: '密码',
      type: 'password',
      placeholder: '请输入密码',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'auth_mode',
      label: '认证模式',
      type: 'select',
      defaultValue: 'NONE',
      options: [
        { label: 'NONE', value: 'NONE' },
        { label: 'NOSASL', value: 'NOSASL' },
        { label: 'KERBEROS', value: 'KERBEROS' },
        { label: 'LDAP', value: 'LDAP' },
        { label: 'CUSTOM', value: 'CUSTOM' },
      ],
      width: 'md',
      group: '高级配置',
    },
    {
      name: 'kerberos_principal',
      label: 'Kerberos Principal',
      type: 'text',
      placeholder: 'hive/_HOST@REALM',
      width: 'lg',
      group: '高级配置',
      tooltip: 'HiveServer2 的 Kerberos Principal',
    },
    {
      name: 'kerberos_keytab',
      label: 'Keytab 路径',
      type: 'text',
      placeholder: '/etc/security/keytabs/hive.keytab',
      width: 'lg',
      group: '高级配置',
    },
    {
      name: 'metastore_uri',
      label: 'Metastore URI',
      type: 'text',
      placeholder: 'thrift://localhost:9083',
      width: 'lg',
      group: '高级配置',
      tooltip: 'Hive Metastore Thrift URI',
    },
    {
      name: 'transport_mode',
      label: '传输模式',
      type: 'select',
      defaultValue: 'binary',
      options: [
        { label: 'binary', value: 'binary' },
        { label: 'http', value: 'http' },
      ],
      width: 'sm',
      group: '高级配置',
    },
    {
      name: 'http_path',
      label: 'HTTP 路径',
      type: 'text',
      placeholder: 'cliservice',
      defaultValue: 'cliservice',
      width: 'md',
      group: '高级配置',
      tooltip: '当传输模式为 http 时使用',
    },
    {
      name: 'ssl',
      label: '启用 SSL',
      type: 'switch',
      defaultValue: false,
      group: '高级配置',
    },
    {
      name: 'timeout',
      label: '连接超时(秒)',
      type: 'number',
      defaultValue: 60,
      min: 1,
      width: 'sm',
      group: '高级配置',
    },
  ],
  toApiConfig: (values: any): DataSourceConfig => ({
    host: values.host,
    port: values.port || 10000,
    database: values.database || 'default',
    username: values.username,
    password: values.password,
    auth_mode: values.auth_mode || 'NONE',
    kerberos_principal: values.kerberos_principal,
    kerberos_keytab: values.kerberos_keytab,
    metastore_uri: values.metastore_uri,
    transport_mode: values.transport_mode || 'binary',
    http_path: values.http_path || 'cliservice',
    ssl: values.ssl || false,
    timeout: values.timeout || 60,
  }),
  fromApiConfig: (config: DataSourceConfig): any => ({
    host: config.host,
    port: config.port,
    database: config.database,
    username: config.username,
    password: config.password,
    auth_mode: config.auth_mode,
    kerberos_principal: config.kerberos_principal,
    kerberos_keytab: config.kerberos_keytab,
    metastore_uri: config.metastore_uri,
    transport_mode: config.transport_mode,
    http_path: config.http_path,
    ssl: config.ssl,
    timeout: config.timeout,
  }),
};

export { hiveStrategy };
