import { DataSourceStrategy, DataSourceConfig } from './types';

const kafkaStrategy: DataSourceStrategy = {
  type: 'kafka',
  label: 'Kafka',
  defaultPort: 9092,
  fields: [
    {
      name: 'brokers',
      label: 'Broker 地址',
      type: 'text',
      required: true,
      placeholder: 'localhost:9092,localhost:9093',
      width: 'lg',
      group: '基础配置',
      tooltip: '多个 Broker 用逗号分隔',
    },
    {
      name: 'username',
      label: 'SASL 用户名',
      type: 'text',
      placeholder: '请输入用户名',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'password',
      label: 'SASL 密码',
      type: 'password',
      placeholder: '请输入密码',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'client_id',
      label: 'Client ID',
      type: 'text',
      placeholder: 'metadata-collector',
      width: 'md',
      group: '高级配置',
    },
    {
      name: 'security_protocol',
      label: '安全协议',
      type: 'select',
      defaultValue: 'PLAINTEXT',
      options: [
        { label: 'PLAINTEXT', value: 'PLAINTEXT' },
        { label: 'SSL', value: 'SSL' },
        { label: 'SASL_PLAINTEXT', value: 'SASL_PLAINTEXT' },
        { label: 'SASL_SSL', value: 'SASL_SSL' },
      ],
      width: 'md',
      group: '高级配置',
    },
    {
      name: 'sasl_mechanism',
      label: 'SASL 机制',
      type: 'select',
      defaultValue: 'PLAIN',
      options: [
        { label: 'PLAIN', value: 'PLAIN' },
        { label: 'SCRAM-SHA-256', value: 'SCRAM-SHA-256' },
        { label: 'SCRAM-SHA-512', value: 'SCRAM-SHA-512' },
        { label: 'GSSAPI', value: 'GSSAPI' },
      ],
      width: 'md',
      group: '高级配置',
    },
    {
      name: 'schema_registry_url',
      label: 'Schema Registry URL',
      type: 'text',
      placeholder: 'http://localhost:8081',
      width: 'lg',
      group: '高级配置',
      tooltip: 'Confluent Schema Registry 地址',
    },
    {
      name: 'timeout',
      label: '连接超时(秒)',
      type: 'number',
      defaultValue: 30,
      min: 1,
      width: 'sm',
      group: '高级配置',
    },
  ],
  toApiConfig: (values: any): DataSourceConfig => ({
    brokers: values.brokers,
    client_id: values.client_id,
    security_protocol: values.security_protocol || 'PLAINTEXT',
    sasl_mechanism: values.sasl_mechanism || 'PLAIN',
    username: values.username,
    password: values.password,
    schema_registry_url: values.schema_registry_url,
    timeout: values.timeout || 30,
  }),
  fromApiConfig: (config: DataSourceConfig): any => ({
    brokers: config.brokers,
    client_id: config.client_id,
    security_protocol: config.security_protocol,
    sasl_mechanism: config.sasl_mechanism,
    username: config.username,
    password: config.password,
    schema_registry_url: config.schema_registry_url,
    timeout: config.timeout,
  }),
};

export { kafkaStrategy };
