import { DataSourceStrategy, DataSourceConfig } from './types';

const mongodbStrategy: DataSourceStrategy = {
  type: 'mongodb',
  label: 'MongoDB',
  defaultPort: 27017,
  fields: [
    {
      name: 'host',
      label: '主机地址',
      type: 'text',
      required: true,
      placeholder: 'localhost',
      tooltip: '支持多个主机，用逗号分隔，如: host1:27017,host2:27017',
      width: 'lg',
      group: '基础配置',
    },
    {
      name: 'port',
      label: '端口',
      type: 'number',
      required: true,
      defaultValue: 27017,
      width: 'sm',
      group: '基础配置',
    },
    {
      name: 'database',
      label: '数据库名',
      type: 'text',
      required: true,
      placeholder: 'admin',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'username',
      label: '用户名',
      type: 'text',
      placeholder: '请输入用户名',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'password',
      label: '密码',
      type: 'password',
      placeholder: '请输入密码',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'auth_source',
      label: '认证数据库',
      type: 'text',
      placeholder: 'admin',
      defaultValue: 'admin',
      width: 'md',
      group: '高级配置',
      tooltip: '用于认证的数据库，默认为 admin',
    },
    {
      name: 'auth_mechanism',
      label: '认证机制',
      type: 'select',
      defaultValue: 'SCRAM-SHA-256',
      options: [
        { label: 'SCRAM-SHA-256', value: 'SCRAM-SHA-256' },
        { label: 'SCRAM-SHA-1', value: 'SCRAM-SHA-1' },
        { label: 'MONGODB-CR', value: 'MONGODB-CR' },
        { label: 'PLAIN', value: 'PLAIN' },
      ],
      width: 'md',
      group: '高级配置',
    },
    {
      name: 'replica_set',
      label: '副本集名称',
      type: 'text',
      placeholder: '如: rs0',
      width: 'md',
      group: '高级配置',
      tooltip: '如果连接副本集，请填写副本集名称',
    },
    {
      name: 'ssl',
      label: '启用 SSL/TLS',
      type: 'switch',
      defaultValue: false,
      group: '高级配置',
    },
    {
      name: 'direct_connection',
      label: '直连模式',
      type: 'switch',
      defaultValue: false,
      group: '高级配置',
      tooltip: '直接连接到指定主机，不进行副本集发现',
    },
    {
      name: 'timeout',
      label: '连接超时(秒)',
      type: 'number',
      defaultValue: 30,
      min: 1,
      width: 'sm',
      group: '高级配置',
    },
  ],
  toApiConfig: (values: any): DataSourceConfig => ({
    host: values.host,
    port: values.port || 27017,
    database: values.database,
    username: values.username,
    password: values.password,
    auth_source: values.auth_source || 'admin',
    auth_mechanism: values.auth_mechanism || 'SCRAM-SHA-256',
    replica_set: values.replica_set,
    ssl: values.ssl || false,
    direct_connection: values.direct_connection || false,
    timeout: values.timeout || 30,
  }),
  fromApiConfig: (config: DataSourceConfig): any => ({
    host: config.host,
    port: config.port,
    database: config.database,
    username: config.username,
    password: config.password,
    auth_source: config.auth_source,
    auth_mechanism: config.auth_mechanism,
    replica_set: config.replica_set,
    ssl: config.ssl,
    direct_connection: config.direct_connection,
    timeout: config.timeout,
  }),
};

export { mongodbStrategy };
