import { DataSourceStrategy, DataSourceConfig } from './types';

const mysqlStrategy: DataSourceStrategy = {
  type: 'mysql',
  label: 'MySQL',
  defaultPort: 3306,
  fields: [
    {
      name: 'host',
      label: '主机地址',
      type: 'text',
      required: true,
      placeholder: 'localhost',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'port',
      label: '端口',
      type: 'number',
      required: true,
      defaultValue: 3306,
      width: 'sm',
      group: '基础配置',
    },
    {
      name: 'database',
      label: '数据库名',
      type: 'text',
      required: true,
      placeholder: '请输入数据库名',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'username',
      label: '用户名',
      type: 'text',
      required: true,
      placeholder: 'root',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'password',
      label: '密码',
      type: 'password',
      placeholder: '请输入密码',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'charset',
      label: '字符集',
      type: 'select',
      defaultValue: 'utf8mb4',
      options: [
        { label: 'utf8mb4', value: 'utf8mb4' },
        { label: 'utf8', value: 'utf8' },
        { label: 'latin1', value: 'latin1' },
        { label: 'gbk', value: 'gbk' },
      ],
      width: 'sm',
      group: '高级配置',
    },
    {
      name: 'ssl',
      label: '启用 SSL',
      type: 'switch',
      defaultValue: false,
      group: '高级配置',
    },
    {
      name: 'ssl_mode',
      label: 'SSL 模式',
      type: 'select',
      defaultValue: 'preferred',
      options: [
        { label: 'disabled', value: 'disabled' },
        { label: 'preferred', value: 'preferred' },
        { label: 'required', value: 'required' },
        { label: 'verify_ca', value: 'verify_ca' },
        { label: 'verify_identity', value: 'verify_identity' },
      ],
      width: 'sm',
      group: '高级配置',
    },
    {
      name: 'timeout',
      label: '连接超时(秒)',
      type: 'number',
      defaultValue: 30,
      min: 1,
      max: 300,
      width: 'sm',
      group: '高级配置',
    },
  ],
  toApiConfig: (values: any): DataSourceConfig => ({
    host: values.host,
    port: values.port || 3306,
    database: values.database,
    username: values.username,
    password: values.password,
    charset: values.charset || 'utf8mb4',
    ssl: values.ssl || false,
    ssl_mode: values.ssl_mode || 'preferred',
    timeout: values.timeout || 30,
  }),
  fromApiConfig: (config: DataSourceConfig): any => ({
    host: config.host,
    port: config.port,
    database: config.database,
    username: config.username,
    password: config.password,
    charset: config.charset,
    ssl: config.ssl,
    ssl_mode: config.ssl_mode,
    timeout: config.timeout,
  }),
};

export { mysqlStrategy };
