import { DataSourceStrategy, DataSourceConfig } from './types';

const postgresqlStrategy: DataSourceStrategy = {
  type: 'postgresql',
  label: 'PostgreSQL',
  defaultPort: 5432,
  fields: [
    {
      name: 'host',
      label: '主机地址',
      type: 'text',
      required: true,
      placeholder: 'localhost',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'port',
      label: '端口',
      type: 'number',
      required: true,
      defaultValue: 5432,
      width: 'sm',
      group: '基础配置',
    },
    {
      name: 'database',
      label: '数据库名',
      type: 'text',
      required: true,
      placeholder: 'postgres',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'username',
      label: '用户名',
      type: 'text',
      required: true,
      placeholder: 'postgres',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'password',
      label: '密码',
      type: 'password',
      placeholder: '请输入密码',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'schema',
      label: 'Schema',
      type: 'text',
      placeholder: 'public',
      defaultValue: 'public',
      width: 'md',
      group: '高级配置',
      tooltip: 'PostgreSQL schema，默认为 public',
    },
    {
      name: 'sslmode',
      label: 'SSL 模式',
      type: 'select',
      defaultValue: 'disable',
      options: [
        { label: 'disable', value: 'disable' },
        { label: 'allow', value: 'allow' },
        { label: 'prefer', value: 'prefer' },
        { label: 'require', value: 'require' },
        { label: 'verify-ca', value: 'verify-ca' },
        { label: 'verify-full', value: 'verify-full' },
      ],
      width: 'sm',
      group: '高级配置',
    },
    {
      name: 'timeout',
      label: '连接超时(秒)',
      type: 'number',
      defaultValue: 30,
      min: 1,
      width: 'sm',
      group: '高级配置',
    },
  ],
  toApiConfig: (values: any): DataSourceConfig => ({
    host: values.host,
    port: values.port || 5432,
    database: values.database,
    schema: values.schema || 'public',
    username: values.username,
    password: values.password,
    sslmode: values.sslmode || 'disable',
    timeout: values.timeout || 30,
  }),
  fromApiConfig: (config: DataSourceConfig): any => ({
    host: config.host,
    port: config.port,
    database: config.database,
    schema: config.schema,
    username: config.username,
    password: config.password,
    sslmode: config.sslmode,
    timeout: config.timeout,
  }),
};

export { postgresqlStrategy };
