import { DataSourceStrategy, DataSourceConfig } from './types';

const redisStrategy: DataSourceStrategy = {
  type: 'redis',
  label: 'Redis',
  defaultPort: 6379,
  fields: [
    {
      name: 'host',
      label: '主机地址',
      type: 'text',
      required: true,
      placeholder: 'localhost',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'port',
      label: '端口',
      type: 'number',
      required: true,
      defaultValue: 6379,
      width: 'sm',
      group: '基础配置',
    },
    {
      name: 'password',
      label: '密码',
      type: 'password',
      placeholder: '请输入密码（如果有）',
      width: 'md',
      group: '基础配置',
    },
    {
      name: 'db',
      label: '数据库索引',
      type: 'number',
      defaultValue: 0,
      min: 0,
      max: 15,
      width: 'sm',
      group: '基础配置',
      tooltip: 'Redis 数据库索引，0-15',
    },
    {
      name: 'username',
      label: '用户名',
      type: 'text',
      placeholder: 'Redis 6.0+ ACL 用户名',
      width: 'md',
      group: '高级配置',
      tooltip: 'Redis 6.0+ 支持 ACL 用户名',
    },
    {
      name: 'cluster_mode',
      label: '集群模式',
      type: 'switch',
      defaultValue: false,
      group: '高级配置',
      tooltip: '是否为 Redis Cluster 集群',
    },
    {
      name: 'sentinel_mode',
      label: '哨兵模式',
      type: 'switch',
      defaultValue: false,
      group: '高级配置',
    },
    {
      name: 'master_name',
      label: 'Master 名称',
      type: 'text',
      placeholder: 'mymaster',
      width: 'md',
      group: '高级配置',
      tooltip: '哨兵模式下的 Master 名称',
    },
    {
      name: 'ssl',
      label: '启用 SSL/TLS',
      type: 'switch',
      defaultValue: false,
      group: '高级配置',
    },
    {
      name: 'timeout',
      label: '连接超时(秒)',
      type: 'number',
      defaultValue: 5,
      min: 1,
      width: 'sm',
      group: '高级配置',
    },
  ],
  toApiConfig: (values: any): DataSourceConfig => ({
    host: values.host,
    port: values.port || 6379,
    password: values.password,
    db: values.db || 0,
    username: values.username,
    cluster_mode: values.cluster_mode || false,
    sentinel_mode: values.sentinel_mode || false,
    master_name: values.master_name,
    ssl: values.ssl || false,
    timeout: values.timeout || 5,
  }),
  fromApiConfig: (config: DataSourceConfig): any => ({
    host: config.host,
    port: config.port,
    password: config.password,
    db: config.db,
    username: config.username,
    cluster_mode: config.cluster_mode,
    sentinel_mode: config.sentinel_mode,
    master_name: config.master_name,
    ssl: config.ssl,
    timeout: config.timeout,
  }),
};

export { redisStrategy };
