// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: datasource.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 数据源类型
type DataSourceType int32

const (
	DataSourceType_DATA_SOURCE_TYPE_UNSPECIFIED   DataSourceType = 0
	DataSourceType_DATA_SOURCE_TYPE_MYSQL         DataSourceType = 1
	DataSourceType_DATA_SOURCE_TYPE_POSTGRESQL    DataSourceType = 2
	DataSourceType_DATA_SOURCE_TYPE_ORACLE        DataSourceType = 3
	DataSourceType_DATA_SOURCE_TYPE_SQLSERVER     DataSourceType = 4
	DataSourceType_DATA_SOURCE_TYPE_MONGODB       DataSourceType = 5
	DataSourceType_DATA_SOURCE_TYPE_REDIS         DataSourceType = 6
	DataSourceType_DATA_SOURCE_TYPE_KAFKA         DataSourceType = 7
	DataSourceType_DATA_SOURCE_TYPE_RABBITMQ      DataSourceType = 8
	DataSourceType_DATA_SOURCE_TYPE_MINIO         DataSourceType = 9
	DataSourceType_DATA_SOURCE_TYPE_CLICKHOUSE    DataSourceType = 10
	DataSourceType_DATA_SOURCE_TYPE_DORIS         DataSourceType = 11
	DataSourceType_DATA_SOURCE_TYPE_HIVE          DataSourceType = 12
	DataSourceType_DATA_SOURCE_TYPE_ELASTICSEARCH DataSourceType = 13
)

// Enum value maps for DataSourceType.
var (
	DataSourceType_name = map[int32]string{
		0:  "DATA_SOURCE_TYPE_UNSPECIFIED",
		1:  "DATA_SOURCE_TYPE_MYSQL",
		2:  "DATA_SOURCE_TYPE_POSTGRESQL",
		3:  "DATA_SOURCE_TYPE_ORACLE",
		4:  "DATA_SOURCE_TYPE_SQLSERVER",
		5:  "DATA_SOURCE_TYPE_MONGODB",
		6:  "DATA_SOURCE_TYPE_REDIS",
		7:  "DATA_SOURCE_TYPE_KAFKA",
		8:  "DATA_SOURCE_TYPE_RABBITMQ",
		9:  "DATA_SOURCE_TYPE_MINIO",
		10: "DATA_SOURCE_TYPE_CLICKHOUSE",
		11: "DATA_SOURCE_TYPE_DORIS",
		12: "DATA_SOURCE_TYPE_HIVE",
		13: "DATA_SOURCE_TYPE_ELASTICSEARCH",
	}
	DataSourceType_value = map[string]int32{
		"DATA_SOURCE_TYPE_UNSPECIFIED":   0,
		"DATA_SOURCE_TYPE_MYSQL":         1,
		"DATA_SOURCE_TYPE_POSTGRESQL":    2,
		"DATA_SOURCE_TYPE_ORACLE":        3,
		"DATA_SOURCE_TYPE_SQLSERVER":     4,
		"DATA_SOURCE_TYPE_MONGODB":       5,
		"DATA_SOURCE_TYPE_REDIS":         6,
		"DATA_SOURCE_TYPE_KAFKA":         7,
		"DATA_SOURCE_TYPE_RABBITMQ":      8,
		"DATA_SOURCE_TYPE_MINIO":         9,
		"DATA_SOURCE_TYPE_CLICKHOUSE":    10,
		"DATA_SOURCE_TYPE_DORIS":         11,
		"DATA_SOURCE_TYPE_HIVE":          12,
		"DATA_SOURCE_TYPE_ELASTICSEARCH": 13,
	}
)

func (x DataSourceType) Enum() *DataSourceType {
	p := new(DataSourceType)
	*p = x
	return p
}

func (x DataSourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataSourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_datasource_proto_enumTypes[0].Descriptor()
}

func (DataSourceType) Type() protoreflect.EnumType {
	return &file_datasource_proto_enumTypes[0]
}

func (x DataSourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataSourceType.Descriptor instead.
func (DataSourceType) EnumDescriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{0}
}

// 数据源状态
type DataSourceStatus int32

const (
	DataSourceStatus_DATA_SOURCE_STATUS_UNSPECIFIED DataSourceStatus = 0
	DataSourceStatus_DATA_SOURCE_STATUS_ACTIVE      DataSourceStatus = 1
	DataSourceStatus_DATA_SOURCE_STATUS_INACTIVE    DataSourceStatus = 2
	DataSourceStatus_DATA_SOURCE_STATUS_ERROR       DataSourceStatus = 3
	DataSourceStatus_DATA_SOURCE_STATUS_TESTING     DataSourceStatus = 4
)

// Enum value maps for DataSourceStatus.
var (
	DataSourceStatus_name = map[int32]string{
		0: "DATA_SOURCE_STATUS_UNSPECIFIED",
		1: "DATA_SOURCE_STATUS_ACTIVE",
		2: "DATA_SOURCE_STATUS_INACTIVE",
		3: "DATA_SOURCE_STATUS_ERROR",
		4: "DATA_SOURCE_STATUS_TESTING",
	}
	DataSourceStatus_value = map[string]int32{
		"DATA_SOURCE_STATUS_UNSPECIFIED": 0,
		"DATA_SOURCE_STATUS_ACTIVE":      1,
		"DATA_SOURCE_STATUS_INACTIVE":    2,
		"DATA_SOURCE_STATUS_ERROR":       3,
		"DATA_SOURCE_STATUS_TESTING":     4,
	}
)

func (x DataSourceStatus) Enum() *DataSourceStatus {
	p := new(DataSourceStatus)
	*p = x
	return p
}

func (x DataSourceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataSourceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_datasource_proto_enumTypes[1].Descriptor()
}

func (DataSourceStatus) Type() protoreflect.EnumType {
	return &file_datasource_proto_enumTypes[1]
}

func (x DataSourceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataSourceStatus.Descriptor instead.
func (DataSourceStatus) EnumDescriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{1}
}

// 连接配置
type ConnectionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Database      string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Ssl           bool                   `protobuf:"varint,6,opt,name=ssl,proto3" json:"ssl,omitempty"`
	SslMode       string                 `protobuf:"bytes,7,opt,name=ssl_mode,json=sslMode,proto3" json:"ssl_mode,omitempty"`
	Timeout       int32                  `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MaxConns      int32                  `protobuf:"varint,9,opt,name=max_conns,json=maxConns,proto3" json:"max_conns,omitempty"`
	MaxIdleConns  int32                  `protobuf:"varint,10,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	Charset       string                 `protobuf:"bytes,11,opt,name=charset,proto3" json:"charset,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,12,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionConfig) Reset() {
	*x = ConnectionConfig{}
	mi := &file_datasource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionConfig) ProtoMessage() {}

func (x *ConnectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionConfig.ProtoReflect.Descriptor instead.
func (*ConnectionConfig) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConnectionConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectionConfig) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ConnectionConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ConnectionConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ConnectionConfig) GetSsl() bool {
	if x != nil {
		return x.Ssl
	}
	return false
}

func (x *ConnectionConfig) GetSslMode() string {
	if x != nil {
		return x.SslMode
	}
	return ""
}

func (x *ConnectionConfig) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ConnectionConfig) GetMaxConns() int32 {
	if x != nil {
		return x.MaxConns
	}
	return 0
}

func (x *ConnectionConfig) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *ConnectionConfig) GetCharset() string {
	if x != nil {
		return x.Charset
	}
	return ""
}

func (x *ConnectionConfig) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// 数据源
type DataSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          DataSourceType         `protobuf:"varint,3,opt,name=type,proto3,enum=api.metadata.v1.DataSourceType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Config        *ConnectionConfig      `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	Status        DataSourceStatus       `protobuf:"varint,6,opt,name=status,proto3,enum=api.metadata.v1.DataSourceStatus" json:"status,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastTestAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_test_at,json=lastTestAt,proto3" json:"last_test_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSource) Reset() {
	*x = DataSource{}
	mi := &file_datasource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSource) ProtoMessage() {}

func (x *DataSource) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSource.ProtoReflect.Descriptor instead.
func (*DataSource) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{1}
}

func (x *DataSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataSource) GetType() DataSourceType {
	if x != nil {
		return x.Type
	}
	return DataSourceType_DATA_SOURCE_TYPE_UNSPECIFIED
}

func (x *DataSource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DataSource) GetConfig() *ConnectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DataSource) GetStatus() DataSourceStatus {
	if x != nil {
		return x.Status
	}
	return DataSourceStatus_DATA_SOURCE_STATUS_UNSPECIFIED
}

func (x *DataSource) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DataSource) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *DataSource) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DataSource) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DataSource) GetLastTestAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTestAt
	}
	return nil
}

// 创建数据源请求
type CreateDataSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          DataSourceType         `protobuf:"varint,2,opt,name=type,proto3,enum=api.metadata.v1.DataSourceType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Config        *ConnectionConfig      `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDataSourceRequest) Reset() {
	*x = CreateDataSourceRequest{}
	mi := &file_datasource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDataSourceRequest) ProtoMessage() {}

func (x *CreateDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDataSourceRequest.ProtoReflect.Descriptor instead.
func (*CreateDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDataSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDataSourceRequest) GetType() DataSourceType {
	if x != nil {
		return x.Type
	}
	return DataSourceType_DATA_SOURCE_TYPE_UNSPECIFIED
}

func (x *CreateDataSourceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDataSourceRequest) GetConfig() *ConnectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateDataSourceRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 更新数据源请求
type UpdateDataSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Config        *ConnectionConfig      `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataSourceRequest) Reset() {
	*x = UpdateDataSourceRequest{}
	mi := &file_datasource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataSourceRequest) ProtoMessage() {}

func (x *UpdateDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataSourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDataSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDataSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDataSourceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateDataSourceRequest) GetConfig() *ConnectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateDataSourceRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 删除数据源请求
type DeleteDataSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataSourceRequest) Reset() {
	*x = DeleteDataSourceRequest{}
	mi := &file_datasource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataSourceRequest) ProtoMessage() {}

func (x *DeleteDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataSourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDataSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取数据源请求
type GetDataSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataSourceRequest) Reset() {
	*x = GetDataSourceRequest{}
	mi := &file_datasource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataSourceRequest) ProtoMessage() {}

func (x *GetDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataSourceRequest.ProtoReflect.Descriptor instead.
func (*GetDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{5}
}

func (x *GetDataSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 列出数据源请求
type ListDataSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Type          DataSourceType         `protobuf:"varint,3,opt,name=type,proto3,enum=api.metadata.v1.DataSourceType" json:"type,omitempty"`
	Status        DataSourceStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=api.metadata.v1.DataSourceStatus" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDataSourcesRequest) Reset() {
	*x = ListDataSourcesRequest{}
	mi := &file_datasource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDataSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataSourcesRequest) ProtoMessage() {}

func (x *ListDataSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListDataSourcesRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{6}
}

func (x *ListDataSourcesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDataSourcesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDataSourcesRequest) GetType() DataSourceType {
	if x != nil {
		return x.Type
	}
	return DataSourceType_DATA_SOURCE_TYPE_UNSPECIFIED
}

func (x *ListDataSourcesRequest) GetStatus() DataSourceStatus {
	if x != nil {
		return x.Status
	}
	return DataSourceStatus_DATA_SOURCE_STATUS_UNSPECIFIED
}

func (x *ListDataSourcesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 列出数据源响应
type ListDataSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataSources   []*DataSource          `protobuf:"bytes,1,rep,name=data_sources,json=dataSources,proto3" json:"data_sources,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDataSourcesResponse) Reset() {
	*x = ListDataSourcesResponse{}
	mi := &file_datasource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDataSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataSourcesResponse) ProtoMessage() {}

func (x *ListDataSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListDataSourcesResponse) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{7}
}

func (x *ListDataSourcesResponse) GetDataSources() []*DataSource {
	if x != nil {
		return x.DataSources
	}
	return nil
}

func (x *ListDataSourcesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDataSourcesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDataSourcesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 测试连接请求
type TestConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionRequest) Reset() {
	*x = TestConnectionRequest{}
	mi := &file_datasource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionRequest) ProtoMessage() {}

func (x *TestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionRequest.ProtoReflect.Descriptor instead.
func (*TestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{8}
}

func (x *TestConnectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 使用配置测试连接请求
type TestConnectionWithConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DataSourceType         `protobuf:"varint,1,opt,name=type,proto3,enum=api.metadata.v1.DataSourceType" json:"type,omitempty"`
	Config        *ConnectionConfig      `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionWithConfigRequest) Reset() {
	*x = TestConnectionWithConfigRequest{}
	mi := &file_datasource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionWithConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionWithConfigRequest) ProtoMessage() {}

func (x *TestConnectionWithConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionWithConfigRequest.ProtoReflect.Descriptor instead.
func (*TestConnectionWithConfigRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{9}
}

func (x *TestConnectionWithConfigRequest) GetType() DataSourceType {
	if x != nil {
		return x.Type
	}
	return DataSourceType_DATA_SOURCE_TYPE_UNSPECIFIED
}

func (x *TestConnectionWithConfigRequest) GetConfig() *ConnectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// 连接测试结果
type ConnectionTestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Latency       int64                  `protobuf:"varint,3,opt,name=latency,proto3" json:"latency,omitempty"`
	ServerInfo    string                 `protobuf:"bytes,4,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
	DatabaseInfo  string                 `protobuf:"bytes,5,opt,name=database_info,json=databaseInfo,proto3" json:"database_info,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionTestResult) Reset() {
	*x = ConnectionTestResult{}
	mi := &file_datasource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionTestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionTestResult) ProtoMessage() {}

func (x *ConnectionTestResult) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionTestResult.ProtoReflect.Descriptor instead.
func (*ConnectionTestResult) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectionTestResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectionTestResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectionTestResult) GetLatency() int64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *ConnectionTestResult) GetServerInfo() string {
	if x != nil {
		return x.ServerInfo
	}
	return ""
}

func (x *ConnectionTestResult) GetDatabaseInfo() string {
	if x != nil {
		return x.DatabaseInfo
	}
	return ""
}

func (x *ConnectionTestResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 刷新连接状态请求
type RefreshConnectionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshConnectionStatusRequest) Reset() {
	*x = RefreshConnectionStatusRequest{}
	mi := &file_datasource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshConnectionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshConnectionStatusRequest) ProtoMessage() {}

func (x *RefreshConnectionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshConnectionStatusRequest.ProtoReflect.Descriptor instead.
func (*RefreshConnectionStatusRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshConnectionStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 更新数据源状态请求
type UpdateDataSourceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        DataSourceStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=api.metadata.v1.DataSourceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataSourceStatusRequest) Reset() {
	*x = UpdateDataSourceStatusRequest{}
	mi := &file_datasource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataSourceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataSourceStatusRequest) ProtoMessage() {}

func (x *UpdateDataSourceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataSourceStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataSourceStatusRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDataSourceStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDataSourceStatusRequest) GetStatus() DataSourceStatus {
	if x != nil {
		return x.Status
	}
	return DataSourceStatus_DATA_SOURCE_STATUS_UNSPECIFIED
}

// 数据源统计
type DataSourceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	ActiveCount   int64                  `protobuf:"varint,2,opt,name=active_count,json=activeCount,proto3" json:"active_count,omitempty"`
	InactiveCount int64                  `protobuf:"varint,3,opt,name=inactive_count,json=inactiveCount,proto3" json:"inactive_count,omitempty"`
	ErrorCount    int64                  `protobuf:"varint,4,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceStats) Reset() {
	*x = DataSourceStats{}
	mi := &file_datasource_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceStats) ProtoMessage() {}

func (x *DataSourceStats) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceStats.ProtoReflect.Descriptor instead.
func (*DataSourceStats) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{13}
}

func (x *DataSourceStats) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *DataSourceStats) GetActiveCount() int64 {
	if x != nil {
		return x.ActiveCount
	}
	return 0
}

func (x *DataSourceStats) GetInactiveCount() int64 {
	if x != nil {
		return x.InactiveCount
	}
	return 0
}

func (x *DataSourceStats) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

// 检查是否可以删除请求
type CanDeleteDataSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanDeleteDataSourceRequest) Reset() {
	*x = CanDeleteDataSourceRequest{}
	mi := &file_datasource_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanDeleteDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanDeleteDataSourceRequest) ProtoMessage() {}

func (x *CanDeleteDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanDeleteDataSourceRequest.ProtoReflect.Descriptor instead.
func (*CanDeleteDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{14}
}

func (x *CanDeleteDataSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 检查是否可以删除结果
type CanDeleteResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CanDelete       bool                   `protobuf:"varint,1,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	AssociatedTasks int32                  `protobuf:"varint,3,opt,name=associated_tasks,json=associatedTasks,proto3" json:"associated_tasks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CanDeleteResult) Reset() {
	*x = CanDeleteResult{}
	mi := &file_datasource_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanDeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanDeleteResult) ProtoMessage() {}

func (x *CanDeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanDeleteResult.ProtoReflect.Descriptor instead.
func (*CanDeleteResult) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{15}
}

func (x *CanDeleteResult) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

func (x *CanDeleteResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CanDeleteResult) GetAssociatedTasks() int32 {
	if x != nil {
		return x.AssociatedTasks
	}
	return 0
}

// 批量更新状态请求
type BatchUpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Status        DataSourceStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=api.metadata.v1.DataSourceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateStatusRequest) Reset() {
	*x = BatchUpdateStatusRequest{}
	mi := &file_datasource_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateStatusRequest) ProtoMessage() {}

func (x *BatchUpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{16}
}

func (x *BatchUpdateStatusRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BatchUpdateStatusRequest) GetStatus() DataSourceStatus {
	if x != nil {
		return x.Status
	}
	return DataSourceStatus_DATA_SOURCE_STATUS_UNSPECIFIED
}

// 批量操作结果
type BatchOperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Success       int32                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOperationResult) Reset() {
	*x = BatchOperationResult{}
	mi := &file_datasource_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOperationResult) ProtoMessage() {}

func (x *BatchOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOperationResult.ProtoReflect.Descriptor instead.
func (*BatchOperationResult) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{17}
}

func (x *BatchOperationResult) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BatchOperationResult) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *BatchOperationResult) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchOperationResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// 批量导入请求
type BatchImportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchImportRequest) Reset() {
	*x = BatchImportRequest{}
	mi := &file_datasource_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchImportRequest) ProtoMessage() {}

func (x *BatchImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchImportRequest.ProtoReflect.Descriptor instead.
func (*BatchImportRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{18}
}

func (x *BatchImportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *BatchImportRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// 批量导入结果
type BatchImportResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Success       int32                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	DataSources   []*DataSource          `protobuf:"bytes,4,rep,name=data_sources,json=dataSources,proto3" json:"data_sources,omitempty"`
	Errors        []string               `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchImportResult) Reset() {
	*x = BatchImportResult{}
	mi := &file_datasource_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchImportResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchImportResult) ProtoMessage() {}

func (x *BatchImportResult) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchImportResult.ProtoReflect.Descriptor instead.
func (*BatchImportResult) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{19}
}

func (x *BatchImportResult) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BatchImportResult) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *BatchImportResult) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchImportResult) GetDataSources() []*DataSource {
	if x != nil {
		return x.DataSources
	}
	return nil
}

func (x *BatchImportResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// 批量导出请求
type BatchExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchExportRequest) Reset() {
	*x = BatchExportRequest{}
	mi := &file_datasource_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExportRequest) ProtoMessage() {}

func (x *BatchExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExportRequest.ProtoReflect.Descriptor instead.
func (*BatchExportRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{20}
}

func (x *BatchExportRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BatchExportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// 批量导出响应
type BatchExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchExportResponse) Reset() {
	*x = BatchExportResponse{}
	mi := &file_datasource_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchExportResponse) ProtoMessage() {}

func (x *BatchExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchExportResponse.ProtoReflect.Descriptor instead.
func (*BatchExportResponse) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{21}
}

func (x *BatchExportResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *BatchExportResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *BatchExportResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_datasource_proto protoreflect.FileDescriptor

const file_datasource_proto_rawDesc = "" +
	"\n" +
	"\x10datasource.proto\x12\x0fapi.metadata.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\"\x80\x04\n" +
	"\x10ConnectionConfig\x12\x1e\n" +
	"\x04host\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\x04host\x12\x1f\n" +
	"\x04port\x18\x02 \x01(\x05B\v\xfaB\b\x1a\x06\x18\xff\xff\x03(\x01R\x04port\x12$\n" +
	"\bdatabase\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xff\x01R\bdatabase\x12$\n" +
	"\busername\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x18\xff\x01R\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x10\n" +
	"\x03ssl\x18\x06 \x01(\bR\x03ssl\x12\x19\n" +
	"\bssl_mode\x18\a \x01(\tR\asslMode\x12$\n" +
	"\atimeout\x18\b \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xac\x02(\x00R\atimeout\x12'\n" +
	"\tmax_conns\x18\t \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xe8\a(\x00R\bmaxConns\x12/\n" +
	"\x0emax_idle_conns\x18\n" +
	" \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\fmaxIdleConns\x12\x18\n" +
	"\acharset\x18\v \x01(\tR\acharset\x12B\n" +
	"\x05extra\x18\f \x03(\v2,.api.metadata.v1.ConnectionConfig.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x03\n" +
	"\n" +
	"DataSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.api.metadata.v1.DataSourceTypeR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\x06config\x18\x05 \x01(\v2!.api.metadata.v1.ConnectionConfigR\x06config\x129\n" +
	"\x06status\x18\x06 \x01(\x0e2!.api.metadata.v1.DataSourceStatusR\x06status\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12<\n" +
	"\flast_test_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastTestAt\"\xfe\x01\n" +
	"\x17CreateDataSourceRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x04name\x12?\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.api.metadata.v1.DataSourceTypeB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x04type\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xf4\x03R\vdescription\x12C\n" +
	"\x06config\x18\x04 \x01(\v2!.api.metadata.v1.ConnectionConfigB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06config\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"\xca\x01\n" +
	"\x17UpdateDataSourceRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18dR\x04name\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xf4\x03R\vdescription\x129\n" +
	"\x06config\x18\x04 \x01(\v2!.api.metadata.v1.ConnectionConfigR\x06config\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"2\n" +
	"\x17DeleteDataSourceRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"/\n" +
	"\x14GetDataSourceRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"\xe1\x01\n" +
	"\x16ListDataSourcesRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x04page\x12&\n" +
	"\tpage_size\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\bpageSize\x123\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.api.metadata.v1.DataSourceTypeR\x04type\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2!.api.metadata.v1.DataSourceStatusR\x06status\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"\xa0\x01\n" +
	"\x17ListDataSourcesResponse\x12>\n" +
	"\fdata_sources\x18\x01 \x03(\v2\x1b.api.metadata.v1.DataSourceR\vdataSources\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"0\n" +
	"\x15TestConnectionRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"\xa7\x01\n" +
	"\x1fTestConnectionWithConfigRequest\x12?\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.api.metadata.v1.DataSourceTypeB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x04type\x12C\n" +
	"\x06config\x18\x02 \x01(\v2!.api.metadata.v1.ConnectionConfigB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06config\"\xc4\x01\n" +
	"\x14ConnectionTestResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\alatency\x18\x03 \x01(\x03R\alatency\x12\x1f\n" +
	"\vserver_info\x18\x04 \x01(\tR\n" +
	"serverInfo\x12#\n" +
	"\rdatabase_info\x18\x05 \x01(\tR\fdatabaseInfo\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"9\n" +
	"\x1eRefreshConnectionStatusRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"\x7f\n" +
	"\x1dUpdateDataSourceStatusRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12E\n" +
	"\x06status\x18\x02 \x01(\x0e2!.api.metadata.v1.DataSourceStatusB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x06status\"\x9d\x01\n" +
	"\x0fDataSourceStats\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12!\n" +
	"\factive_count\x18\x02 \x01(\x03R\vactiveCount\x12%\n" +
	"\x0einactive_count\x18\x03 \x01(\x03R\rinactiveCount\x12\x1f\n" +
	"\verror_count\x18\x04 \x01(\x03R\n" +
	"errorCount\"5\n" +
	"\x1aCanDeleteDataSourceRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"s\n" +
	"\x0fCanDeleteResult\x12\x1d\n" +
	"\n" +
	"can_delete\x18\x01 \x01(\bR\tcanDelete\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12)\n" +
	"\x10associated_tasks\x18\x03 \x01(\x05R\x0fassociatedTasks\"\x7f\n" +
	"\x18BatchUpdateStatusRequest\x12\x1c\n" +
	"\x03ids\x18\x01 \x03(\tB\n" +
	"\xfaB\a\x92\x01\x04\b\x01\x10dR\x03ids\x12E\n" +
	"\x06status\x18\x02 \x01(\x0e2!.api.metadata.v1.DataSourceStatusB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x06status\"v\n" +
	"\x14BatchOperationResult\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\x05R\asuccess\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"a\n" +
	"\x12BatchImportRequest\x12.\n" +
	"\x06format\x18\x01 \x01(\tB\x16\xfaB\x13r\x11R\x04jsonR\x04yamlR\x03csvR\x06format\x12\x1b\n" +
	"\x04data\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04data\"\xb3\x01\n" +
	"\x11BatchImportResult\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\x05R\asuccess\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12>\n" +
	"\fdata_sources\x18\x04 \x03(\v2\x1b.api.metadata.v1.DataSourceR\vdataSources\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\"V\n" +
	"\x12BatchExportRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12.\n" +
	"\x06format\x18\x02 \x01(\tB\x16\xfaB\x13r\x11R\x04jsonR\x04yamlR\x03csvR\x06format\"W\n" +
	"\x13BatchExportResponse\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count*\xb9\x03\n" +
	"\x0eDataSourceType\x12 \n" +
	"\x1cDATA_SOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DATA_SOURCE_TYPE_MYSQL\x10\x01\x12\x1f\n" +
	"\x1bDATA_SOURCE_TYPE_POSTGRESQL\x10\x02\x12\x1b\n" +
	"\x17DATA_SOURCE_TYPE_ORACLE\x10\x03\x12\x1e\n" +
	"\x1aDATA_SOURCE_TYPE_SQLSERVER\x10\x04\x12\x1c\n" +
	"\x18DATA_SOURCE_TYPE_MONGODB\x10\x05\x12\x1a\n" +
	"\x16DATA_SOURCE_TYPE_REDIS\x10\x06\x12\x1a\n" +
	"\x16DATA_SOURCE_TYPE_KAFKA\x10\a\x12\x1d\n" +
	"\x19DATA_SOURCE_TYPE_RABBITMQ\x10\b\x12\x1a\n" +
	"\x16DATA_SOURCE_TYPE_MINIO\x10\t\x12\x1f\n" +
	"\x1bDATA_SOURCE_TYPE_CLICKHOUSE\x10\n" +
	"\x12\x1a\n" +
	"\x16DATA_SOURCE_TYPE_DORIS\x10\v\x12\x19\n" +
	"\x15DATA_SOURCE_TYPE_HIVE\x10\f\x12\"\n" +
	"\x1eDATA_SOURCE_TYPE_ELASTICSEARCH\x10\r*\xb4\x01\n" +
	"\x10DataSourceStatus\x12\"\n" +
	"\x1eDATA_SOURCE_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DATA_SOURCE_STATUS_ACTIVE\x10\x01\x12\x1f\n" +
	"\x1bDATA_SOURCE_STATUS_INACTIVE\x10\x02\x12\x1c\n" +
	"\x18DATA_SOURCE_STATUS_ERROR\x10\x03\x12\x1e\n" +
	"\x1aDATA_SOURCE_STATUS_TESTING\x10\x042\xf7\x0e\n" +
	"\x11DataSourceService\x12y\n" +
	"\x10CreateDataSource\x12(.api.metadata.v1.CreateDataSourceRequest\x1a\x1b.api.metadata.v1.DataSource\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/datasources\x12~\n" +
	"\x10UpdateDataSource\x12(.api.metadata.v1.UpdateDataSourceRequest\x1a\x1b.api.metadata.v1.DataSource\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/v1/datasources/{id}\x12v\n" +
	"\x10DeleteDataSource\x12(.api.metadata.v1.DeleteDataSourceRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/datasources/{id}\x12u\n" +
	"\rGetDataSource\x12%.api.metadata.v1.GetDataSourceRequest\x1a\x1b.api.metadata.v1.DataSource\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/datasources/{id}\x12\x81\x01\n" +
	"\x0fListDataSources\x12'.api.metadata.v1.ListDataSourcesRequest\x1a(.api.metadata.v1.ListDataSourcesResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/datasources\x12\x86\x01\n" +
	"\x0eTestConnection\x12&.api.metadata.v1.TestConnectionRequest\x1a%.api.metadata.v1.ConnectionTestResult\"%\x82\xd3\xe4\x93\x02\x1f\"\x1d/api/v1/datasources/{id}/test\x12\x98\x01\n" +
	"\x18TestConnectionWithConfig\x120.api.metadata.v1.TestConnectionWithConfigRequest\x1a%.api.metadata.v1.ConnectionTestResult\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/datasources/test\x12\x8c\x01\n" +
	"\x17RefreshConnectionStatus\x12/.api.metadata.v1.RefreshConnectionStatusRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\"\" /api/v1/datasources/{id}/refresh\x12\x8c\x01\n" +
	"\x16UpdateDataSourceStatus\x12..api.metadata.v1.UpdateDataSourceStatusRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/api/v1/datasources/{id}/status\x12q\n" +
	"\x12GetDataSourceStats\x12\x16.google.protobuf.Empty\x1a .api.metadata.v1.DataSourceStats\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/datasources/stats\x12\x91\x01\n" +
	"\x13CanDeleteDataSource\x12+.api.metadata.v1.CanDeleteDataSourceRequest\x1a .api.metadata.v1.CanDeleteResult\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/datasources/{id}/can-delete\x12\x92\x01\n" +
	"\x11BatchUpdateStatus\x12).api.metadata.v1.BatchUpdateStatusRequest\x1a%.api.metadata.v1.BatchOperationResult\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/datasources/batch/status\x12\x88\x01\n" +
	"\x16BatchImportDataSources\x12#.api.metadata.v1.BatchImportRequest\x1a\".api.metadata.v1.BatchImportResult\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/datasources/import\x12\x8a\x01\n" +
	"\x16BatchExportDataSources\x12#.api.metadata.v1.BatchExportRequest\x1a$.api.metadata.v1.BatchExportResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/datasources/exportB Z\x1ego-metadata/api/metadata/v1;v1b\x06proto3"

var (
	file_datasource_proto_rawDescOnce sync.Once
	file_datasource_proto_rawDescData []byte
)

func file_datasource_proto_rawDescGZIP() []byte {
	file_datasource_proto_rawDescOnce.Do(func() {
		file_datasource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datasource_proto_rawDesc), len(file_datasource_proto_rawDesc)))
	})
	return file_datasource_proto_rawDescData
}

var file_datasource_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_datasource_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_datasource_proto_goTypes = []any{
	(DataSourceType)(0),                     // 0: api.metadata.v1.DataSourceType
	(DataSourceStatus)(0),                   // 1: api.metadata.v1.DataSourceStatus
	(*ConnectionConfig)(nil),                // 2: api.metadata.v1.ConnectionConfig
	(*DataSource)(nil),                      // 3: api.metadata.v1.DataSource
	(*CreateDataSourceRequest)(nil),         // 4: api.metadata.v1.CreateDataSourceRequest
	(*UpdateDataSourceRequest)(nil),         // 5: api.metadata.v1.UpdateDataSourceRequest
	(*DeleteDataSourceRequest)(nil),         // 6: api.metadata.v1.DeleteDataSourceRequest
	(*GetDataSourceRequest)(nil),            // 7: api.metadata.v1.GetDataSourceRequest
	(*ListDataSourcesRequest)(nil),          // 8: api.metadata.v1.ListDataSourcesRequest
	(*ListDataSourcesResponse)(nil),         // 9: api.metadata.v1.ListDataSourcesResponse
	(*TestConnectionRequest)(nil),           // 10: api.metadata.v1.TestConnectionRequest
	(*TestConnectionWithConfigRequest)(nil), // 11: api.metadata.v1.TestConnectionWithConfigRequest
	(*ConnectionTestResult)(nil),            // 12: api.metadata.v1.ConnectionTestResult
	(*RefreshConnectionStatusRequest)(nil),  // 13: api.metadata.v1.RefreshConnectionStatusRequest
	(*UpdateDataSourceStatusRequest)(nil),   // 14: api.metadata.v1.UpdateDataSourceStatusRequest
	(*DataSourceStats)(nil),                 // 15: api.metadata.v1.DataSourceStats
	(*CanDeleteDataSourceRequest)(nil),      // 16: api.metadata.v1.CanDeleteDataSourceRequest
	(*CanDeleteResult)(nil),                 // 17: api.metadata.v1.CanDeleteResult
	(*BatchUpdateStatusRequest)(nil),        // 18: api.metadata.v1.BatchUpdateStatusRequest
	(*BatchOperationResult)(nil),            // 19: api.metadata.v1.BatchOperationResult
	(*BatchImportRequest)(nil),              // 20: api.metadata.v1.BatchImportRequest
	(*BatchImportResult)(nil),               // 21: api.metadata.v1.BatchImportResult
	(*BatchExportRequest)(nil),              // 22: api.metadata.v1.BatchExportRequest
	(*BatchExportResponse)(nil),             // 23: api.metadata.v1.BatchExportResponse
	nil,                                     // 24: api.metadata.v1.ConnectionConfig.ExtraEntry
	(*timestamppb.Timestamp)(nil),           // 25: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 26: google.protobuf.Empty
}
var file_datasource_proto_depIdxs = []int32{
	24, // 0: api.metadata.v1.ConnectionConfig.extra:type_name -> api.metadata.v1.ConnectionConfig.ExtraEntry
	0,  // 1: api.metadata.v1.DataSource.type:type_name -> api.metadata.v1.DataSourceType
	2,  // 2: api.metadata.v1.DataSource.config:type_name -> api.metadata.v1.ConnectionConfig
	1,  // 3: api.metadata.v1.DataSource.status:type_name -> api.metadata.v1.DataSourceStatus
	25, // 4: api.metadata.v1.DataSource.created_at:type_name -> google.protobuf.Timestamp
	25, // 5: api.metadata.v1.DataSource.updated_at:type_name -> google.protobuf.Timestamp
	25, // 6: api.metadata.v1.DataSource.last_test_at:type_name -> google.protobuf.Timestamp
	0,  // 7: api.metadata.v1.CreateDataSourceRequest.type:type_name -> api.metadata.v1.DataSourceType
	2,  // 8: api.metadata.v1.CreateDataSourceRequest.config:type_name -> api.metadata.v1.ConnectionConfig
	2,  // 9: api.metadata.v1.UpdateDataSourceRequest.config:type_name -> api.metadata.v1.ConnectionConfig
	0,  // 10: api.metadata.v1.ListDataSourcesRequest.type:type_name -> api.metadata.v1.DataSourceType
	1,  // 11: api.metadata.v1.ListDataSourcesRequest.status:type_name -> api.metadata.v1.DataSourceStatus
	3,  // 12: api.metadata.v1.ListDataSourcesResponse.data_sources:type_name -> api.metadata.v1.DataSource
	0,  // 13: api.metadata.v1.TestConnectionWithConfigRequest.type:type_name -> api.metadata.v1.DataSourceType
	2,  // 14: api.metadata.v1.TestConnectionWithConfigRequest.config:type_name -> api.metadata.v1.ConnectionConfig
	1,  // 15: api.metadata.v1.UpdateDataSourceStatusRequest.status:type_name -> api.metadata.v1.DataSourceStatus
	1,  // 16: api.metadata.v1.BatchUpdateStatusRequest.status:type_name -> api.metadata.v1.DataSourceStatus
	3,  // 17: api.metadata.v1.BatchImportResult.data_sources:type_name -> api.metadata.v1.DataSource
	4,  // 18: api.metadata.v1.DataSourceService.CreateDataSource:input_type -> api.metadata.v1.CreateDataSourceRequest
	5,  // 19: api.metadata.v1.DataSourceService.UpdateDataSource:input_type -> api.metadata.v1.UpdateDataSourceRequest
	6,  // 20: api.metadata.v1.DataSourceService.DeleteDataSource:input_type -> api.metadata.v1.DeleteDataSourceRequest
	7,  // 21: api.metadata.v1.DataSourceService.GetDataSource:input_type -> api.metadata.v1.GetDataSourceRequest
	8,  // 22: api.metadata.v1.DataSourceService.ListDataSources:input_type -> api.metadata.v1.ListDataSourcesRequest
	10, // 23: api.metadata.v1.DataSourceService.TestConnection:input_type -> api.metadata.v1.TestConnectionRequest
	11, // 24: api.metadata.v1.DataSourceService.TestConnectionWithConfig:input_type -> api.metadata.v1.TestConnectionWithConfigRequest
	13, // 25: api.metadata.v1.DataSourceService.RefreshConnectionStatus:input_type -> api.metadata.v1.RefreshConnectionStatusRequest
	14, // 26: api.metadata.v1.DataSourceService.UpdateDataSourceStatus:input_type -> api.metadata.v1.UpdateDataSourceStatusRequest
	26, // 27: api.metadata.v1.DataSourceService.GetDataSourceStats:input_type -> google.protobuf.Empty
	16, // 28: api.metadata.v1.DataSourceService.CanDeleteDataSource:input_type -> api.metadata.v1.CanDeleteDataSourceRequest
	18, // 29: api.metadata.v1.DataSourceService.BatchUpdateStatus:input_type -> api.metadata.v1.BatchUpdateStatusRequest
	20, // 30: api.metadata.v1.DataSourceService.BatchImportDataSources:input_type -> api.metadata.v1.BatchImportRequest
	22, // 31: api.metadata.v1.DataSourceService.BatchExportDataSources:input_type -> api.metadata.v1.BatchExportRequest
	3,  // 32: api.metadata.v1.DataSourceService.CreateDataSource:output_type -> api.metadata.v1.DataSource
	3,  // 33: api.metadata.v1.DataSourceService.UpdateDataSource:output_type -> api.metadata.v1.DataSource
	26, // 34: api.metadata.v1.DataSourceService.DeleteDataSource:output_type -> google.protobuf.Empty
	3,  // 35: api.metadata.v1.DataSourceService.GetDataSource:output_type -> api.metadata.v1.DataSource
	9,  // 36: api.metadata.v1.DataSourceService.ListDataSources:output_type -> api.metadata.v1.ListDataSourcesResponse
	12, // 37: api.metadata.v1.DataSourceService.TestConnection:output_type -> api.metadata.v1.ConnectionTestResult
	12, // 38: api.metadata.v1.DataSourceService.TestConnectionWithConfig:output_type -> api.metadata.v1.ConnectionTestResult
	26, // 39: api.metadata.v1.DataSourceService.RefreshConnectionStatus:output_type -> google.protobuf.Empty
	26, // 40: api.metadata.v1.DataSourceService.UpdateDataSourceStatus:output_type -> google.protobuf.Empty
	15, // 41: api.metadata.v1.DataSourceService.GetDataSourceStats:output_type -> api.metadata.v1.DataSourceStats
	17, // 42: api.metadata.v1.DataSourceService.CanDeleteDataSource:output_type -> api.metadata.v1.CanDeleteResult
	19, // 43: api.metadata.v1.DataSourceService.BatchUpdateStatus:output_type -> api.metadata.v1.BatchOperationResult
	21, // 44: api.metadata.v1.DataSourceService.BatchImportDataSources:output_type -> api.metadata.v1.BatchImportResult
	23, // 45: api.metadata.v1.DataSourceService.BatchExportDataSources:output_type -> api.metadata.v1.BatchExportResponse
	32, // [32:46] is the sub-list for method output_type
	18, // [18:32] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_datasource_proto_init() }
func file_datasource_proto_init() {
	if File_datasource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datasource_proto_rawDesc), len(file_datasource_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datasource_proto_goTypes,
		DependencyIndexes: file_datasource_proto_depIdxs,
		EnumInfos:         file_datasource_proto_enumTypes,
		MessageInfos:      file_datasource_proto_msgTypes,
	}.Build()
	File_datasource_proto = out.File
	file_datasource_proto_goTypes = nil
	file_datasource_proto_depIdxs = nil
}
