// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: datasource.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDataSourceServiceBatchExportDataSources = "/api.metadata.v1.DataSourceService/BatchExportDataSources"
const OperationDataSourceServiceBatchImportDataSources = "/api.metadata.v1.DataSourceService/BatchImportDataSources"
const OperationDataSourceServiceBatchUpdateStatus = "/api.metadata.v1.DataSourceService/BatchUpdateStatus"
const OperationDataSourceServiceCanDeleteDataSource = "/api.metadata.v1.DataSourceService/CanDeleteDataSource"
const OperationDataSourceServiceCreateDataSource = "/api.metadata.v1.DataSourceService/CreateDataSource"
const OperationDataSourceServiceDeleteDataSource = "/api.metadata.v1.DataSourceService/DeleteDataSource"
const OperationDataSourceServiceGetDataSource = "/api.metadata.v1.DataSourceService/GetDataSource"
const OperationDataSourceServiceGetDataSourceStats = "/api.metadata.v1.DataSourceService/GetDataSourceStats"
const OperationDataSourceServiceListDataSources = "/api.metadata.v1.DataSourceService/ListDataSources"
const OperationDataSourceServiceRefreshConnectionStatus = "/api.metadata.v1.DataSourceService/RefreshConnectionStatus"
const OperationDataSourceServiceTestConnection = "/api.metadata.v1.DataSourceService/TestConnection"
const OperationDataSourceServiceTestConnectionWithConfig = "/api.metadata.v1.DataSourceService/TestConnectionWithConfig"
const OperationDataSourceServiceUpdateDataSource = "/api.metadata.v1.DataSourceService/UpdateDataSource"
const OperationDataSourceServiceUpdateDataSourceStatus = "/api.metadata.v1.DataSourceService/UpdateDataSourceStatus"

type DataSourceServiceHTTPServer interface {
	// BatchExportDataSources 批量导出
	BatchExportDataSources(context.Context, *BatchExportRequest) (*BatchExportResponse, error)
	// BatchImportDataSources 批量导入
	BatchImportDataSources(context.Context, *BatchImportRequest) (*BatchImportResult, error)
	// BatchUpdateStatus 批量更新状态
	BatchUpdateStatus(context.Context, *BatchUpdateStatusRequest) (*BatchOperationResult, error)
	// CanDeleteDataSource 检查是否可以删除
	CanDeleteDataSource(context.Context, *CanDeleteDataSourceRequest) (*CanDeleteResult, error)
	// CreateDataSource 创建数据源
	CreateDataSource(context.Context, *CreateDataSourceRequest) (*DataSource, error)
	// DeleteDataSource 删除数据源
	DeleteDataSource(context.Context, *DeleteDataSourceRequest) (*emptypb.Empty, error)
	// GetDataSource 获取数据源
	GetDataSource(context.Context, *GetDataSourceRequest) (*DataSource, error)
	// GetDataSourceStats 获取数据源统计
	GetDataSourceStats(context.Context, *emptypb.Empty) (*DataSourceStats, error)
	// ListDataSources 列出数据源
	ListDataSources(context.Context, *ListDataSourcesRequest) (*ListDataSourcesResponse, error)
	// RefreshConnectionStatus 刷新连接状态
	RefreshConnectionStatus(context.Context, *RefreshConnectionStatusRequest) (*emptypb.Empty, error)
	// TestConnection 测试连接
	TestConnection(context.Context, *TestConnectionRequest) (*ConnectionTestResult, error)
	// TestConnectionWithConfig 使用配置测试连接
	TestConnectionWithConfig(context.Context, *TestConnectionWithConfigRequest) (*ConnectionTestResult, error)
	// UpdateDataSource 更新数据源
	UpdateDataSource(context.Context, *UpdateDataSourceRequest) (*DataSource, error)
	// UpdateDataSourceStatus 更新数据源状态
	UpdateDataSourceStatus(context.Context, *UpdateDataSourceStatusRequest) (*emptypb.Empty, error)
}

func RegisterDataSourceServiceHTTPServer(s *http.Server, srv DataSourceServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/datasources", _DataSourceService_CreateDataSource0_HTTP_Handler(srv))
	r.PUT("/api/v1/datasources/{id}", _DataSourceService_UpdateDataSource0_HTTP_Handler(srv))
	r.DELETE("/api/v1/datasources/{id}", _DataSourceService_DeleteDataSource0_HTTP_Handler(srv))
	r.GET("/api/v1/datasources/{id}", _DataSourceService_GetDataSource0_HTTP_Handler(srv))
	r.GET("/api/v1/datasources", _DataSourceService_ListDataSources0_HTTP_Handler(srv))
	r.POST("/api/v1/datasources/{id}/test", _DataSourceService_TestConnection0_HTTP_Handler(srv))
	r.POST("/api/v1/datasources/test", _DataSourceService_TestConnectionWithConfig0_HTTP_Handler(srv))
	r.POST("/api/v1/datasources/{id}/refresh", _DataSourceService_RefreshConnectionStatus0_HTTP_Handler(srv))
	r.PUT("/api/v1/datasources/{id}/status", _DataSourceService_UpdateDataSourceStatus0_HTTP_Handler(srv))
	r.GET("/api/v1/datasources/stats", _DataSourceService_GetDataSourceStats0_HTTP_Handler(srv))
	r.GET("/api/v1/datasources/{id}/can-delete", _DataSourceService_CanDeleteDataSource0_HTTP_Handler(srv))
	r.POST("/api/v1/datasources/batch/status", _DataSourceService_BatchUpdateStatus0_HTTP_Handler(srv))
	r.POST("/api/v1/datasources/import", _DataSourceService_BatchImportDataSources0_HTTP_Handler(srv))
	r.POST("/api/v1/datasources/export", _DataSourceService_BatchExportDataSources0_HTTP_Handler(srv))
}

func _DataSourceService_CreateDataSource0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDataSourceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceCreateDataSource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDataSource(ctx, req.(*CreateDataSourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DataSource)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_UpdateDataSource0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDataSourceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceUpdateDataSource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDataSource(ctx, req.(*UpdateDataSourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DataSource)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_DeleteDataSource0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDataSourceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceDeleteDataSource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDataSource(ctx, req.(*DeleteDataSourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_GetDataSource0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDataSourceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceGetDataSource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDataSource(ctx, req.(*GetDataSourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DataSource)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_ListDataSources0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDataSourcesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceListDataSources)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDataSources(ctx, req.(*ListDataSourcesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDataSourcesResponse)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_TestConnection0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TestConnectionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceTestConnection)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TestConnection(ctx, req.(*TestConnectionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConnectionTestResult)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_TestConnectionWithConfig0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TestConnectionWithConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceTestConnectionWithConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TestConnectionWithConfig(ctx, req.(*TestConnectionWithConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConnectionTestResult)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_RefreshConnectionStatus0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RefreshConnectionStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceRefreshConnectionStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RefreshConnectionStatus(ctx, req.(*RefreshConnectionStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_UpdateDataSourceStatus0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDataSourceStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceUpdateDataSourceStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDataSourceStatus(ctx, req.(*UpdateDataSourceStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_GetDataSourceStats0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceGetDataSourceStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDataSourceStats(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DataSourceStats)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_CanDeleteDataSource0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CanDeleteDataSourceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceCanDeleteDataSource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CanDeleteDataSource(ctx, req.(*CanDeleteDataSourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CanDeleteResult)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_BatchUpdateStatus0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchUpdateStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceBatchUpdateStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchUpdateStatus(ctx, req.(*BatchUpdateStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchOperationResult)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_BatchImportDataSources0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchImportRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceBatchImportDataSources)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchImportDataSources(ctx, req.(*BatchImportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchImportResult)
		return ctx.Result(200, reply)
	}
}

func _DataSourceService_BatchExportDataSources0_HTTP_Handler(srv DataSourceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchExportRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataSourceServiceBatchExportDataSources)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchExportDataSources(ctx, req.(*BatchExportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchExportResponse)
		return ctx.Result(200, reply)
	}
}

type DataSourceServiceHTTPClient interface {
	// BatchExportDataSources 批量导出
	BatchExportDataSources(ctx context.Context, req *BatchExportRequest, opts ...http.CallOption) (rsp *BatchExportResponse, err error)
	// BatchImportDataSources 批量导入
	BatchImportDataSources(ctx context.Context, req *BatchImportRequest, opts ...http.CallOption) (rsp *BatchImportResult, err error)
	// BatchUpdateStatus 批量更新状态
	BatchUpdateStatus(ctx context.Context, req *BatchUpdateStatusRequest, opts ...http.CallOption) (rsp *BatchOperationResult, err error)
	// CanDeleteDataSource 检查是否可以删除
	CanDeleteDataSource(ctx context.Context, req *CanDeleteDataSourceRequest, opts ...http.CallOption) (rsp *CanDeleteResult, err error)
	// CreateDataSource 创建数据源
	CreateDataSource(ctx context.Context, req *CreateDataSourceRequest, opts ...http.CallOption) (rsp *DataSource, err error)
	// DeleteDataSource 删除数据源
	DeleteDataSource(ctx context.Context, req *DeleteDataSourceRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetDataSource 获取数据源
	GetDataSource(ctx context.Context, req *GetDataSourceRequest, opts ...http.CallOption) (rsp *DataSource, err error)
	// GetDataSourceStats 获取数据源统计
	GetDataSourceStats(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *DataSourceStats, err error)
	// ListDataSources 列出数据源
	ListDataSources(ctx context.Context, req *ListDataSourcesRequest, opts ...http.CallOption) (rsp *ListDataSourcesResponse, err error)
	// RefreshConnectionStatus 刷新连接状态
	RefreshConnectionStatus(ctx context.Context, req *RefreshConnectionStatusRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// TestConnection 测试连接
	TestConnection(ctx context.Context, req *TestConnectionRequest, opts ...http.CallOption) (rsp *ConnectionTestResult, err error)
	// TestConnectionWithConfig 使用配置测试连接
	TestConnectionWithConfig(ctx context.Context, req *TestConnectionWithConfigRequest, opts ...http.CallOption) (rsp *ConnectionTestResult, err error)
	// UpdateDataSource 更新数据源
	UpdateDataSource(ctx context.Context, req *UpdateDataSourceRequest, opts ...http.CallOption) (rsp *DataSource, err error)
	// UpdateDataSourceStatus 更新数据源状态
	UpdateDataSourceStatus(ctx context.Context, req *UpdateDataSourceStatusRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type DataSourceServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDataSourceServiceHTTPClient(client *http.Client) DataSourceServiceHTTPClient {
	return &DataSourceServiceHTTPClientImpl{client}
}

// BatchExportDataSources 批量导出
func (c *DataSourceServiceHTTPClientImpl) BatchExportDataSources(ctx context.Context, in *BatchExportRequest, opts ...http.CallOption) (*BatchExportResponse, error) {
	var out BatchExportResponse
	pattern := "/api/v1/datasources/export"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDataSourceServiceBatchExportDataSources))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BatchImportDataSources 批量导入
func (c *DataSourceServiceHTTPClientImpl) BatchImportDataSources(ctx context.Context, in *BatchImportRequest, opts ...http.CallOption) (*BatchImportResult, error) {
	var out BatchImportResult
	pattern := "/api/v1/datasources/import"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDataSourceServiceBatchImportDataSources))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BatchUpdateStatus 批量更新状态
func (c *DataSourceServiceHTTPClientImpl) BatchUpdateStatus(ctx context.Context, in *BatchUpdateStatusRequest, opts ...http.CallOption) (*BatchOperationResult, error) {
	var out BatchOperationResult
	pattern := "/api/v1/datasources/batch/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDataSourceServiceBatchUpdateStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CanDeleteDataSource 检查是否可以删除
func (c *DataSourceServiceHTTPClientImpl) CanDeleteDataSource(ctx context.Context, in *CanDeleteDataSourceRequest, opts ...http.CallOption) (*CanDeleteResult, error) {
	var out CanDeleteResult
	pattern := "/api/v1/datasources/{id}/can-delete"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDataSourceServiceCanDeleteDataSource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateDataSource 创建数据源
func (c *DataSourceServiceHTTPClientImpl) CreateDataSource(ctx context.Context, in *CreateDataSourceRequest, opts ...http.CallOption) (*DataSource, error) {
	var out DataSource
	pattern := "/api/v1/datasources"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDataSourceServiceCreateDataSource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteDataSource 删除数据源
func (c *DataSourceServiceHTTPClientImpl) DeleteDataSource(ctx context.Context, in *DeleteDataSourceRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/datasources/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDataSourceServiceDeleteDataSource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDataSource 获取数据源
func (c *DataSourceServiceHTTPClientImpl) GetDataSource(ctx context.Context, in *GetDataSourceRequest, opts ...http.CallOption) (*DataSource, error) {
	var out DataSource
	pattern := "/api/v1/datasources/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDataSourceServiceGetDataSource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDataSourceStats 获取数据源统计
func (c *DataSourceServiceHTTPClientImpl) GetDataSourceStats(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*DataSourceStats, error) {
	var out DataSourceStats
	pattern := "/api/v1/datasources/stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDataSourceServiceGetDataSourceStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListDataSources 列出数据源
func (c *DataSourceServiceHTTPClientImpl) ListDataSources(ctx context.Context, in *ListDataSourcesRequest, opts ...http.CallOption) (*ListDataSourcesResponse, error) {
	var out ListDataSourcesResponse
	pattern := "/api/v1/datasources"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDataSourceServiceListDataSources))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RefreshConnectionStatus 刷新连接状态
func (c *DataSourceServiceHTTPClientImpl) RefreshConnectionStatus(ctx context.Context, in *RefreshConnectionStatusRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/datasources/{id}/refresh"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDataSourceServiceRefreshConnectionStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TestConnection 测试连接
func (c *DataSourceServiceHTTPClientImpl) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...http.CallOption) (*ConnectionTestResult, error) {
	var out ConnectionTestResult
	pattern := "/api/v1/datasources/{id}/test"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDataSourceServiceTestConnection))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TestConnectionWithConfig 使用配置测试连接
func (c *DataSourceServiceHTTPClientImpl) TestConnectionWithConfig(ctx context.Context, in *TestConnectionWithConfigRequest, opts ...http.CallOption) (*ConnectionTestResult, error) {
	var out ConnectionTestResult
	pattern := "/api/v1/datasources/test"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDataSourceServiceTestConnectionWithConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateDataSource 更新数据源
func (c *DataSourceServiceHTTPClientImpl) UpdateDataSource(ctx context.Context, in *UpdateDataSourceRequest, opts ...http.CallOption) (*DataSource, error) {
	var out DataSource
	pattern := "/api/v1/datasources/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDataSourceServiceUpdateDataSource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateDataSourceStatus 更新数据源状态
func (c *DataSourceServiceHTTPClientImpl) UpdateDataSourceStatus(ctx context.Context, in *UpdateDataSourceStatusRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/datasources/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDataSourceServiceUpdateDataSourceStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
