// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: datasource.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataSourceService_CreateDataSource_FullMethodName         = "/api.metadata.v1.DataSourceService/CreateDataSource"
	DataSourceService_UpdateDataSource_FullMethodName         = "/api.metadata.v1.DataSourceService/UpdateDataSource"
	DataSourceService_DeleteDataSource_FullMethodName         = "/api.metadata.v1.DataSourceService/DeleteDataSource"
	DataSourceService_GetDataSource_FullMethodName            = "/api.metadata.v1.DataSourceService/GetDataSource"
	DataSourceService_ListDataSources_FullMethodName          = "/api.metadata.v1.DataSourceService/ListDataSources"
	DataSourceService_TestConnection_FullMethodName           = "/api.metadata.v1.DataSourceService/TestConnection"
	DataSourceService_TestConnectionWithConfig_FullMethodName = "/api.metadata.v1.DataSourceService/TestConnectionWithConfig"
	DataSourceService_RefreshConnectionStatus_FullMethodName  = "/api.metadata.v1.DataSourceService/RefreshConnectionStatus"
	DataSourceService_UpdateDataSourceStatus_FullMethodName   = "/api.metadata.v1.DataSourceService/UpdateDataSourceStatus"
	DataSourceService_GetDataSourceStats_FullMethodName       = "/api.metadata.v1.DataSourceService/GetDataSourceStats"
	DataSourceService_CanDeleteDataSource_FullMethodName      = "/api.metadata.v1.DataSourceService/CanDeleteDataSource"
	DataSourceService_BatchUpdateStatus_FullMethodName        = "/api.metadata.v1.DataSourceService/BatchUpdateStatus"
	DataSourceService_BatchImportDataSources_FullMethodName   = "/api.metadata.v1.DataSourceService/BatchImportDataSources"
	DataSourceService_BatchExportDataSources_FullMethodName   = "/api.metadata.v1.DataSourceService/BatchExportDataSources"
)

// DataSourceServiceClient is the client API for DataSourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataSourceService 数据源管理服务
type DataSourceServiceClient interface {
	// 创建数据源
	CreateDataSource(ctx context.Context, in *CreateDataSourceRequest, opts ...grpc.CallOption) (*DataSource, error)
	// 更新数据源
	UpdateDataSource(ctx context.Context, in *UpdateDataSourceRequest, opts ...grpc.CallOption) (*DataSource, error)
	// 删除数据源
	DeleteDataSource(ctx context.Context, in *DeleteDataSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取数据源
	GetDataSource(ctx context.Context, in *GetDataSourceRequest, opts ...grpc.CallOption) (*DataSource, error)
	// 列出数据源
	ListDataSources(ctx context.Context, in *ListDataSourcesRequest, opts ...grpc.CallOption) (*ListDataSourcesResponse, error)
	// 测试连接
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*ConnectionTestResult, error)
	// 使用配置测试连接
	TestConnectionWithConfig(ctx context.Context, in *TestConnectionWithConfigRequest, opts ...grpc.CallOption) (*ConnectionTestResult, error)
	// 刷新连接状态
	RefreshConnectionStatus(ctx context.Context, in *RefreshConnectionStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新数据源状态
	UpdateDataSourceStatus(ctx context.Context, in *UpdateDataSourceStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取数据源统计
	GetDataSourceStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DataSourceStats, error)
	// 检查是否可以删除
	CanDeleteDataSource(ctx context.Context, in *CanDeleteDataSourceRequest, opts ...grpc.CallOption) (*CanDeleteResult, error)
	// 批量更新状态
	BatchUpdateStatus(ctx context.Context, in *BatchUpdateStatusRequest, opts ...grpc.CallOption) (*BatchOperationResult, error)
	// 批量导入
	BatchImportDataSources(ctx context.Context, in *BatchImportRequest, opts ...grpc.CallOption) (*BatchImportResult, error)
	// 批量导出
	BatchExportDataSources(ctx context.Context, in *BatchExportRequest, opts ...grpc.CallOption) (*BatchExportResponse, error)
}

type dataSourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSourceServiceClient(cc grpc.ClientConnInterface) DataSourceServiceClient {
	return &dataSourceServiceClient{cc}
}

func (c *dataSourceServiceClient) CreateDataSource(ctx context.Context, in *CreateDataSourceRequest, opts ...grpc.CallOption) (*DataSource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSource)
	err := c.cc.Invoke(ctx, DataSourceService_CreateDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) UpdateDataSource(ctx context.Context, in *UpdateDataSourceRequest, opts ...grpc.CallOption) (*DataSource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSource)
	err := c.cc.Invoke(ctx, DataSourceService_UpdateDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) DeleteDataSource(ctx context.Context, in *DeleteDataSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DataSourceService_DeleteDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) GetDataSource(ctx context.Context, in *GetDataSourceRequest, opts ...grpc.CallOption) (*DataSource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSource)
	err := c.cc.Invoke(ctx, DataSourceService_GetDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) ListDataSources(ctx context.Context, in *ListDataSourcesRequest, opts ...grpc.CallOption) (*ListDataSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDataSourcesResponse)
	err := c.cc.Invoke(ctx, DataSourceService_ListDataSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*ConnectionTestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionTestResult)
	err := c.cc.Invoke(ctx, DataSourceService_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) TestConnectionWithConfig(ctx context.Context, in *TestConnectionWithConfigRequest, opts ...grpc.CallOption) (*ConnectionTestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionTestResult)
	err := c.cc.Invoke(ctx, DataSourceService_TestConnectionWithConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) RefreshConnectionStatus(ctx context.Context, in *RefreshConnectionStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DataSourceService_RefreshConnectionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) UpdateDataSourceStatus(ctx context.Context, in *UpdateDataSourceStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DataSourceService_UpdateDataSourceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) GetDataSourceStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DataSourceStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSourceStats)
	err := c.cc.Invoke(ctx, DataSourceService_GetDataSourceStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) CanDeleteDataSource(ctx context.Context, in *CanDeleteDataSourceRequest, opts ...grpc.CallOption) (*CanDeleteResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanDeleteResult)
	err := c.cc.Invoke(ctx, DataSourceService_CanDeleteDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) BatchUpdateStatus(ctx context.Context, in *BatchUpdateStatusRequest, opts ...grpc.CallOption) (*BatchOperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchOperationResult)
	err := c.cc.Invoke(ctx, DataSourceService_BatchUpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) BatchImportDataSources(ctx context.Context, in *BatchImportRequest, opts ...grpc.CallOption) (*BatchImportResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchImportResult)
	err := c.cc.Invoke(ctx, DataSourceService_BatchImportDataSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceServiceClient) BatchExportDataSources(ctx context.Context, in *BatchExportRequest, opts ...grpc.CallOption) (*BatchExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchExportResponse)
	err := c.cc.Invoke(ctx, DataSourceService_BatchExportDataSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataSourceServiceServer is the server API for DataSourceService service.
// All implementations must embed UnimplementedDataSourceServiceServer
// for forward compatibility.
//
// DataSourceService 数据源管理服务
type DataSourceServiceServer interface {
	// 创建数据源
	CreateDataSource(context.Context, *CreateDataSourceRequest) (*DataSource, error)
	// 更新数据源
	UpdateDataSource(context.Context, *UpdateDataSourceRequest) (*DataSource, error)
	// 删除数据源
	DeleteDataSource(context.Context, *DeleteDataSourceRequest) (*emptypb.Empty, error)
	// 获取数据源
	GetDataSource(context.Context, *GetDataSourceRequest) (*DataSource, error)
	// 列出数据源
	ListDataSources(context.Context, *ListDataSourcesRequest) (*ListDataSourcesResponse, error)
	// 测试连接
	TestConnection(context.Context, *TestConnectionRequest) (*ConnectionTestResult, error)
	// 使用配置测试连接
	TestConnectionWithConfig(context.Context, *TestConnectionWithConfigRequest) (*ConnectionTestResult, error)
	// 刷新连接状态
	RefreshConnectionStatus(context.Context, *RefreshConnectionStatusRequest) (*emptypb.Empty, error)
	// 更新数据源状态
	UpdateDataSourceStatus(context.Context, *UpdateDataSourceStatusRequest) (*emptypb.Empty, error)
	// 获取数据源统计
	GetDataSourceStats(context.Context, *emptypb.Empty) (*DataSourceStats, error)
	// 检查是否可以删除
	CanDeleteDataSource(context.Context, *CanDeleteDataSourceRequest) (*CanDeleteResult, error)
	// 批量更新状态
	BatchUpdateStatus(context.Context, *BatchUpdateStatusRequest) (*BatchOperationResult, error)
	// 批量导入
	BatchImportDataSources(context.Context, *BatchImportRequest) (*BatchImportResult, error)
	// 批量导出
	BatchExportDataSources(context.Context, *BatchExportRequest) (*BatchExportResponse, error)
	mustEmbedUnimplementedDataSourceServiceServer()
}

// UnimplementedDataSourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataSourceServiceServer struct{}

func (UnimplementedDataSourceServiceServer) CreateDataSource(context.Context, *CreateDataSourceRequest) (*DataSource, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDataSource not implemented")
}
func (UnimplementedDataSourceServiceServer) UpdateDataSource(context.Context, *UpdateDataSourceRequest) (*DataSource, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDataSource not implemented")
}
func (UnimplementedDataSourceServiceServer) DeleteDataSource(context.Context, *DeleteDataSourceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDataSource not implemented")
}
func (UnimplementedDataSourceServiceServer) GetDataSource(context.Context, *GetDataSourceRequest) (*DataSource, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDataSource not implemented")
}
func (UnimplementedDataSourceServiceServer) ListDataSources(context.Context, *ListDataSourcesRequest) (*ListDataSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDataSources not implemented")
}
func (UnimplementedDataSourceServiceServer) TestConnection(context.Context, *TestConnectionRequest) (*ConnectionTestResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedDataSourceServiceServer) TestConnectionWithConfig(context.Context, *TestConnectionWithConfigRequest) (*ConnectionTestResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConnectionWithConfig not implemented")
}
func (UnimplementedDataSourceServiceServer) RefreshConnectionStatus(context.Context, *RefreshConnectionStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshConnectionStatus not implemented")
}
func (UnimplementedDataSourceServiceServer) UpdateDataSourceStatus(context.Context, *UpdateDataSourceStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDataSourceStatus not implemented")
}
func (UnimplementedDataSourceServiceServer) GetDataSourceStats(context.Context, *emptypb.Empty) (*DataSourceStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDataSourceStats not implemented")
}
func (UnimplementedDataSourceServiceServer) CanDeleteDataSource(context.Context, *CanDeleteDataSourceRequest) (*CanDeleteResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CanDeleteDataSource not implemented")
}
func (UnimplementedDataSourceServiceServer) BatchUpdateStatus(context.Context, *BatchUpdateStatusRequest) (*BatchOperationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUpdateStatus not implemented")
}
func (UnimplementedDataSourceServiceServer) BatchImportDataSources(context.Context, *BatchImportRequest) (*BatchImportResult, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchImportDataSources not implemented")
}
func (UnimplementedDataSourceServiceServer) BatchExportDataSources(context.Context, *BatchExportRequest) (*BatchExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchExportDataSources not implemented")
}
func (UnimplementedDataSourceServiceServer) mustEmbedUnimplementedDataSourceServiceServer() {}
func (UnimplementedDataSourceServiceServer) testEmbeddedByValue()                           {}

// UnsafeDataSourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataSourceServiceServer will
// result in compilation errors.
type UnsafeDataSourceServiceServer interface {
	mustEmbedUnimplementedDataSourceServiceServer()
}

func RegisterDataSourceServiceServer(s grpc.ServiceRegistrar, srv DataSourceServiceServer) {
	// If the following call panics, it indicates UnimplementedDataSourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataSourceService_ServiceDesc, srv)
}

func _DataSourceService_CreateDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).CreateDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_CreateDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).CreateDataSource(ctx, req.(*CreateDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_UpdateDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).UpdateDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_UpdateDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).UpdateDataSource(ctx, req.(*UpdateDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_DeleteDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).DeleteDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_DeleteDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).DeleteDataSource(ctx, req.(*DeleteDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_GetDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).GetDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_GetDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).GetDataSource(ctx, req.(*GetDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_ListDataSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).ListDataSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_ListDataSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).ListDataSources(ctx, req.(*ListDataSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_TestConnectionWithConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionWithConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).TestConnectionWithConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_TestConnectionWithConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).TestConnectionWithConfig(ctx, req.(*TestConnectionWithConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_RefreshConnectionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshConnectionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).RefreshConnectionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_RefreshConnectionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).RefreshConnectionStatus(ctx, req.(*RefreshConnectionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_UpdateDataSourceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataSourceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).UpdateDataSourceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_UpdateDataSourceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).UpdateDataSourceStatus(ctx, req.(*UpdateDataSourceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_GetDataSourceStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).GetDataSourceStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_GetDataSourceStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).GetDataSourceStats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_CanDeleteDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanDeleteDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).CanDeleteDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_CanDeleteDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).CanDeleteDataSource(ctx, req.(*CanDeleteDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_BatchUpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).BatchUpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_BatchUpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).BatchUpdateStatus(ctx, req.(*BatchUpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_BatchImportDataSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).BatchImportDataSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_BatchImportDataSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).BatchImportDataSources(ctx, req.(*BatchImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourceService_BatchExportDataSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourceServiceServer).BatchExportDataSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourceService_BatchExportDataSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourceServiceServer).BatchExportDataSources(ctx, req.(*BatchExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataSourceService_ServiceDesc is the grpc.ServiceDesc for DataSourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataSourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.metadata.v1.DataSourceService",
	HandlerType: (*DataSourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDataSource",
			Handler:    _DataSourceService_CreateDataSource_Handler,
		},
		{
			MethodName: "UpdateDataSource",
			Handler:    _DataSourceService_UpdateDataSource_Handler,
		},
		{
			MethodName: "DeleteDataSource",
			Handler:    _DataSourceService_DeleteDataSource_Handler,
		},
		{
			MethodName: "GetDataSource",
			Handler:    _DataSourceService_GetDataSource_Handler,
		},
		{
			MethodName: "ListDataSources",
			Handler:    _DataSourceService_ListDataSources_Handler,
		},
		{
			MethodName: "TestConnection",
			Handler:    _DataSourceService_TestConnection_Handler,
		},
		{
			MethodName: "TestConnectionWithConfig",
			Handler:    _DataSourceService_TestConnectionWithConfig_Handler,
		},
		{
			MethodName: "RefreshConnectionStatus",
			Handler:    _DataSourceService_RefreshConnectionStatus_Handler,
		},
		{
			MethodName: "UpdateDataSourceStatus",
			Handler:    _DataSourceService_UpdateDataSourceStatus_Handler,
		},
		{
			MethodName: "GetDataSourceStats",
			Handler:    _DataSourceService_GetDataSourceStats_Handler,
		},
		{
			MethodName: "CanDeleteDataSource",
			Handler:    _DataSourceService_CanDeleteDataSource_Handler,
		},
		{
			MethodName: "BatchUpdateStatus",
			Handler:    _DataSourceService_BatchUpdateStatus_Handler,
		},
		{
			MethodName: "BatchImportDataSources",
			Handler:    _DataSourceService_BatchImportDataSources_Handler,
		},
		{
			MethodName: "BatchExportDataSources",
			Handler:    _DataSourceService_BatchExportDataSources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datasource.proto",
}
