// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: task.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTaskServiceBatchDeleteTasks = "/api.metadata.v1.TaskService/BatchDeleteTasks"
const OperationTaskServiceBatchStartTasks = "/api.metadata.v1.TaskService/BatchStartTasks"
const OperationTaskServiceBatchStopTasks = "/api.metadata.v1.TaskService/BatchStopTasks"
const OperationTaskServiceCancelExecution = "/api.metadata.v1.TaskService/CancelExecution"
const OperationTaskServiceCreateTask = "/api.metadata.v1.TaskService/CreateTask"
const OperationTaskServiceDeleteTask = "/api.metadata.v1.TaskService/DeleteTask"
const OperationTaskServiceExecuteTaskNow = "/api.metadata.v1.TaskService/ExecuteTaskNow"
const OperationTaskServiceGetTask = "/api.metadata.v1.TaskService/GetTask"
const OperationTaskServiceGetTaskExecution = "/api.metadata.v1.TaskService/GetTaskExecution"
const OperationTaskServiceGetTaskStatus = "/api.metadata.v1.TaskService/GetTaskStatus"
const OperationTaskServiceListTaskExecutions = "/api.metadata.v1.TaskService/ListTaskExecutions"
const OperationTaskServiceListTasks = "/api.metadata.v1.TaskService/ListTasks"
const OperationTaskServicePauseTask = "/api.metadata.v1.TaskService/PauseTask"
const OperationTaskServiceResumeTask = "/api.metadata.v1.TaskService/ResumeTask"
const OperationTaskServiceRetryExecution = "/api.metadata.v1.TaskService/RetryExecution"
const OperationTaskServiceStartTask = "/api.metadata.v1.TaskService/StartTask"
const OperationTaskServiceStopTask = "/api.metadata.v1.TaskService/StopTask"
const OperationTaskServiceUpdateTask = "/api.metadata.v1.TaskService/UpdateTask"

type TaskServiceHTTPServer interface {
	// BatchDeleteTasks 批量删除任务
	BatchDeleteTasks(context.Context, *BatchTaskOperationRequest) (*BatchTaskOperationResult, error)
	// BatchStartTasks 批量启动任务
	BatchStartTasks(context.Context, *BatchTaskOperationRequest) (*BatchTaskOperationResult, error)
	// BatchStopTasks 批量停止任务
	BatchStopTasks(context.Context, *BatchTaskOperationRequest) (*BatchTaskOperationResult, error)
	// CancelExecution 取消执行
	CancelExecution(context.Context, *CancelExecutionRequest) (*TaskExecution, error)
	// CreateTask 创建任务
	CreateTask(context.Context, *CreateTaskRequest) (*CollectionTask, error)
	// DeleteTask 删除任务
	DeleteTask(context.Context, *DeleteTaskRequest) (*emptypb.Empty, error)
	// ExecuteTaskNow 立即执行任务
	ExecuteTaskNow(context.Context, *ExecuteTaskNowRequest) (*TaskExecution, error)
	// GetTask 获取任务
	GetTask(context.Context, *GetTaskRequest) (*CollectionTask, error)
	// GetTaskExecution 获取执行记录
	GetTaskExecution(context.Context, *GetTaskExecutionRequest) (*TaskExecution, error)
	// GetTaskStatus 获取任务状态
	GetTaskStatus(context.Context, *GetTaskStatusRequest) (*TaskStatusInfo, error)
	// ListTaskExecutions 列出执行记录
	ListTaskExecutions(context.Context, *ListTaskExecutionsRequest) (*ListTaskExecutionsResponse, error)
	// ListTasks 列出任务
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// PauseTask 暂停任务
	PauseTask(context.Context, *PauseTaskRequest) (*emptypb.Empty, error)
	// ResumeTask 恢复任务
	ResumeTask(context.Context, *ResumeTaskRequest) (*emptypb.Empty, error)
	// RetryExecution 重试执行
	RetryExecution(context.Context, *RetryExecutionRequest) (*TaskExecution, error)
	// StartTask 启动任务
	StartTask(context.Context, *StartTaskRequest) (*emptypb.Empty, error)
	// StopTask 停止任务
	StopTask(context.Context, *StopTaskRequest) (*emptypb.Empty, error)
	// UpdateTask 更新任务
	UpdateTask(context.Context, *UpdateTaskRequest) (*CollectionTask, error)
}

func RegisterTaskServiceHTTPServer(s *http.Server, srv TaskServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/tasks", _TaskService_CreateTask0_HTTP_Handler(srv))
	r.PUT("/api/v1/tasks/{id}", _TaskService_UpdateTask0_HTTP_Handler(srv))
	r.DELETE("/api/v1/tasks/{id}", _TaskService_DeleteTask0_HTTP_Handler(srv))
	r.GET("/api/v1/tasks/{id}", _TaskService_GetTask0_HTTP_Handler(srv))
	r.GET("/api/v1/tasks", _TaskService_ListTasks0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/{id}/start", _TaskService_StartTask0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/{id}/stop", _TaskService_StopTask0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/{id}/pause", _TaskService_PauseTask0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/{id}/resume", _TaskService_ResumeTask0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/{id}/execute", _TaskService_ExecuteTaskNow0_HTTP_Handler(srv))
	r.GET("/api/v1/tasks/{id}/status", _TaskService_GetTaskStatus0_HTTP_Handler(srv))
	r.GET("/api/v1/executions/{id}", _TaskService_GetTaskExecution0_HTTP_Handler(srv))
	r.GET("/api/v1/tasks/{task_id}/executions", _TaskService_ListTaskExecutions0_HTTP_Handler(srv))
	r.POST("/api/v1/executions/{id}/cancel", _TaskService_CancelExecution0_HTTP_Handler(srv))
	r.POST("/api/v1/executions/{id}/retry", _TaskService_RetryExecution0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/batch/start", _TaskService_BatchStartTasks0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/batch/stop", _TaskService_BatchStopTasks0_HTTP_Handler(srv))
	r.POST("/api/v1/tasks/batch/delete", _TaskService_BatchDeleteTasks0_HTTP_Handler(srv))
}

func _TaskService_CreateTask0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceCreateTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTask(ctx, req.(*CreateTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CollectionTask)
		return ctx.Result(200, reply)
	}
}

func _TaskService_UpdateTask0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceUpdateTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTask(ctx, req.(*UpdateTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CollectionTask)
		return ctx.Result(200, reply)
	}
}

func _TaskService_DeleteTask0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceDeleteTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTask(ctx, req.(*DeleteTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TaskService_GetTask0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceGetTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTask(ctx, req.(*GetTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CollectionTask)
		return ctx.Result(200, reply)
	}
}

func _TaskService_ListTasks0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceListTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTasks(ctx, req.(*ListTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTasksResponse)
		return ctx.Result(200, reply)
	}
}

func _TaskService_StartTask0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceStartTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartTask(ctx, req.(*StartTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TaskService_StopTask0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StopTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceStopTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StopTask(ctx, req.(*StopTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TaskService_PauseTask0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PauseTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServicePauseTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PauseTask(ctx, req.(*PauseTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TaskService_ResumeTask0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResumeTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceResumeTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResumeTask(ctx, req.(*ResumeTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TaskService_ExecuteTaskNow0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExecuteTaskNowRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceExecuteTaskNow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExecuteTaskNow(ctx, req.(*ExecuteTaskNowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskExecution)
		return ctx.Result(200, reply)
	}
}

func _TaskService_GetTaskStatus0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTaskStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceGetTaskStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTaskStatus(ctx, req.(*GetTaskStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskStatusInfo)
		return ctx.Result(200, reply)
	}
}

func _TaskService_GetTaskExecution0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTaskExecutionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceGetTaskExecution)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTaskExecution(ctx, req.(*GetTaskExecutionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskExecution)
		return ctx.Result(200, reply)
	}
}

func _TaskService_ListTaskExecutions0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTaskExecutionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceListTaskExecutions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTaskExecutions(ctx, req.(*ListTaskExecutionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTaskExecutionsResponse)
		return ctx.Result(200, reply)
	}
}

func _TaskService_CancelExecution0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelExecutionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceCancelExecution)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelExecution(ctx, req.(*CancelExecutionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskExecution)
		return ctx.Result(200, reply)
	}
}

func _TaskService_RetryExecution0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RetryExecutionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceRetryExecution)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RetryExecution(ctx, req.(*RetryExecutionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskExecution)
		return ctx.Result(200, reply)
	}
}

func _TaskService_BatchStartTasks0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchTaskOperationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceBatchStartTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchStartTasks(ctx, req.(*BatchTaskOperationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchTaskOperationResult)
		return ctx.Result(200, reply)
	}
}

func _TaskService_BatchStopTasks0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchTaskOperationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceBatchStopTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchStopTasks(ctx, req.(*BatchTaskOperationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchTaskOperationResult)
		return ctx.Result(200, reply)
	}
}

func _TaskService_BatchDeleteTasks0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchTaskOperationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceBatchDeleteTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchDeleteTasks(ctx, req.(*BatchTaskOperationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchTaskOperationResult)
		return ctx.Result(200, reply)
	}
}

type TaskServiceHTTPClient interface {
	// BatchDeleteTasks 批量删除任务
	BatchDeleteTasks(ctx context.Context, req *BatchTaskOperationRequest, opts ...http.CallOption) (rsp *BatchTaskOperationResult, err error)
	// BatchStartTasks 批量启动任务
	BatchStartTasks(ctx context.Context, req *BatchTaskOperationRequest, opts ...http.CallOption) (rsp *BatchTaskOperationResult, err error)
	// BatchStopTasks 批量停止任务
	BatchStopTasks(ctx context.Context, req *BatchTaskOperationRequest, opts ...http.CallOption) (rsp *BatchTaskOperationResult, err error)
	// CancelExecution 取消执行
	CancelExecution(ctx context.Context, req *CancelExecutionRequest, opts ...http.CallOption) (rsp *TaskExecution, err error)
	// CreateTask 创建任务
	CreateTask(ctx context.Context, req *CreateTaskRequest, opts ...http.CallOption) (rsp *CollectionTask, err error)
	// DeleteTask 删除任务
	DeleteTask(ctx context.Context, req *DeleteTaskRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// ExecuteTaskNow 立即执行任务
	ExecuteTaskNow(ctx context.Context, req *ExecuteTaskNowRequest, opts ...http.CallOption) (rsp *TaskExecution, err error)
	// GetTask 获取任务
	GetTask(ctx context.Context, req *GetTaskRequest, opts ...http.CallOption) (rsp *CollectionTask, err error)
	// GetTaskExecution 获取执行记录
	GetTaskExecution(ctx context.Context, req *GetTaskExecutionRequest, opts ...http.CallOption) (rsp *TaskExecution, err error)
	// GetTaskStatus 获取任务状态
	GetTaskStatus(ctx context.Context, req *GetTaskStatusRequest, opts ...http.CallOption) (rsp *TaskStatusInfo, err error)
	// ListTaskExecutions 列出执行记录
	ListTaskExecutions(ctx context.Context, req *ListTaskExecutionsRequest, opts ...http.CallOption) (rsp *ListTaskExecutionsResponse, err error)
	// ListTasks 列出任务
	ListTasks(ctx context.Context, req *ListTasksRequest, opts ...http.CallOption) (rsp *ListTasksResponse, err error)
	// PauseTask 暂停任务
	PauseTask(ctx context.Context, req *PauseTaskRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// ResumeTask 恢复任务
	ResumeTask(ctx context.Context, req *ResumeTaskRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// RetryExecution 重试执行
	RetryExecution(ctx context.Context, req *RetryExecutionRequest, opts ...http.CallOption) (rsp *TaskExecution, err error)
	// StartTask 启动任务
	StartTask(ctx context.Context, req *StartTaskRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// StopTask 停止任务
	StopTask(ctx context.Context, req *StopTaskRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// UpdateTask 更新任务
	UpdateTask(ctx context.Context, req *UpdateTaskRequest, opts ...http.CallOption) (rsp *CollectionTask, err error)
}

type TaskServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTaskServiceHTTPClient(client *http.Client) TaskServiceHTTPClient {
	return &TaskServiceHTTPClientImpl{client}
}

// BatchDeleteTasks 批量删除任务
func (c *TaskServiceHTTPClientImpl) BatchDeleteTasks(ctx context.Context, in *BatchTaskOperationRequest, opts ...http.CallOption) (*BatchTaskOperationResult, error) {
	var out BatchTaskOperationResult
	pattern := "/api/v1/tasks/batch/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTaskServiceBatchDeleteTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BatchStartTasks 批量启动任务
func (c *TaskServiceHTTPClientImpl) BatchStartTasks(ctx context.Context, in *BatchTaskOperationRequest, opts ...http.CallOption) (*BatchTaskOperationResult, error) {
	var out BatchTaskOperationResult
	pattern := "/api/v1/tasks/batch/start"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTaskServiceBatchStartTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BatchStopTasks 批量停止任务
func (c *TaskServiceHTTPClientImpl) BatchStopTasks(ctx context.Context, in *BatchTaskOperationRequest, opts ...http.CallOption) (*BatchTaskOperationResult, error) {
	var out BatchTaskOperationResult
	pattern := "/api/v1/tasks/batch/stop"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTaskServiceBatchStopTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CancelExecution 取消执行
func (c *TaskServiceHTTPClientImpl) CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...http.CallOption) (*TaskExecution, error) {
	var out TaskExecution
	pattern := "/api/v1/executions/{id}/cancel"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceCancelExecution))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateTask 创建任务
func (c *TaskServiceHTTPClientImpl) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...http.CallOption) (*CollectionTask, error) {
	var out CollectionTask
	pattern := "/api/v1/tasks"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTaskServiceCreateTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteTask 删除任务
func (c *TaskServiceHTTPClientImpl) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/tasks/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceDeleteTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ExecuteTaskNow 立即执行任务
func (c *TaskServiceHTTPClientImpl) ExecuteTaskNow(ctx context.Context, in *ExecuteTaskNowRequest, opts ...http.CallOption) (*TaskExecution, error) {
	var out TaskExecution
	pattern := "/api/v1/tasks/{id}/execute"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceExecuteTaskNow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTask 获取任务
func (c *TaskServiceHTTPClientImpl) GetTask(ctx context.Context, in *GetTaskRequest, opts ...http.CallOption) (*CollectionTask, error) {
	var out CollectionTask
	pattern := "/api/v1/tasks/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceGetTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTaskExecution 获取执行记录
func (c *TaskServiceHTTPClientImpl) GetTaskExecution(ctx context.Context, in *GetTaskExecutionRequest, opts ...http.CallOption) (*TaskExecution, error) {
	var out TaskExecution
	pattern := "/api/v1/executions/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceGetTaskExecution))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTaskStatus 获取任务状态
func (c *TaskServiceHTTPClientImpl) GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...http.CallOption) (*TaskStatusInfo, error) {
	var out TaskStatusInfo
	pattern := "/api/v1/tasks/{id}/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceGetTaskStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTaskExecutions 列出执行记录
func (c *TaskServiceHTTPClientImpl) ListTaskExecutions(ctx context.Context, in *ListTaskExecutionsRequest, opts ...http.CallOption) (*ListTaskExecutionsResponse, error) {
	var out ListTaskExecutionsResponse
	pattern := "/api/v1/tasks/{task_id}/executions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceListTaskExecutions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTasks 列出任务
func (c *TaskServiceHTTPClientImpl) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...http.CallOption) (*ListTasksResponse, error) {
	var out ListTasksResponse
	pattern := "/api/v1/tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceListTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PauseTask 暂停任务
func (c *TaskServiceHTTPClientImpl) PauseTask(ctx context.Context, in *PauseTaskRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/tasks/{id}/pause"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServicePauseTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResumeTask 恢复任务
func (c *TaskServiceHTTPClientImpl) ResumeTask(ctx context.Context, in *ResumeTaskRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/tasks/{id}/resume"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceResumeTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RetryExecution 重试执行
func (c *TaskServiceHTTPClientImpl) RetryExecution(ctx context.Context, in *RetryExecutionRequest, opts ...http.CallOption) (*TaskExecution, error) {
	var out TaskExecution
	pattern := "/api/v1/executions/{id}/retry"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceRetryExecution))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StartTask 启动任务
func (c *TaskServiceHTTPClientImpl) StartTask(ctx context.Context, in *StartTaskRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/tasks/{id}/start"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceStartTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StopTask 停止任务
func (c *TaskServiceHTTPClientImpl) StopTask(ctx context.Context, in *StopTaskRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/tasks/{id}/stop"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceStopTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTask 更新任务
func (c *TaskServiceHTTPClientImpl) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...http.CallOption) (*CollectionTask, error) {
	var out CollectionTask
	pattern := "/api/v1/tasks/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTaskServiceUpdateTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
