// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: task.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务类型
type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED            TaskType = 0
	TaskType_TASK_TYPE_FULL_COLLECTION        TaskType = 1
	TaskType_TASK_TYPE_INCREMENTAL_COLLECTION TaskType = 2
	TaskType_TASK_TYPE_SCHEMA_ONLY            TaskType = 3
	TaskType_TASK_TYPE_DATA_PROFILE           TaskType = 4
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_FULL_COLLECTION",
		2: "TASK_TYPE_INCREMENTAL_COLLECTION",
		3: "TASK_TYPE_SCHEMA_ONLY",
		4: "TASK_TYPE_DATA_PROFILE",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED":            0,
		"TASK_TYPE_FULL_COLLECTION":        1,
		"TASK_TYPE_INCREMENTAL_COLLECTION": 2,
		"TASK_TYPE_SCHEMA_ONLY":            3,
		"TASK_TYPE_DATA_PROFILE":           4,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

// 任务状态
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_ACTIVE      TaskStatus = 1
	TaskStatus_TASK_STATUS_INACTIVE    TaskStatus = 2
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 3
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 4
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 5
	TaskStatus_TASK_STATUS_PAUSED      TaskStatus = 6
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_ACTIVE",
		2: "TASK_STATUS_INACTIVE",
		3: "TASK_STATUS_RUNNING",
		4: "TASK_STATUS_COMPLETED",
		5: "TASK_STATUS_FAILED",
		6: "TASK_STATUS_PAUSED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_ACTIVE":      1,
		"TASK_STATUS_INACTIVE":    2,
		"TASK_STATUS_RUNNING":     3,
		"TASK_STATUS_COMPLETED":   4,
		"TASK_STATUS_FAILED":      5,
		"TASK_STATUS_PAUSED":      6,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

// 调度器类型
type SchedulerType int32

const (
	SchedulerType_SCHEDULER_TYPE_UNSPECIFIED      SchedulerType = 0
	SchedulerType_SCHEDULER_TYPE_DOLPHINSCHEDULER SchedulerType = 1
	SchedulerType_SCHEDULER_TYPE_BUILTIN          SchedulerType = 2
)

// Enum value maps for SchedulerType.
var (
	SchedulerType_name = map[int32]string{
		0: "SCHEDULER_TYPE_UNSPECIFIED",
		1: "SCHEDULER_TYPE_DOLPHINSCHEDULER",
		2: "SCHEDULER_TYPE_BUILTIN",
	}
	SchedulerType_value = map[string]int32{
		"SCHEDULER_TYPE_UNSPECIFIED":      0,
		"SCHEDULER_TYPE_DOLPHINSCHEDULER": 1,
		"SCHEDULER_TYPE_BUILTIN":          2,
	}
)

func (x SchedulerType) Enum() *SchedulerType {
	p := new(SchedulerType)
	*p = x
	return p
}

func (x SchedulerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedulerType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[2].Descriptor()
}

func (SchedulerType) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[2]
}

func (x SchedulerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedulerType.Descriptor instead.
func (SchedulerType) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

// 调度类型
type ScheduleType int32

const (
	ScheduleType_SCHEDULE_TYPE_UNSPECIFIED ScheduleType = 0
	ScheduleType_SCHEDULE_TYPE_IMMEDIATE   ScheduleType = 1
	ScheduleType_SCHEDULE_TYPE_ONCE        ScheduleType = 2
	ScheduleType_SCHEDULE_TYPE_CRON        ScheduleType = 3
	ScheduleType_SCHEDULE_TYPE_INTERVAL    ScheduleType = 4
)

// Enum value maps for ScheduleType.
var (
	ScheduleType_name = map[int32]string{
		0: "SCHEDULE_TYPE_UNSPECIFIED",
		1: "SCHEDULE_TYPE_IMMEDIATE",
		2: "SCHEDULE_TYPE_ONCE",
		3: "SCHEDULE_TYPE_CRON",
		4: "SCHEDULE_TYPE_INTERVAL",
	}
	ScheduleType_value = map[string]int32{
		"SCHEDULE_TYPE_UNSPECIFIED": 0,
		"SCHEDULE_TYPE_IMMEDIATE":   1,
		"SCHEDULE_TYPE_ONCE":        2,
		"SCHEDULE_TYPE_CRON":        3,
		"SCHEDULE_TYPE_INTERVAL":    4,
	}
)

func (x ScheduleType) Enum() *ScheduleType {
	p := new(ScheduleType)
	*p = x
	return p
}

func (x ScheduleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[3].Descriptor()
}

func (ScheduleType) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[3]
}

func (x ScheduleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleType.Descriptor instead.
func (ScheduleType) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

// 执行状态
type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_PENDING     ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_RUNNING     ExecutionStatus = 2
	ExecutionStatus_EXECUTION_STATUS_COMPLETED   ExecutionStatus = 3
	ExecutionStatus_EXECUTION_STATUS_FAILED      ExecutionStatus = 4
	ExecutionStatus_EXECUTION_STATUS_CANCELLED   ExecutionStatus = 5
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_PENDING",
		2: "EXECUTION_STATUS_RUNNING",
		3: "EXECUTION_STATUS_COMPLETED",
		4: "EXECUTION_STATUS_FAILED",
		5: "EXECUTION_STATUS_CANCELLED",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"EXECUTION_STATUS_PENDING":     1,
		"EXECUTION_STATUS_RUNNING":     2,
		"EXECUTION_STATUS_COMPLETED":   3,
		"EXECUTION_STATUS_FAILED":      4,
		"EXECUTION_STATUS_CANCELLED":   5,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[4].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[4]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

// 任务配置
type TaskConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IncludeSchemas    []string               `protobuf:"bytes,1,rep,name=include_schemas,json=includeSchemas,proto3" json:"include_schemas,omitempty"`
	ExcludeSchemas    []string               `protobuf:"bytes,2,rep,name=exclude_schemas,json=excludeSchemas,proto3" json:"exclude_schemas,omitempty"`
	IncludeTables     []string               `protobuf:"bytes,3,rep,name=include_tables,json=includeTables,proto3" json:"include_tables,omitempty"`
	ExcludeTables     []string               `protobuf:"bytes,4,rep,name=exclude_tables,json=excludeTables,proto3" json:"exclude_tables,omitempty"`
	BatchSize         int32                  `protobuf:"varint,5,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	Timeout           int32                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RetryCount        int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	RetryInterval     int32                  `protobuf:"varint,8,opt,name=retry_interval,json=retryInterval,proto3" json:"retry_interval,omitempty"`
	IncrementalColumn string                 `protobuf:"bytes,9,opt,name=incremental_column,json=incrementalColumn,proto3" json:"incremental_column,omitempty"`
	IncrementalValue  string                 `protobuf:"bytes,10,opt,name=incremental_value,json=incrementalValue,proto3" json:"incremental_value,omitempty"`
	Extra             map[string]string      `protobuf:"bytes,11,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskConfig) Reset() {
	*x = TaskConfig{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskConfig) ProtoMessage() {}

func (x *TaskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskConfig.ProtoReflect.Descriptor instead.
func (*TaskConfig) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskConfig) GetIncludeSchemas() []string {
	if x != nil {
		return x.IncludeSchemas
	}
	return nil
}

func (x *TaskConfig) GetExcludeSchemas() []string {
	if x != nil {
		return x.ExcludeSchemas
	}
	return nil
}

func (x *TaskConfig) GetIncludeTables() []string {
	if x != nil {
		return x.IncludeTables
	}
	return nil
}

func (x *TaskConfig) GetExcludeTables() []string {
	if x != nil {
		return x.ExcludeTables
	}
	return nil
}

func (x *TaskConfig) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *TaskConfig) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *TaskConfig) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *TaskConfig) GetRetryInterval() int32 {
	if x != nil {
		return x.RetryInterval
	}
	return 0
}

func (x *TaskConfig) GetIncrementalColumn() string {
	if x != nil {
		return x.IncrementalColumn
	}
	return ""
}

func (x *TaskConfig) GetIncrementalValue() string {
	if x != nil {
		return x.IncrementalValue
	}
	return ""
}

func (x *TaskConfig) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// 调度配置
type ScheduleConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ScheduleType           `protobuf:"varint,1,opt,name=type,proto3,enum=api.metadata.v1.ScheduleType" json:"type,omitempty"`
	CronExpr      string                 `protobuf:"bytes,2,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	Interval      int32                  `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Timezone      string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleConfig) Reset() {
	*x = ScheduleConfig{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleConfig) ProtoMessage() {}

func (x *ScheduleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleConfig.ProtoReflect.Descriptor instead.
func (*ScheduleConfig) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleConfig) GetType() ScheduleType {
	if x != nil {
		return x.Type
	}
	return ScheduleType_SCHEDULE_TYPE_UNSPECIFIED
}

func (x *ScheduleConfig) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *ScheduleConfig) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *ScheduleConfig) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ScheduleConfig) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ScheduleConfig) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

// 采集任务
type CollectionTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DatasourceId   string                 `protobuf:"bytes,3,opt,name=datasource_id,json=datasourceId,proto3" json:"datasource_id,omitempty"`
	Type           TaskType               `protobuf:"varint,4,opt,name=type,proto3,enum=api.metadata.v1.TaskType" json:"type,omitempty"`
	Config         *TaskConfig            `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	Schedule       *ScheduleConfig        `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Status         TaskStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=api.metadata.v1.TaskStatus" json:"status,omitempty"`
	SchedulerType  SchedulerType          `protobuf:"varint,8,opt,name=scheduler_type,json=schedulerType,proto3,enum=api.metadata.v1.SchedulerType" json:"scheduler_type,omitempty"`
	ExternalId     string                 `protobuf:"bytes,9,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastExecutedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_executed_at,json=lastExecutedAt,proto3" json:"last_executed_at,omitempty"`
	NextExecuteAt  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=next_execute_at,json=nextExecuteAt,proto3" json:"next_execute_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollectionTask) Reset() {
	*x = CollectionTask{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionTask) ProtoMessage() {}

func (x *CollectionTask) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionTask.ProtoReflect.Descriptor instead.
func (*CollectionTask) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *CollectionTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CollectionTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectionTask) GetDatasourceId() string {
	if x != nil {
		return x.DatasourceId
	}
	return ""
}

func (x *CollectionTask) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *CollectionTask) GetConfig() *TaskConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CollectionTask) GetSchedule() *ScheduleConfig {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *CollectionTask) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *CollectionTask) GetSchedulerType() SchedulerType {
	if x != nil {
		return x.SchedulerType
	}
	return SchedulerType_SCHEDULER_TYPE_UNSPECIFIED
}

func (x *CollectionTask) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *CollectionTask) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CollectionTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CollectionTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CollectionTask) GetLastExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastExecutedAt
	}
	return nil
}

func (x *CollectionTask) GetNextExecuteAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextExecuteAt
	}
	return nil
}

// 执行结果
type ExecutionResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TablesProcessed  int32                  `protobuf:"varint,1,opt,name=tables_processed,json=tablesProcessed,proto3" json:"tables_processed,omitempty"`
	RecordsProcessed int64                  `protobuf:"varint,2,opt,name=records_processed,json=recordsProcessed,proto3" json:"records_processed,omitempty"`
	ErrorsCount      int32                  `protobuf:"varint,3,opt,name=errors_count,json=errorsCount,proto3" json:"errors_count,omitempty"`
	WarningsCount    int32                  `protobuf:"varint,4,opt,name=warnings_count,json=warningsCount,proto3" json:"warnings_count,omitempty"`
	ProcessingStats  map[string]int64       `protobuf:"bytes,5,rep,name=processing_stats,json=processingStats,proto3" json:"processing_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionResult) GetTablesProcessed() int32 {
	if x != nil {
		return x.TablesProcessed
	}
	return 0
}

func (x *ExecutionResult) GetRecordsProcessed() int64 {
	if x != nil {
		return x.RecordsProcessed
	}
	return 0
}

func (x *ExecutionResult) GetErrorsCount() int32 {
	if x != nil {
		return x.ErrorsCount
	}
	return 0
}

func (x *ExecutionResult) GetWarningsCount() int32 {
	if x != nil {
		return x.WarningsCount
	}
	return 0
}

func (x *ExecutionResult) GetProcessingStats() map[string]int64 {
	if x != nil {
		return x.ProcessingStats
	}
	return nil
}

// 任务执行记录
type TaskExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=api.metadata.v1.ExecutionStatus" json:"status,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration      int64                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Result        *ExecutionResult       `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Logs          string                 `protobuf:"bytes,9,opt,name=logs,proto3" json:"logs,omitempty"`
	ExternalId    string                 `protobuf:"bytes,10,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecution) Reset() {
	*x = TaskExecution{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecution) ProtoMessage() {}

func (x *TaskExecution) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecution.ProtoReflect.Descriptor instead.
func (*TaskExecution) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *TaskExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskExecution) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskExecution) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *TaskExecution) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TaskExecution) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TaskExecution) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TaskExecution) GetResult() *ExecutionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskExecution) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskExecution) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *TaskExecution) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *TaskExecution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 任务状态信息
type TaskStatusInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status         TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=api.metadata.v1.TaskStatus" json:"status,omitempty"`
	LastExecution  *TaskExecution         `protobuf:"bytes,3,opt,name=last_execution,json=lastExecution,proto3" json:"last_execution,omitempty"`
	NextExecuteAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=next_execute_at,json=nextExecuteAt,proto3" json:"next_execute_at,omitempty"`
	AllowedActions []string               `protobuf:"bytes,5,rep,name=allowed_actions,json=allowedActions,proto3" json:"allowed_actions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskStatusInfo) Reset() {
	*x = TaskStatusInfo{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusInfo) ProtoMessage() {}

func (x *TaskStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusInfo.ProtoReflect.Descriptor instead.
func (*TaskStatusInfo) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *TaskStatusInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusInfo) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskStatusInfo) GetLastExecution() *TaskExecution {
	if x != nil {
		return x.LastExecution
	}
	return nil
}

func (x *TaskStatusInfo) GetNextExecuteAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextExecuteAt
	}
	return nil
}

func (x *TaskStatusInfo) GetAllowedActions() []string {
	if x != nil {
		return x.AllowedActions
	}
	return nil
}

// 创建任务请求
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DatasourceId  string                 `protobuf:"bytes,2,opt,name=datasource_id,json=datasourceId,proto3" json:"datasource_id,omitempty"`
	Type          TaskType               `protobuf:"varint,3,opt,name=type,proto3,enum=api.metadata.v1.TaskType" json:"type,omitempty"`
	Config        *TaskConfig            `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Schedule      *ScheduleConfig        `protobuf:"bytes,5,opt,name=schedule,proto3" json:"schedule,omitempty"`
	SchedulerType SchedulerType          `protobuf:"varint,6,opt,name=scheduler_type,json=schedulerType,proto3,enum=api.metadata.v1.SchedulerType" json:"scheduler_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetDatasourceId() string {
	if x != nil {
		return x.DatasourceId
	}
	return ""
}

func (x *CreateTaskRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *CreateTaskRequest) GetConfig() *TaskConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateTaskRequest) GetSchedule() *ScheduleConfig {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *CreateTaskRequest) GetSchedulerType() SchedulerType {
	if x != nil {
		return x.SchedulerType
	}
	return SchedulerType_SCHEDULER_TYPE_UNSPECIFIED
}

// 更新任务请求
type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config        *TaskConfig            `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Schedule      *ScheduleConfig        `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTaskRequest) GetConfig() *TaskConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateTaskRequest) GetSchedule() *ScheduleConfig {
	if x != nil {
		return x.Schedule
	}
	return nil
}

// 删除任务请求
type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取任务请求
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 列出任务请求
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	DatasourceId  string                 `protobuf:"bytes,3,opt,name=datasource_id,json=datasourceId,proto3" json:"datasource_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=api.metadata.v1.TaskStatus" json:"status,omitempty"`
	Type          TaskType               `protobuf:"varint,5,opt,name=type,proto3,enum=api.metadata.v1.TaskType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{10}
}

func (x *ListTasksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetDatasourceId() string {
	if x != nil {
		return x.DatasourceId
	}
	return ""
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListTasksRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

// 列出任务响应
type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*CollectionTask      `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{11}
}

func (x *ListTasksResponse) GetTasks() []*CollectionTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTasksResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 启动任务请求
type StartTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskRequest) Reset() {
	*x = StartTaskRequest{}
	mi := &file_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskRequest) ProtoMessage() {}

func (x *StartTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskRequest.ProtoReflect.Descriptor instead.
func (*StartTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{12}
}

func (x *StartTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 停止任务请求
type StopTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskRequest) Reset() {
	*x = StopTaskRequest{}
	mi := &file_task_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskRequest) ProtoMessage() {}

func (x *StopTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskRequest.ProtoReflect.Descriptor instead.
func (*StopTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{13}
}

func (x *StopTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 暂停任务请求
type PauseTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTaskRequest) Reset() {
	*x = PauseTaskRequest{}
	mi := &file_task_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTaskRequest) ProtoMessage() {}

func (x *PauseTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTaskRequest.ProtoReflect.Descriptor instead.
func (*PauseTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{14}
}

func (x *PauseTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 恢复任务请求
type ResumeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTaskRequest) Reset() {
	*x = ResumeTaskRequest{}
	mi := &file_task_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTaskRequest) ProtoMessage() {}

func (x *ResumeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTaskRequest.ProtoReflect.Descriptor instead.
func (*ResumeTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{15}
}

func (x *ResumeTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 立即执行任务请求
type ExecuteTaskNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskNowRequest) Reset() {
	*x = ExecuteTaskNowRequest{}
	mi := &file_task_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskNowRequest) ProtoMessage() {}

func (x *ExecuteTaskNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskNowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskNowRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{16}
}

func (x *ExecuteTaskNowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取任务状态请求
type GetTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusRequest) Reset() {
	*x = GetTaskStatusRequest{}
	mi := &file_task_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRequest) ProtoMessage() {}

func (x *GetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{17}
}

func (x *GetTaskStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取执行记录请求
type GetTaskExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskExecutionRequest) Reset() {
	*x = GetTaskExecutionRequest{}
	mi := &file_task_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskExecutionRequest) ProtoMessage() {}

func (x *GetTaskExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetTaskExecutionRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{18}
}

func (x *GetTaskExecutionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 列出执行记录请求
type ListTaskExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=api.metadata.v1.ExecutionStatus" json:"status,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskExecutionsRequest) Reset() {
	*x = ListTaskExecutionsRequest{}
	mi := &file_task_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskExecutionsRequest) ProtoMessage() {}

func (x *ListTaskExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListTaskExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{19}
}

func (x *ListTaskExecutionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTaskExecutionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTaskExecutionsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListTaskExecutionsRequest) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ListTaskExecutionsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListTaskExecutionsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// 列出执行记录响应
type ListTaskExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*TaskExecution       `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskExecutionsResponse) Reset() {
	*x = ListTaskExecutionsResponse{}
	mi := &file_task_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskExecutionsResponse) ProtoMessage() {}

func (x *ListTaskExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListTaskExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{20}
}

func (x *ListTaskExecutionsResponse) GetExecutions() []*TaskExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

func (x *ListTaskExecutionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTaskExecutionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTaskExecutionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 取消执行请求
type CancelExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecutionRequest) Reset() {
	*x = CancelExecutionRequest{}
	mi := &file_task_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionRequest) ProtoMessage() {}

func (x *CancelExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionRequest.ProtoReflect.Descriptor instead.
func (*CancelExecutionRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{21}
}

func (x *CancelExecutionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 重试执行请求
type RetryExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryExecutionRequest) Reset() {
	*x = RetryExecutionRequest{}
	mi := &file_task_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryExecutionRequest) ProtoMessage() {}

func (x *RetryExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryExecutionRequest.ProtoReflect.Descriptor instead.
func (*RetryExecutionRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{22}
}

func (x *RetryExecutionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 批量任务操作请求
type BatchTaskOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTaskOperationRequest) Reset() {
	*x = BatchTaskOperationRequest{}
	mi := &file_task_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTaskOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTaskOperationRequest) ProtoMessage() {}

func (x *BatchTaskOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTaskOperationRequest.ProtoReflect.Descriptor instead.
func (*BatchTaskOperationRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{23}
}

func (x *BatchTaskOperationRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 批量任务操作结果
type BatchTaskOperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Success       int32                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Results       map[string]string      `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTaskOperationResult) Reset() {
	*x = BatchTaskOperationResult{}
	mi := &file_task_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTaskOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTaskOperationResult) ProtoMessage() {}

func (x *BatchTaskOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTaskOperationResult.ProtoReflect.Descriptor instead.
func (*BatchTaskOperationResult) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{24}
}

func (x *BatchTaskOperationResult) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BatchTaskOperationResult) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *BatchTaskOperationResult) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchTaskOperationResult) GetResults() map[string]string {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x0fapi.metadata.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\"\xb1\x04\n" +
	"\n" +
	"TaskConfig\x12'\n" +
	"\x0finclude_schemas\x18\x01 \x03(\tR\x0eincludeSchemas\x12'\n" +
	"\x0fexclude_schemas\x18\x02 \x03(\tR\x0eexcludeSchemas\x12%\n" +
	"\x0einclude_tables\x18\x03 \x03(\tR\rincludeTables\x12%\n" +
	"\x0eexclude_tables\x18\x04 \x03(\tR\rexcludeTables\x12)\n" +
	"\n" +
	"batch_size\x18\x05 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\x90N(\x00R\tbatchSize\x12%\n" +
	"\atimeout\x18\x06 \x01(\x05B\v\xfaB\b\x1a\x06\x18\x80\xa3\x05(\x00R\atimeout\x12*\n" +
	"\vretry_count\x18\a \x01(\x05B\t\xfaB\x06\x1a\x04\x18\n" +
	"(\x00R\n" +
	"retryCount\x121\n" +
	"\x0eretry_interval\x18\b \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\x90\x1c(\x00R\rretryInterval\x12-\n" +
	"\x12incremental_column\x18\t \x01(\tR\x11incrementalColumn\x12+\n" +
	"\x11incremental_value\x18\n" +
	" \x01(\tR\x10incrementalValue\x12<\n" +
	"\x05extra\x18\v \x03(\v2&.api.metadata.v1.TaskConfig.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x02\n" +
	"\x0eScheduleConfig\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.api.metadata.v1.ScheduleTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04type\x12$\n" +
	"\tcron_expr\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18dR\bcronExpr\x12#\n" +
	"\binterval\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\binterval\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12#\n" +
	"\btimezone\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x182R\btimezone\"\xb6\x05\n" +
	"\x0eCollectionTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rdatasource_id\x18\x03 \x01(\tR\fdatasourceId\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.api.metadata.v1.TaskTypeR\x04type\x123\n" +
	"\x06config\x18\x05 \x01(\v2\x1b.api.metadata.v1.TaskConfigR\x06config\x12;\n" +
	"\bschedule\x18\x06 \x01(\v2\x1f.api.metadata.v1.ScheduleConfigR\bschedule\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.api.metadata.v1.TaskStatusR\x06status\x12E\n" +
	"\x0escheduler_type\x18\b \x01(\x0e2\x1e.api.metadata.v1.SchedulerTypeR\rschedulerType\x12\x1f\n" +
	"\vexternal_id\x18\t \x01(\tR\n" +
	"externalId\x12\x1d\n" +
	"\n" +
	"created_by\x18\n" +
	" \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12D\n" +
	"\x10last_executed_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x0elastExecutedAt\x12B\n" +
	"\x0fnext_execute_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\rnextExecuteAt\"\xd9\x02\n" +
	"\x0fExecutionResult\x12)\n" +
	"\x10tables_processed\x18\x01 \x01(\x05R\x0ftablesProcessed\x12+\n" +
	"\x11records_processed\x18\x02 \x01(\x03R\x10recordsProcessed\x12!\n" +
	"\ferrors_count\x18\x03 \x01(\x05R\verrorsCount\x12%\n" +
	"\x0ewarnings_count\x18\x04 \x01(\x05R\rwarningsCount\x12`\n" +
	"\x10processing_stats\x18\x05 \x03(\v25.api.metadata.v1.ExecutionResult.ProcessingStatsEntryR\x0fprocessingStats\x1aB\n" +
	"\x14ProcessingStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xcf\x03\n" +
	"\rTaskExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x128\n" +
	"\x06status\x18\x03 \x01(\x0e2 .api.metadata.v1.ExecutionStatusR\x06status\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x03R\bduration\x128\n" +
	"\x06result\x18\a \x01(\v2 .api.metadata.v1.ExecutionResultR\x06result\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04logs\x18\t \x01(\tR\x04logs\x12\x1f\n" +
	"\vexternal_id\x18\n" +
	" \x01(\tR\n" +
	"externalId\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x92\x02\n" +
	"\x0eTaskStatusInfo\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.api.metadata.v1.TaskStatusR\x06status\x12E\n" +
	"\x0elast_execution\x18\x03 \x01(\v2\x1e.api.metadata.v1.TaskExecutionR\rlastExecution\x12B\n" +
	"\x0fnext_execute_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rnextExecuteAt\x12'\n" +
	"\x0fallowed_actions\x18\x05 \x03(\tR\x0eallowedActions\"\xd4\x02\n" +
	"\x11CreateTaskRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x04name\x12,\n" +
	"\rdatasource_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\fdatasourceId\x129\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.api.metadata.v1.TaskTypeB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x04type\x123\n" +
	"\x06config\x18\x04 \x01(\v2\x1b.api.metadata.v1.TaskConfigR\x06config\x12;\n" +
	"\bschedule\x18\x05 \x01(\v2\x1f.api.metadata.v1.ScheduleConfigR\bschedule\x12E\n" +
	"\x0escheduler_type\x18\x06 \x01(\x0e2\x1e.api.metadata.v1.SchedulerTypeR\rschedulerType\"\xbb\x01\n" +
	"\x11UpdateTaskRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18dR\x04name\x123\n" +
	"\x06config\x18\x03 \x01(\v2\x1b.api.metadata.v1.TaskConfigR\x06config\x12;\n" +
	"\bschedule\x18\x04 \x01(\v2\x1f.api.metadata.v1.ScheduleConfigR\bschedule\",\n" +
	"\x11DeleteTaskRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"\xe0\x01\n" +
	"\x10ListTasksRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x04page\x12&\n" +
	"\tpage_size\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\bpageSize\x12#\n" +
	"\rdatasource_id\x18\x03 \x01(\tR\fdatasourceId\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.api.metadata.v1.TaskStatusR\x06status\x12-\n" +
	"\x04type\x18\x05 \x01(\x0e2\x19.api.metadata.v1.TaskTypeR\x04type\"\x91\x01\n" +
	"\x11ListTasksResponse\x125\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1f.api.metadata.v1.CollectionTaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"+\n" +
	"\x10StartTaskRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"*\n" +
	"\x0fStopTaskRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"+\n" +
	"\x10PauseTaskRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\",\n" +
	"\x11ResumeTaskRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"0\n" +
	"\x15ExecuteTaskNowRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"/\n" +
	"\x14GetTaskStatusRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"2\n" +
	"\x17GetTaskExecutionRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"\xae\x02\n" +
	"\x19ListTaskExecutionsRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x04page\x12&\n" +
	"\tpage_size\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\bpageSize\x12 \n" +
	"\atask_id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06taskId\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2 .api.metadata.v1.ExecutionStatusR\x06status\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xa3\x01\n" +
	"\x1aListTaskExecutionsResponse\x12>\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x1e.api.metadata.v1.TaskExecutionR\n" +
	"executions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"1\n" +
	"\x16CancelExecutionRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"0\n" +
	"\x15RetryExecutionRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"9\n" +
	"\x19BatchTaskOperationRequest\x12\x1c\n" +
	"\x03ids\x18\x01 \x03(\tB\n" +
	"\xfaB\a\x92\x01\x04\b\x01\x10dR\x03ids\"\xf0\x01\n" +
	"\x18BatchTaskOperationResult\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\x05R\asuccess\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12P\n" +
	"\aresults\x18\x04 \x03(\v26.api.metadata.v1.BatchTaskOperationResult.ResultsEntryR\aresults\x1a:\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xa1\x01\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TASK_TYPE_FULL_COLLECTION\x10\x01\x12$\n" +
	" TASK_TYPE_INCREMENTAL_COLLECTION\x10\x02\x12\x19\n" +
	"\x15TASK_TYPE_SCHEMA_ONLY\x10\x03\x12\x1a\n" +
	"\x16TASK_TYPE_DATA_PROFILE\x10\x04*\xbf\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14TASK_STATUS_INACTIVE\x10\x02\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x04\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x05\x12\x16\n" +
	"\x12TASK_STATUS_PAUSED\x10\x06*p\n" +
	"\rSchedulerType\x12\x1e\n" +
	"\x1aSCHEDULER_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSCHEDULER_TYPE_DOLPHINSCHEDULER\x10\x01\x12\x1a\n" +
	"\x16SCHEDULER_TYPE_BUILTIN\x10\x02*\x96\x01\n" +
	"\fScheduleType\x12\x1d\n" +
	"\x19SCHEDULE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SCHEDULE_TYPE_IMMEDIATE\x10\x01\x12\x16\n" +
	"\x12SCHEDULE_TYPE_ONCE\x10\x02\x12\x16\n" +
	"\x12SCHEDULE_TYPE_CRON\x10\x03\x12\x1a\n" +
	"\x16SCHEDULE_TYPE_INTERVAL\x10\x04*\xcc\x01\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EXECUTION_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18EXECUTION_STATUS_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17EXECUTION_STATUS_FAILED\x10\x04\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_CANCELLED\x10\x052\x9c\x11\n" +
	"\vTaskService\x12k\n" +
	"\n" +
	"CreateTask\x12\".api.metadata.v1.CreateTaskRequest\x1a\x1f.api.metadata.v1.CollectionTask\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/tasks\x12p\n" +
	"\n" +
	"UpdateTask\x12\".api.metadata.v1.UpdateTaskRequest\x1a\x1f.api.metadata.v1.CollectionTask\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/tasks/{id}\x12d\n" +
	"\n" +
	"DeleteTask\x12\".api.metadata.v1.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/tasks/{id}\x12g\n" +
	"\aGetTask\x12\x1f.api.metadata.v1.GetTaskRequest\x1a\x1f.api.metadata.v1.CollectionTask\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/tasks/{id}\x12i\n" +
	"\tListTasks\x12!.api.metadata.v1.ListTasksRequest\x1a\".api.metadata.v1.ListTasksResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/tasks\x12h\n" +
	"\tStartTask\x12!.api.metadata.v1.StartTaskRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a\"\x18/api/v1/tasks/{id}/start\x12e\n" +
	"\bStopTask\x12 .api.metadata.v1.StopTaskRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/api/v1/tasks/{id}/stop\x12h\n" +
	"\tPauseTask\x12!.api.metadata.v1.PauseTaskRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a\"\x18/api/v1/tasks/{id}/pause\x12k\n" +
	"\n" +
	"ResumeTask\x12\".api.metadata.v1.ResumeTaskRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/api/v1/tasks/{id}/resume\x12|\n" +
	"\x0eExecuteTaskNow\x12&.api.metadata.v1.ExecuteTaskNowRequest\x1a\x1e.api.metadata.v1.TaskExecution\"\"\x82\xd3\xe4\x93\x02\x1c\"\x1a/api/v1/tasks/{id}/execute\x12z\n" +
	"\rGetTaskStatus\x12%.api.metadata.v1.GetTaskStatusRequest\x1a\x1f.api.metadata.v1.TaskStatusInfo\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/tasks/{id}/status\x12}\n" +
	"\x10GetTaskExecution\x12(.api.metadata.v1.GetTaskExecutionRequest\x1a\x1e.api.metadata.v1.TaskExecution\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/executions/{id}\x12\x99\x01\n" +
	"\x12ListTaskExecutions\x12*.api.metadata.v1.ListTaskExecutionsRequest\x1a+.api.metadata.v1.ListTaskExecutionsResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/tasks/{task_id}/executions\x12\x82\x01\n" +
	"\x0fCancelExecution\x12'.api.metadata.v1.CancelExecutionRequest\x1a\x1e.api.metadata.v1.TaskExecution\"&\x82\xd3\xe4\x93\x02 \"\x1e/api/v1/executions/{id}/cancel\x12\x7f\n" +
	"\x0eRetryExecution\x12&.api.metadata.v1.RetryExecutionRequest\x1a\x1e.api.metadata.v1.TaskExecution\"%\x82\xd3\xe4\x93\x02\x1f\"\x1d/api/v1/executions/{id}/retry\x12\x8e\x01\n" +
	"\x0fBatchStartTasks\x12*.api.metadata.v1.BatchTaskOperationRequest\x1a).api.metadata.v1.BatchTaskOperationResult\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/tasks/batch/start\x12\x8c\x01\n" +
	"\x0eBatchStopTasks\x12*.api.metadata.v1.BatchTaskOperationRequest\x1a).api.metadata.v1.BatchTaskOperationResult\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/tasks/batch/stop\x12\x90\x01\n" +
	"\x10BatchDeleteTasks\x12*.api.metadata.v1.BatchTaskOperationRequest\x1a).api.metadata.v1.BatchTaskOperationResult\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/tasks/batch/deleteB Z\x1ego-metadata/api/metadata/v1;v1b\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_task_proto_goTypes = []any{
	(TaskType)(0),                      // 0: api.metadata.v1.TaskType
	(TaskStatus)(0),                    // 1: api.metadata.v1.TaskStatus
	(SchedulerType)(0),                 // 2: api.metadata.v1.SchedulerType
	(ScheduleType)(0),                  // 3: api.metadata.v1.ScheduleType
	(ExecutionStatus)(0),               // 4: api.metadata.v1.ExecutionStatus
	(*TaskConfig)(nil),                 // 5: api.metadata.v1.TaskConfig
	(*ScheduleConfig)(nil),             // 6: api.metadata.v1.ScheduleConfig
	(*CollectionTask)(nil),             // 7: api.metadata.v1.CollectionTask
	(*ExecutionResult)(nil),            // 8: api.metadata.v1.ExecutionResult
	(*TaskExecution)(nil),              // 9: api.metadata.v1.TaskExecution
	(*TaskStatusInfo)(nil),             // 10: api.metadata.v1.TaskStatusInfo
	(*CreateTaskRequest)(nil),          // 11: api.metadata.v1.CreateTaskRequest
	(*UpdateTaskRequest)(nil),          // 12: api.metadata.v1.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),          // 13: api.metadata.v1.DeleteTaskRequest
	(*GetTaskRequest)(nil),             // 14: api.metadata.v1.GetTaskRequest
	(*ListTasksRequest)(nil),           // 15: api.metadata.v1.ListTasksRequest
	(*ListTasksResponse)(nil),          // 16: api.metadata.v1.ListTasksResponse
	(*StartTaskRequest)(nil),           // 17: api.metadata.v1.StartTaskRequest
	(*StopTaskRequest)(nil),            // 18: api.metadata.v1.StopTaskRequest
	(*PauseTaskRequest)(nil),           // 19: api.metadata.v1.PauseTaskRequest
	(*ResumeTaskRequest)(nil),          // 20: api.metadata.v1.ResumeTaskRequest
	(*ExecuteTaskNowRequest)(nil),      // 21: api.metadata.v1.ExecuteTaskNowRequest
	(*GetTaskStatusRequest)(nil),       // 22: api.metadata.v1.GetTaskStatusRequest
	(*GetTaskExecutionRequest)(nil),    // 23: api.metadata.v1.GetTaskExecutionRequest
	(*ListTaskExecutionsRequest)(nil),  // 24: api.metadata.v1.ListTaskExecutionsRequest
	(*ListTaskExecutionsResponse)(nil), // 25: api.metadata.v1.ListTaskExecutionsResponse
	(*CancelExecutionRequest)(nil),     // 26: api.metadata.v1.CancelExecutionRequest
	(*RetryExecutionRequest)(nil),      // 27: api.metadata.v1.RetryExecutionRequest
	(*BatchTaskOperationRequest)(nil),  // 28: api.metadata.v1.BatchTaskOperationRequest
	(*BatchTaskOperationResult)(nil),   // 29: api.metadata.v1.BatchTaskOperationResult
	nil,                                // 30: api.metadata.v1.TaskConfig.ExtraEntry
	nil,                                // 31: api.metadata.v1.ExecutionResult.ProcessingStatsEntry
	nil,                                // 32: api.metadata.v1.BatchTaskOperationResult.ResultsEntry
	(*timestamppb.Timestamp)(nil),      // 33: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 34: google.protobuf.Empty
}
var file_task_proto_depIdxs = []int32{
	30, // 0: api.metadata.v1.TaskConfig.extra:type_name -> api.metadata.v1.TaskConfig.ExtraEntry
	3,  // 1: api.metadata.v1.ScheduleConfig.type:type_name -> api.metadata.v1.ScheduleType
	33, // 2: api.metadata.v1.ScheduleConfig.start_time:type_name -> google.protobuf.Timestamp
	33, // 3: api.metadata.v1.ScheduleConfig.end_time:type_name -> google.protobuf.Timestamp
	0,  // 4: api.metadata.v1.CollectionTask.type:type_name -> api.metadata.v1.TaskType
	5,  // 5: api.metadata.v1.CollectionTask.config:type_name -> api.metadata.v1.TaskConfig
	6,  // 6: api.metadata.v1.CollectionTask.schedule:type_name -> api.metadata.v1.ScheduleConfig
	1,  // 7: api.metadata.v1.CollectionTask.status:type_name -> api.metadata.v1.TaskStatus
	2,  // 8: api.metadata.v1.CollectionTask.scheduler_type:type_name -> api.metadata.v1.SchedulerType
	33, // 9: api.metadata.v1.CollectionTask.created_at:type_name -> google.protobuf.Timestamp
	33, // 10: api.metadata.v1.CollectionTask.updated_at:type_name -> google.protobuf.Timestamp
	33, // 11: api.metadata.v1.CollectionTask.last_executed_at:type_name -> google.protobuf.Timestamp
	33, // 12: api.metadata.v1.CollectionTask.next_execute_at:type_name -> google.protobuf.Timestamp
	31, // 13: api.metadata.v1.ExecutionResult.processing_stats:type_name -> api.metadata.v1.ExecutionResult.ProcessingStatsEntry
	4,  // 14: api.metadata.v1.TaskExecution.status:type_name -> api.metadata.v1.ExecutionStatus
	33, // 15: api.metadata.v1.TaskExecution.start_time:type_name -> google.protobuf.Timestamp
	33, // 16: api.metadata.v1.TaskExecution.end_time:type_name -> google.protobuf.Timestamp
	8,  // 17: api.metadata.v1.TaskExecution.result:type_name -> api.metadata.v1.ExecutionResult
	33, // 18: api.metadata.v1.TaskExecution.created_at:type_name -> google.protobuf.Timestamp
	1,  // 19: api.metadata.v1.TaskStatusInfo.status:type_name -> api.metadata.v1.TaskStatus
	9,  // 20: api.metadata.v1.TaskStatusInfo.last_execution:type_name -> api.metadata.v1.TaskExecution
	33, // 21: api.metadata.v1.TaskStatusInfo.next_execute_at:type_name -> google.protobuf.Timestamp
	0,  // 22: api.metadata.v1.CreateTaskRequest.type:type_name -> api.metadata.v1.TaskType
	5,  // 23: api.metadata.v1.CreateTaskRequest.config:type_name -> api.metadata.v1.TaskConfig
	6,  // 24: api.metadata.v1.CreateTaskRequest.schedule:type_name -> api.metadata.v1.ScheduleConfig
	2,  // 25: api.metadata.v1.CreateTaskRequest.scheduler_type:type_name -> api.metadata.v1.SchedulerType
	5,  // 26: api.metadata.v1.UpdateTaskRequest.config:type_name -> api.metadata.v1.TaskConfig
	6,  // 27: api.metadata.v1.UpdateTaskRequest.schedule:type_name -> api.metadata.v1.ScheduleConfig
	1,  // 28: api.metadata.v1.ListTasksRequest.status:type_name -> api.metadata.v1.TaskStatus
	0,  // 29: api.metadata.v1.ListTasksRequest.type:type_name -> api.metadata.v1.TaskType
	7,  // 30: api.metadata.v1.ListTasksResponse.tasks:type_name -> api.metadata.v1.CollectionTask
	4,  // 31: api.metadata.v1.ListTaskExecutionsRequest.status:type_name -> api.metadata.v1.ExecutionStatus
	33, // 32: api.metadata.v1.ListTaskExecutionsRequest.start_time:type_name -> google.protobuf.Timestamp
	33, // 33: api.metadata.v1.ListTaskExecutionsRequest.end_time:type_name -> google.protobuf.Timestamp
	9,  // 34: api.metadata.v1.ListTaskExecutionsResponse.executions:type_name -> api.metadata.v1.TaskExecution
	32, // 35: api.metadata.v1.BatchTaskOperationResult.results:type_name -> api.metadata.v1.BatchTaskOperationResult.ResultsEntry
	11, // 36: api.metadata.v1.TaskService.CreateTask:input_type -> api.metadata.v1.CreateTaskRequest
	12, // 37: api.metadata.v1.TaskService.UpdateTask:input_type -> api.metadata.v1.UpdateTaskRequest
	13, // 38: api.metadata.v1.TaskService.DeleteTask:input_type -> api.metadata.v1.DeleteTaskRequest
	14, // 39: api.metadata.v1.TaskService.GetTask:input_type -> api.metadata.v1.GetTaskRequest
	15, // 40: api.metadata.v1.TaskService.ListTasks:input_type -> api.metadata.v1.ListTasksRequest
	17, // 41: api.metadata.v1.TaskService.StartTask:input_type -> api.metadata.v1.StartTaskRequest
	18, // 42: api.metadata.v1.TaskService.StopTask:input_type -> api.metadata.v1.StopTaskRequest
	19, // 43: api.metadata.v1.TaskService.PauseTask:input_type -> api.metadata.v1.PauseTaskRequest
	20, // 44: api.metadata.v1.TaskService.ResumeTask:input_type -> api.metadata.v1.ResumeTaskRequest
	21, // 45: api.metadata.v1.TaskService.ExecuteTaskNow:input_type -> api.metadata.v1.ExecuteTaskNowRequest
	22, // 46: api.metadata.v1.TaskService.GetTaskStatus:input_type -> api.metadata.v1.GetTaskStatusRequest
	23, // 47: api.metadata.v1.TaskService.GetTaskExecution:input_type -> api.metadata.v1.GetTaskExecutionRequest
	24, // 48: api.metadata.v1.TaskService.ListTaskExecutions:input_type -> api.metadata.v1.ListTaskExecutionsRequest
	26, // 49: api.metadata.v1.TaskService.CancelExecution:input_type -> api.metadata.v1.CancelExecutionRequest
	27, // 50: api.metadata.v1.TaskService.RetryExecution:input_type -> api.metadata.v1.RetryExecutionRequest
	28, // 51: api.metadata.v1.TaskService.BatchStartTasks:input_type -> api.metadata.v1.BatchTaskOperationRequest
	28, // 52: api.metadata.v1.TaskService.BatchStopTasks:input_type -> api.metadata.v1.BatchTaskOperationRequest
	28, // 53: api.metadata.v1.TaskService.BatchDeleteTasks:input_type -> api.metadata.v1.BatchTaskOperationRequest
	7,  // 54: api.metadata.v1.TaskService.CreateTask:output_type -> api.metadata.v1.CollectionTask
	7,  // 55: api.metadata.v1.TaskService.UpdateTask:output_type -> api.metadata.v1.CollectionTask
	34, // 56: api.metadata.v1.TaskService.DeleteTask:output_type -> google.protobuf.Empty
	7,  // 57: api.metadata.v1.TaskService.GetTask:output_type -> api.metadata.v1.CollectionTask
	16, // 58: api.metadata.v1.TaskService.ListTasks:output_type -> api.metadata.v1.ListTasksResponse
	34, // 59: api.metadata.v1.TaskService.StartTask:output_type -> google.protobuf.Empty
	34, // 60: api.metadata.v1.TaskService.StopTask:output_type -> google.protobuf.Empty
	34, // 61: api.metadata.v1.TaskService.PauseTask:output_type -> google.protobuf.Empty
	34, // 62: api.metadata.v1.TaskService.ResumeTask:output_type -> google.protobuf.Empty
	9,  // 63: api.metadata.v1.TaskService.ExecuteTaskNow:output_type -> api.metadata.v1.TaskExecution
	10, // 64: api.metadata.v1.TaskService.GetTaskStatus:output_type -> api.metadata.v1.TaskStatusInfo
	9,  // 65: api.metadata.v1.TaskService.GetTaskExecution:output_type -> api.metadata.v1.TaskExecution
	25, // 66: api.metadata.v1.TaskService.ListTaskExecutions:output_type -> api.metadata.v1.ListTaskExecutionsResponse
	9,  // 67: api.metadata.v1.TaskService.CancelExecution:output_type -> api.metadata.v1.TaskExecution
	9,  // 68: api.metadata.v1.TaskService.RetryExecution:output_type -> api.metadata.v1.TaskExecution
	29, // 69: api.metadata.v1.TaskService.BatchStartTasks:output_type -> api.metadata.v1.BatchTaskOperationResult
	29, // 70: api.metadata.v1.TaskService.BatchStopTasks:output_type -> api.metadata.v1.BatchTaskOperationResult
	29, // 71: api.metadata.v1.TaskService.BatchDeleteTasks:output_type -> api.metadata.v1.BatchTaskOperationResult
	54, // [54:72] is the sub-list for method output_type
	36, // [36:54] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		EnumInfos:         file_task_proto_enumTypes,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
