// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/metadata/v1/task.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TaskConfig with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TaskConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TaskConfigMultiError, or
// nil if none found.
func (m *TaskConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetBatchSize(); val < 0 || val > 10000 {
		err := TaskConfigValidationError{
			field:  "BatchSize",
			reason: "value must be inside range [0, 10000]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetTimeout(); val < 0 || val > 86400 {
		err := TaskConfigValidationError{
			field:  "Timeout",
			reason: "value must be inside range [0, 86400]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetRetryCount(); val < 0 || val > 10 {
		err := TaskConfigValidationError{
			field:  "RetryCount",
			reason: "value must be inside range [0, 10]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetRetryInterval(); val < 0 || val > 3600 {
		err := TaskConfigValidationError{
			field:  "RetryInterval",
			reason: "value must be inside range [0, 3600]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IncrementalColumn

	// no validation rules for IncrementalValue

	// no validation rules for Extra

	if len(errors) > 0 {
		return TaskConfigMultiError(errors)
	}

	return nil
}

// TaskConfigMultiError is an error wrapping multiple validation errors
// returned by TaskConfig.ValidateAll() if the designated constraints aren't met.
type TaskConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskConfigMultiError) AllErrors() []error { return m }

// TaskConfigValidationError is the validation error returned by
// TaskConfig.Validate if the designated constraints aren't met.
type TaskConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskConfigValidationError) ErrorName() string { return "TaskConfigValidationError" }

// Error satisfies the builtin error interface
func (e TaskConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskConfigValidationError{}

// Validate checks the field values on ScheduleConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ScheduleConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ScheduleConfig with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ScheduleConfigMultiError,
// or nil if none found.
func (m *ScheduleConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *ScheduleConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := ScheduleType_name[int32(m.GetType())]; !ok {
		err := ScheduleConfigValidationError{
			field:  "Type",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCronExpr()) > 100 {
		err := ScheduleConfigValidationError{
			field:  "CronExpr",
			reason: "value length must be at most 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetInterval() < 0 {
		err := ScheduleConfigValidationError{
			field:  "Interval",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetStartTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ScheduleConfigValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ScheduleConfigValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ScheduleConfigValidationError{
				field:  "StartTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ScheduleConfigValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ScheduleConfigValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ScheduleConfigValidationError{
				field:  "EndTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if utf8.RuneCountInString(m.GetTimezone()) > 50 {
		err := ScheduleConfigValidationError{
			field:  "Timezone",
			reason: "value length must be at most 50 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ScheduleConfigMultiError(errors)
	}

	return nil
}

// ScheduleConfigMultiError is an error wrapping multiple validation errors
// returned by ScheduleConfig.ValidateAll() if the designated constraints
// aren't met.
type ScheduleConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ScheduleConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ScheduleConfigMultiError) AllErrors() []error { return m }

// ScheduleConfigValidationError is the validation error returned by
// ScheduleConfig.Validate if the designated constraints aren't met.
type ScheduleConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ScheduleConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ScheduleConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ScheduleConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ScheduleConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ScheduleConfigValidationError) ErrorName() string { return "ScheduleConfigValidationError" }

// Error satisfies the builtin error interface
func (e ScheduleConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sScheduleConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ScheduleConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ScheduleConfigValidationError{}

// Validate checks the field values on CollectionTask with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CollectionTask) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CollectionTask with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CollectionTaskMultiError,
// or nil if none found.
func (m *CollectionTask) ValidateAll() error {
	return m.validate(true)
}

func (m *CollectionTask) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for DatasourceId

	// no validation rules for Type

	if all {
		switch v := interface{}(m.GetConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CollectionTaskValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CollectionTaskValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CollectionTaskValidationError{
				field:  "Config",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSchedule()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CollectionTaskValidationError{
					field:  "Schedule",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CollectionTaskValidationError{
					field:  "Schedule",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSchedule()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CollectionTaskValidationError{
				field:  "Schedule",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	// no validation rules for SchedulerType

	// no validation rules for ExternalId

	// no validation rules for CreatedBy

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CollectionTaskValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CollectionTaskValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CollectionTaskValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CollectionTaskValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CollectionTaskValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CollectionTaskValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetLastExecutedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CollectionTaskValidationError{
					field:  "LastExecutedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CollectionTaskValidationError{
					field:  "LastExecutedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastExecutedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CollectionTaskValidationError{
				field:  "LastExecutedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetNextExecuteAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CollectionTaskValidationError{
					field:  "NextExecuteAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CollectionTaskValidationError{
					field:  "NextExecuteAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNextExecuteAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CollectionTaskValidationError{
				field:  "NextExecuteAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CollectionTaskMultiError(errors)
	}

	return nil
}

// CollectionTaskMultiError is an error wrapping multiple validation errors
// returned by CollectionTask.ValidateAll() if the designated constraints
// aren't met.
type CollectionTaskMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CollectionTaskMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CollectionTaskMultiError) AllErrors() []error { return m }

// CollectionTaskValidationError is the validation error returned by
// CollectionTask.Validate if the designated constraints aren't met.
type CollectionTaskValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CollectionTaskValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CollectionTaskValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CollectionTaskValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CollectionTaskValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CollectionTaskValidationError) ErrorName() string { return "CollectionTaskValidationError" }

// Error satisfies the builtin error interface
func (e CollectionTaskValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCollectionTask.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CollectionTaskValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CollectionTaskValidationError{}

// Validate checks the field values on ExecutionResult with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ExecutionResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExecutionResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExecutionResultMultiError, or nil if none found.
func (m *ExecutionResult) ValidateAll() error {
	return m.validate(true)
}

func (m *ExecutionResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TablesProcessed

	// no validation rules for RecordsProcessed

	// no validation rules for ErrorsCount

	// no validation rules for WarningsCount

	// no validation rules for ProcessingStats

	if len(errors) > 0 {
		return ExecutionResultMultiError(errors)
	}

	return nil
}

// ExecutionResultMultiError is an error wrapping multiple validation errors
// returned by ExecutionResult.ValidateAll() if the designated constraints
// aren't met.
type ExecutionResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExecutionResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExecutionResultMultiError) AllErrors() []error { return m }

// ExecutionResultValidationError is the validation error returned by
// ExecutionResult.Validate if the designated constraints aren't met.
type ExecutionResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecutionResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecutionResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecutionResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecutionResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecutionResultValidationError) ErrorName() string { return "ExecutionResultValidationError" }

// Error satisfies the builtin error interface
func (e ExecutionResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecutionResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecutionResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecutionResultValidationError{}

// Validate checks the field values on TaskExecution with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TaskExecution) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskExecution with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TaskExecutionMultiError, or
// nil if none found.
func (m *TaskExecution) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskExecution) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TaskId

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetStartTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TaskExecutionValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TaskExecutionValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TaskExecutionValidationError{
				field:  "StartTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TaskExecutionValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TaskExecutionValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TaskExecutionValidationError{
				field:  "EndTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Duration

	if all {
		switch v := interface{}(m.GetResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TaskExecutionValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TaskExecutionValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TaskExecutionValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ErrorMessage

	// no validation rules for Logs

	// no validation rules for ExternalId

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TaskExecutionValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TaskExecutionValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TaskExecutionValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TaskExecutionMultiError(errors)
	}

	return nil
}

// TaskExecutionMultiError is an error wrapping multiple validation errors
// returned by TaskExecution.ValidateAll() if the designated constraints
// aren't met.
type TaskExecutionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskExecutionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskExecutionMultiError) AllErrors() []error { return m }

// TaskExecutionValidationError is the validation error returned by
// TaskExecution.Validate if the designated constraints aren't met.
type TaskExecutionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskExecutionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskExecutionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskExecutionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskExecutionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskExecutionValidationError) ErrorName() string { return "TaskExecutionValidationError" }

// Error satisfies the builtin error interface
func (e TaskExecutionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskExecution.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskExecutionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskExecutionValidationError{}

// Validate checks the field values on TaskStatusInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TaskStatusInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskStatusInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TaskStatusInfoMultiError,
// or nil if none found.
func (m *TaskStatusInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskStatusInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetLastExecution()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TaskStatusInfoValidationError{
					field:  "LastExecution",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TaskStatusInfoValidationError{
					field:  "LastExecution",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastExecution()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TaskStatusInfoValidationError{
				field:  "LastExecution",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetNextExecuteAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TaskStatusInfoValidationError{
					field:  "NextExecuteAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TaskStatusInfoValidationError{
					field:  "NextExecuteAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNextExecuteAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TaskStatusInfoValidationError{
				field:  "NextExecuteAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TaskStatusInfoMultiError(errors)
	}

	return nil
}

// TaskStatusInfoMultiError is an error wrapping multiple validation errors
// returned by TaskStatusInfo.ValidateAll() if the designated constraints
// aren't met.
type TaskStatusInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskStatusInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskStatusInfoMultiError) AllErrors() []error { return m }

// TaskStatusInfoValidationError is the validation error returned by
// TaskStatusInfo.Validate if the designated constraints aren't met.
type TaskStatusInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskStatusInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskStatusInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskStatusInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskStatusInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskStatusInfoValidationError) ErrorName() string { return "TaskStatusInfoValidationError" }

// Error satisfies the builtin error interface
func (e TaskStatusInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskStatusInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskStatusInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskStatusInfoValidationError{}

// Validate checks the field values on CreateTaskRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateTaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTaskRequestMultiError, or nil if none found.
func (m *CreateTaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 100 {
		err := CreateTaskRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDatasourceId()) < 1 {
		err := CreateTaskRequestValidationError{
			field:  "DatasourceId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreateTaskRequest_Type_NotInLookup[m.GetType()]; ok {
		err := CreateTaskRequestValidationError{
			field:  "Type",
			reason: "value must not be in list [TASK_TYPE_UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := TaskType_name[int32(m.GetType())]; !ok {
		err := CreateTaskRequestValidationError{
			field:  "Type",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateTaskRequestValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateTaskRequestValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateTaskRequestValidationError{
				field:  "Config",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSchedule()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateTaskRequestValidationError{
					field:  "Schedule",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateTaskRequestValidationError{
					field:  "Schedule",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSchedule()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateTaskRequestValidationError{
				field:  "Schedule",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SchedulerType

	if len(errors) > 0 {
		return CreateTaskRequestMultiError(errors)
	}

	return nil
}

// CreateTaskRequestMultiError is an error wrapping multiple validation errors
// returned by CreateTaskRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateTaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTaskRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTaskRequestMultiError) AllErrors() []error { return m }

// CreateTaskRequestValidationError is the validation error returned by
// CreateTaskRequest.Validate if the designated constraints aren't met.
type CreateTaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTaskRequestValidationError) ErrorName() string {
	return "CreateTaskRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTaskRequestValidationError{}

var _CreateTaskRequest_Type_NotInLookup = map[TaskType]struct{}{
	0: {},
}

// Validate checks the field values on UpdateTaskRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateTaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTaskRequestMultiError, or nil if none found.
func (m *UpdateTaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := UpdateTaskRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) > 100 {
		err := UpdateTaskRequestValidationError{
			field:  "Name",
			reason: "value length must be at most 100 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateTaskRequestValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateTaskRequestValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateTaskRequestValidationError{
				field:  "Config",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSchedule()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateTaskRequestValidationError{
					field:  "Schedule",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateTaskRequestValidationError{
					field:  "Schedule",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSchedule()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateTaskRequestValidationError{
				field:  "Schedule",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateTaskRequestMultiError(errors)
	}

	return nil
}

// UpdateTaskRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateTaskRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateTaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTaskRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTaskRequestMultiError) AllErrors() []error { return m }

// UpdateTaskRequestValidationError is the validation error returned by
// UpdateTaskRequest.Validate if the designated constraints aren't met.
type UpdateTaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTaskRequestValidationError) ErrorName() string {
	return "UpdateTaskRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTaskRequestValidationError{}

// Validate checks the field values on DeleteTaskRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteTaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTaskRequestMultiError, or nil if none found.
func (m *DeleteTaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := DeleteTaskRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteTaskRequestMultiError(errors)
	}

	return nil
}

// DeleteTaskRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteTaskRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteTaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTaskRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTaskRequestMultiError) AllErrors() []error { return m }

// DeleteTaskRequestValidationError is the validation error returned by
// DeleteTaskRequest.Validate if the designated constraints aren't met.
type DeleteTaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTaskRequestValidationError) ErrorName() string {
	return "DeleteTaskRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTaskRequestValidationError{}

// Validate checks the field values on GetTaskRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetTaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTaskRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetTaskRequestMultiError,
// or nil if none found.
func (m *GetTaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := GetTaskRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetTaskRequestMultiError(errors)
	}

	return nil
}

// GetTaskRequestMultiError is an error wrapping multiple validation errors
// returned by GetTaskRequest.ValidateAll() if the designated constraints
// aren't met.
type GetTaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTaskRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTaskRequestMultiError) AllErrors() []error { return m }

// GetTaskRequestValidationError is the validation error returned by
// GetTaskRequest.Validate if the designated constraints aren't met.
type GetTaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTaskRequestValidationError) ErrorName() string { return "GetTaskRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetTaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTaskRequestValidationError{}

// Validate checks the field values on ListTasksRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListTasksRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTasksRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTasksRequestMultiError, or nil if none found.
func (m *ListTasksRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTasksRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPage() < 0 {
		err := ListTasksRequestValidationError{
			field:  "Page",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetPageSize(); val < 0 || val > 100 {
		err := ListTasksRequestValidationError{
			field:  "PageSize",
			reason: "value must be inside range [0, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for DatasourceId

	// no validation rules for Status

	// no validation rules for Type

	if len(errors) > 0 {
		return ListTasksRequestMultiError(errors)
	}

	return nil
}

// ListTasksRequestMultiError is an error wrapping multiple validation errors
// returned by ListTasksRequest.ValidateAll() if the designated constraints
// aren't met.
type ListTasksRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTasksRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTasksRequestMultiError) AllErrors() []error { return m }

// ListTasksRequestValidationError is the validation error returned by
// ListTasksRequest.Validate if the designated constraints aren't met.
type ListTasksRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTasksRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTasksRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTasksRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTasksRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTasksRequestValidationError) ErrorName() string { return "ListTasksRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListTasksRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTasksRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTasksRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTasksRequestValidationError{}

// Validate checks the field values on ListTasksResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListTasksResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTasksResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTasksResponseMultiError, or nil if none found.
func (m *ListTasksResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTasksResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTasks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTasksResponseValidationError{
						field:  fmt.Sprintf("Tasks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTasksResponseValidationError{
						field:  fmt.Sprintf("Tasks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTasksResponseValidationError{
					field:  fmt.Sprintf("Tasks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListTasksResponseMultiError(errors)
	}

	return nil
}

// ListTasksResponseMultiError is an error wrapping multiple validation errors
// returned by ListTasksResponse.ValidateAll() if the designated constraints
// aren't met.
type ListTasksResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTasksResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTasksResponseMultiError) AllErrors() []error { return m }

// ListTasksResponseValidationError is the validation error returned by
// ListTasksResponse.Validate if the designated constraints aren't met.
type ListTasksResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTasksResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTasksResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTasksResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTasksResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTasksResponseValidationError) ErrorName() string {
	return "ListTasksResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListTasksResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTasksResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTasksResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTasksResponseValidationError{}

// Validate checks the field values on StartTaskRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *StartTaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StartTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StartTaskRequestMultiError, or nil if none found.
func (m *StartTaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StartTaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := StartTaskRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return StartTaskRequestMultiError(errors)
	}

	return nil
}

// StartTaskRequestMultiError is an error wrapping multiple validation errors
// returned by StartTaskRequest.ValidateAll() if the designated constraints
// aren't met.
type StartTaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StartTaskRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StartTaskRequestMultiError) AllErrors() []error { return m }

// StartTaskRequestValidationError is the validation error returned by
// StartTaskRequest.Validate if the designated constraints aren't met.
type StartTaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StartTaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StartTaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StartTaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StartTaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StartTaskRequestValidationError) ErrorName() string { return "StartTaskRequestValidationError" }

// Error satisfies the builtin error interface
func (e StartTaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStartTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StartTaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StartTaskRequestValidationError{}

// Validate checks the field values on StopTaskRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *StopTaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StopTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StopTaskRequestMultiError, or nil if none found.
func (m *StopTaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StopTaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := StopTaskRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return StopTaskRequestMultiError(errors)
	}

	return nil
}

// StopTaskRequestMultiError is an error wrapping multiple validation errors
// returned by StopTaskRequest.ValidateAll() if the designated constraints
// aren't met.
type StopTaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StopTaskRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StopTaskRequestMultiError) AllErrors() []error { return m }

// StopTaskRequestValidationError is the validation error returned by
// StopTaskRequest.Validate if the designated constraints aren't met.
type StopTaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StopTaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StopTaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StopTaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StopTaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StopTaskRequestValidationError) ErrorName() string { return "StopTaskRequestValidationError" }

// Error satisfies the builtin error interface
func (e StopTaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStopTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StopTaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StopTaskRequestValidationError{}

// Validate checks the field values on PauseTaskRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PauseTaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PauseTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PauseTaskRequestMultiError, or nil if none found.
func (m *PauseTaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PauseTaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := PauseTaskRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PauseTaskRequestMultiError(errors)
	}

	return nil
}

// PauseTaskRequestMultiError is an error wrapping multiple validation errors
// returned by PauseTaskRequest.ValidateAll() if the designated constraints
// aren't met.
type PauseTaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PauseTaskRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PauseTaskRequestMultiError) AllErrors() []error { return m }

// PauseTaskRequestValidationError is the validation error returned by
// PauseTaskRequest.Validate if the designated constraints aren't met.
type PauseTaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PauseTaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PauseTaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PauseTaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PauseTaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PauseTaskRequestValidationError) ErrorName() string { return "PauseTaskRequestValidationError" }

// Error satisfies the builtin error interface
func (e PauseTaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPauseTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PauseTaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PauseTaskRequestValidationError{}

// Validate checks the field values on ResumeTaskRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ResumeTaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResumeTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResumeTaskRequestMultiError, or nil if none found.
func (m *ResumeTaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResumeTaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := ResumeTaskRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ResumeTaskRequestMultiError(errors)
	}

	return nil
}

// ResumeTaskRequestMultiError is an error wrapping multiple validation errors
// returned by ResumeTaskRequest.ValidateAll() if the designated constraints
// aren't met.
type ResumeTaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResumeTaskRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResumeTaskRequestMultiError) AllErrors() []error { return m }

// ResumeTaskRequestValidationError is the validation error returned by
// ResumeTaskRequest.Validate if the designated constraints aren't met.
type ResumeTaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResumeTaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResumeTaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResumeTaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResumeTaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResumeTaskRequestValidationError) ErrorName() string {
	return "ResumeTaskRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResumeTaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResumeTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResumeTaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResumeTaskRequestValidationError{}

// Validate checks the field values on ExecuteTaskNowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExecuteTaskNowRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExecuteTaskNowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExecuteTaskNowRequestMultiError, or nil if none found.
func (m *ExecuteTaskNowRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ExecuteTaskNowRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := ExecuteTaskNowRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ExecuteTaskNowRequestMultiError(errors)
	}

	return nil
}

// ExecuteTaskNowRequestMultiError is an error wrapping multiple validation
// errors returned by ExecuteTaskNowRequest.ValidateAll() if the designated
// constraints aren't met.
type ExecuteTaskNowRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExecuteTaskNowRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExecuteTaskNowRequestMultiError) AllErrors() []error { return m }

// ExecuteTaskNowRequestValidationError is the validation error returned by
// ExecuteTaskNowRequest.Validate if the designated constraints aren't met.
type ExecuteTaskNowRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecuteTaskNowRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecuteTaskNowRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecuteTaskNowRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecuteTaskNowRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecuteTaskNowRequestValidationError) ErrorName() string {
	return "ExecuteTaskNowRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ExecuteTaskNowRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecuteTaskNowRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecuteTaskNowRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecuteTaskNowRequestValidationError{}

// Validate checks the field values on GetTaskStatusRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTaskStatusRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTaskStatusRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTaskStatusRequestMultiError, or nil if none found.
func (m *GetTaskStatusRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTaskStatusRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := GetTaskStatusRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetTaskStatusRequestMultiError(errors)
	}

	return nil
}

// GetTaskStatusRequestMultiError is an error wrapping multiple validation
// errors returned by GetTaskStatusRequest.ValidateAll() if the designated
// constraints aren't met.
type GetTaskStatusRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTaskStatusRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTaskStatusRequestMultiError) AllErrors() []error { return m }

// GetTaskStatusRequestValidationError is the validation error returned by
// GetTaskStatusRequest.Validate if the designated constraints aren't met.
type GetTaskStatusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTaskStatusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTaskStatusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTaskStatusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTaskStatusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTaskStatusRequestValidationError) ErrorName() string {
	return "GetTaskStatusRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTaskStatusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTaskStatusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTaskStatusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTaskStatusRequestValidationError{}

// Validate checks the field values on GetTaskExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTaskExecutionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTaskExecutionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTaskExecutionRequestMultiError, or nil if none found.
func (m *GetTaskExecutionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTaskExecutionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := GetTaskExecutionRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetTaskExecutionRequestMultiError(errors)
	}

	return nil
}

// GetTaskExecutionRequestMultiError is an error wrapping multiple validation
// errors returned by GetTaskExecutionRequest.ValidateAll() if the designated
// constraints aren't met.
type GetTaskExecutionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTaskExecutionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTaskExecutionRequestMultiError) AllErrors() []error { return m }

// GetTaskExecutionRequestValidationError is the validation error returned by
// GetTaskExecutionRequest.Validate if the designated constraints aren't met.
type GetTaskExecutionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTaskExecutionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTaskExecutionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTaskExecutionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTaskExecutionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTaskExecutionRequestValidationError) ErrorName() string {
	return "GetTaskExecutionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTaskExecutionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTaskExecutionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTaskExecutionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTaskExecutionRequestValidationError{}

// Validate checks the field values on ListTaskExecutionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTaskExecutionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTaskExecutionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTaskExecutionsRequestMultiError, or nil if none found.
func (m *ListTaskExecutionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTaskExecutionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPage() < 0 {
		err := ListTaskExecutionsRequestValidationError{
			field:  "Page",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetPageSize(); val < 0 || val > 100 {
		err := ListTaskExecutionsRequestValidationError{
			field:  "PageSize",
			reason: "value must be inside range [0, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTaskId()) < 1 {
		err := ListTaskExecutionsRequestValidationError{
			field:  "TaskId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetStartTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListTaskExecutionsRequestValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListTaskExecutionsRequestValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListTaskExecutionsRequestValidationError{
				field:  "StartTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListTaskExecutionsRequestValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListTaskExecutionsRequestValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListTaskExecutionsRequestValidationError{
				field:  "EndTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListTaskExecutionsRequestMultiError(errors)
	}

	return nil
}

// ListTaskExecutionsRequestMultiError is an error wrapping multiple validation
// errors returned by ListTaskExecutionsRequest.ValidateAll() if the
// designated constraints aren't met.
type ListTaskExecutionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTaskExecutionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTaskExecutionsRequestMultiError) AllErrors() []error { return m }

// ListTaskExecutionsRequestValidationError is the validation error returned by
// ListTaskExecutionsRequest.Validate if the designated constraints aren't met.
type ListTaskExecutionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTaskExecutionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTaskExecutionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTaskExecutionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTaskExecutionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTaskExecutionsRequestValidationError) ErrorName() string {
	return "ListTaskExecutionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListTaskExecutionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTaskExecutionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTaskExecutionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTaskExecutionsRequestValidationError{}

// Validate checks the field values on ListTaskExecutionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTaskExecutionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTaskExecutionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTaskExecutionsResponseMultiError, or nil if none found.
func (m *ListTaskExecutionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTaskExecutionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetExecutions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTaskExecutionsResponseValidationError{
						field:  fmt.Sprintf("Executions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTaskExecutionsResponseValidationError{
						field:  fmt.Sprintf("Executions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTaskExecutionsResponseValidationError{
					field:  fmt.Sprintf("Executions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListTaskExecutionsResponseMultiError(errors)
	}

	return nil
}

// ListTaskExecutionsResponseMultiError is an error wrapping multiple
// validation errors returned by ListTaskExecutionsResponse.ValidateAll() if
// the designated constraints aren't met.
type ListTaskExecutionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTaskExecutionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTaskExecutionsResponseMultiError) AllErrors() []error { return m }

// ListTaskExecutionsResponseValidationError is the validation error returned
// by ListTaskExecutionsResponse.Validate if the designated constraints aren't met.
type ListTaskExecutionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTaskExecutionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTaskExecutionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTaskExecutionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTaskExecutionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTaskExecutionsResponseValidationError) ErrorName() string {
	return "ListTaskExecutionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListTaskExecutionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTaskExecutionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTaskExecutionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTaskExecutionsResponseValidationError{}

// Validate checks the field values on CancelExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelExecutionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelExecutionRequestMultiError, or nil if none found.
func (m *CancelExecutionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelExecutionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := CancelExecutionRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CancelExecutionRequestMultiError(errors)
	}

	return nil
}

// CancelExecutionRequestMultiError is an error wrapping multiple validation
// errors returned by CancelExecutionRequest.ValidateAll() if the designated
// constraints aren't met.
type CancelExecutionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelExecutionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelExecutionRequestMultiError) AllErrors() []error { return m }

// CancelExecutionRequestValidationError is the validation error returned by
// CancelExecutionRequest.Validate if the designated constraints aren't met.
type CancelExecutionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelExecutionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelExecutionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelExecutionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelExecutionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelExecutionRequestValidationError) ErrorName() string {
	return "CancelExecutionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CancelExecutionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelExecutionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelExecutionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelExecutionRequestValidationError{}

// Validate checks the field values on RetryExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RetryExecutionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RetryExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RetryExecutionRequestMultiError, or nil if none found.
func (m *RetryExecutionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RetryExecutionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := RetryExecutionRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RetryExecutionRequestMultiError(errors)
	}

	return nil
}

// RetryExecutionRequestMultiError is an error wrapping multiple validation
// errors returned by RetryExecutionRequest.ValidateAll() if the designated
// constraints aren't met.
type RetryExecutionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RetryExecutionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RetryExecutionRequestMultiError) AllErrors() []error { return m }

// RetryExecutionRequestValidationError is the validation error returned by
// RetryExecutionRequest.Validate if the designated constraints aren't met.
type RetryExecutionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RetryExecutionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RetryExecutionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RetryExecutionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RetryExecutionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RetryExecutionRequestValidationError) ErrorName() string {
	return "RetryExecutionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RetryExecutionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRetryExecutionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RetryExecutionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RetryExecutionRequestValidationError{}

// Validate checks the field values on BatchTaskOperationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BatchTaskOperationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BatchTaskOperationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BatchTaskOperationRequestMultiError, or nil if none found.
func (m *BatchTaskOperationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BatchTaskOperationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := len(m.GetIds()); l < 1 || l > 100 {
		err := BatchTaskOperationRequestValidationError{
			field:  "Ids",
			reason: "value must contain between 1 and 100 items, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BatchTaskOperationRequestMultiError(errors)
	}

	return nil
}

// BatchTaskOperationRequestMultiError is an error wrapping multiple validation
// errors returned by BatchTaskOperationRequest.ValidateAll() if the
// designated constraints aren't met.
type BatchTaskOperationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BatchTaskOperationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BatchTaskOperationRequestMultiError) AllErrors() []error { return m }

// BatchTaskOperationRequestValidationError is the validation error returned by
// BatchTaskOperationRequest.Validate if the designated constraints aren't met.
type BatchTaskOperationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BatchTaskOperationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BatchTaskOperationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BatchTaskOperationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BatchTaskOperationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BatchTaskOperationRequestValidationError) ErrorName() string {
	return "BatchTaskOperationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BatchTaskOperationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBatchTaskOperationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BatchTaskOperationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BatchTaskOperationRequestValidationError{}

// Validate checks the field values on BatchTaskOperationResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BatchTaskOperationResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BatchTaskOperationResult with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BatchTaskOperationResultMultiError, or nil if none found.
func (m *BatchTaskOperationResult) ValidateAll() error {
	return m.validate(true)
}

func (m *BatchTaskOperationResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	// no validation rules for Success

	// no validation rules for Failed

	// no validation rules for Results

	if len(errors) > 0 {
		return BatchTaskOperationResultMultiError(errors)
	}

	return nil
}

// BatchTaskOperationResultMultiError is an error wrapping multiple validation
// errors returned by BatchTaskOperationResult.ValidateAll() if the designated
// constraints aren't met.
type BatchTaskOperationResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BatchTaskOperationResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BatchTaskOperationResultMultiError) AllErrors() []error { return m }

// BatchTaskOperationResultValidationError is the validation error returned by
// BatchTaskOperationResult.Validate if the designated constraints aren't met.
type BatchTaskOperationResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BatchTaskOperationResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BatchTaskOperationResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BatchTaskOperationResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BatchTaskOperationResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BatchTaskOperationResultValidationError) ErrorName() string {
	return "BatchTaskOperationResultValidationError"
}

// Error satisfies the builtin error interface
func (e BatchTaskOperationResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBatchTaskOperationResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BatchTaskOperationResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BatchTaskOperationResultValidationError{}
