// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // account, mobile
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 登录响应
type LoginResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // ok, error
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CurrentAuthority string                 `protobuf:"bytes,3,opt,name=current_authority,json=currentAuthority,proto3" json:"current_authority,omitempty"`
	Token            string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LoginResponse) GetCurrentAuthority() string {
	if x != nil {
		return x.CurrentAuthority
	}
	return ""
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 登出请求
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

// 登出响应
type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取当前用户请求
type GetCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserRequest) Reset() {
	*x = GetCurrentUserRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserRequest) ProtoMessage() {}

func (x *GetCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

// 获取当前用户响应
type GetCurrentUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *CurrentUser           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserResponse) Reset() {
	*x = GetCurrentUserResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserResponse) ProtoMessage() {}

func (x *GetCurrentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetCurrentUserResponse) GetData() *CurrentUser {
	if x != nil {
		return x.Data
	}
	return nil
}

// 当前用户信息
type CurrentUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Userid        string                 `protobuf:"bytes,3,opt,name=userid,proto3" json:"userid,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Group         string                 `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	Access        string                 `protobuf:"bytes,7,opt,name=access,proto3" json:"access,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	Tags          []*UserTag             `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Country       string                 `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	Province      string                 `protobuf:"bytes,12,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,13,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentUser) Reset() {
	*x = CurrentUser{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUser) ProtoMessage() {}

func (x *CurrentUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentUser.ProtoReflect.Descriptor instead.
func (*CurrentUser) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *CurrentUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CurrentUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CurrentUser) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *CurrentUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CurrentUser) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CurrentUser) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CurrentUser) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *CurrentUser) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CurrentUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CurrentUser) GetTags() []*UserTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CurrentUser) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CurrentUser) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CurrentUser) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

// 用户标签
type UserTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTag) Reset() {
	*x = UserTag{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTag) ProtoMessage() {}

func (x *UserTag) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTag.ProtoReflect.Descriptor instead.
func (*UserTag) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserTag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UserTag) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// 获取通知请求
type GetNoticesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoticesRequest) Reset() {
	*x = GetNoticesRequest{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoticesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoticesRequest) ProtoMessage() {}

func (x *GetNoticesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoticesRequest.ProtoReflect.Descriptor instead.
func (*GetNoticesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

// 获取通知响应
type GetNoticesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Notice              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoticesResponse) Reset() {
	*x = GetNoticesResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoticesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoticesResponse) ProtoMessage() {}

func (x *GetNoticesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoticesResponse.ProtoReflect.Descriptor instead.
func (*GetNoticesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetNoticesResponse) GetData() []*Notice {
	if x != nil {
		return x.Data
	}
	return nil
}

// 通知
type Notice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // notification, message, event
	Read          bool                   `protobuf:"varint,4,opt,name=read,proto3" json:"read,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Datetime      string                 `protobuf:"bytes,6,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Extra         string                 `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notice) Reset() {
	*x = Notice{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notice) ProtoMessage() {}

func (x *Notice) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notice.ProtoReflect.Descriptor instead.
func (*Notice) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *Notice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notice) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notice) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notice) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Notice) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *Notice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Notice) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x0fapi.metadata.v1\x1a\x1cgoogle/api/annotations.proto\"Z\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"~\n" +
	"\rLoginResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12+\n" +
	"\x11current_authority\x18\x03 \x01(\tR\x10currentAuthority\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"\x0f\n" +
	"\rLogoutRequest\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x17\n" +
	"\x15GetCurrentUserRequest\"J\n" +
	"\x16GetCurrentUserResponse\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.api.metadata.v1.CurrentUserR\x04data\"\xd3\x02\n" +
	"\vCurrentUser\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06userid\x18\x03 \x01(\tR\x06userid\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x14\n" +
	"\x05group\x18\x06 \x01(\tR\x05group\x12\x16\n" +
	"\x06access\x18\a \x01(\tR\x06access\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\t \x01(\tR\x05phone\x12,\n" +
	"\x04tags\x18\n" +
	" \x03(\v2\x18.api.metadata.v1.UserTagR\x04tags\x12\x18\n" +
	"\acountry\x18\v \x01(\tR\acountry\x12\x1a\n" +
	"\bprovince\x18\f \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\r \x01(\tR\x04city\"1\n" +
	"\aUserTag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x13\n" +
	"\x11GetNoticesRequest\"A\n" +
	"\x12GetNoticesResponse\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.api.metadata.v1.NoticeR\x04data\"\xb8\x01\n" +
	"\x06Notice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04read\x18\x04 \x01(\bR\x04read\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x1a\n" +
	"\bdatetime\x18\x06 \x01(\tR\bdatetime\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05extra\x18\b \x01(\tR\x05extra2\xbf\x03\n" +
	"\vUserService\x12`\n" +
	"\x05Login\x12\x1d.api.metadata.v1.LoginRequest\x1a\x1e.api.metadata.v1.LoginResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/login\x12a\n" +
	"\x06Logout\x12\x1e.api.metadata.v1.LogoutRequest\x1a\x1f.api.metadata.v1.LogoutResponse\"\x16\x82\xd3\xe4\x93\x02\x10\"\x0e/api/v1/logout\x12~\n" +
	"\x0eGetCurrentUser\x12&.api.metadata.v1.GetCurrentUserRequest\x1a'.api.metadata.v1.GetCurrentUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/currentUser\x12k\n" +
	"\n" +
	"GetNotices\x12\".api.metadata.v1.GetNoticesRequest\x1a#.api.metadata.v1.GetNoticesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/noticesB Z\x1ego-metadata/api/metadata/v1;v1b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_proto_goTypes = []any{
	(*LoginRequest)(nil),           // 0: api.metadata.v1.LoginRequest
	(*LoginResponse)(nil),          // 1: api.metadata.v1.LoginResponse
	(*LogoutRequest)(nil),          // 2: api.metadata.v1.LogoutRequest
	(*LogoutResponse)(nil),         // 3: api.metadata.v1.LogoutResponse
	(*GetCurrentUserRequest)(nil),  // 4: api.metadata.v1.GetCurrentUserRequest
	(*GetCurrentUserResponse)(nil), // 5: api.metadata.v1.GetCurrentUserResponse
	(*CurrentUser)(nil),            // 6: api.metadata.v1.CurrentUser
	(*UserTag)(nil),                // 7: api.metadata.v1.UserTag
	(*GetNoticesRequest)(nil),      // 8: api.metadata.v1.GetNoticesRequest
	(*GetNoticesResponse)(nil),     // 9: api.metadata.v1.GetNoticesResponse
	(*Notice)(nil),                 // 10: api.metadata.v1.Notice
}
var file_user_proto_depIdxs = []int32{
	6,  // 0: api.metadata.v1.GetCurrentUserResponse.data:type_name -> api.metadata.v1.CurrentUser
	7,  // 1: api.metadata.v1.CurrentUser.tags:type_name -> api.metadata.v1.UserTag
	10, // 2: api.metadata.v1.GetNoticesResponse.data:type_name -> api.metadata.v1.Notice
	0,  // 3: api.metadata.v1.UserService.Login:input_type -> api.metadata.v1.LoginRequest
	2,  // 4: api.metadata.v1.UserService.Logout:input_type -> api.metadata.v1.LogoutRequest
	4,  // 5: api.metadata.v1.UserService.GetCurrentUser:input_type -> api.metadata.v1.GetCurrentUserRequest
	8,  // 6: api.metadata.v1.UserService.GetNotices:input_type -> api.metadata.v1.GetNoticesRequest
	1,  // 7: api.metadata.v1.UserService.Login:output_type -> api.metadata.v1.LoginResponse
	3,  // 8: api.metadata.v1.UserService.Logout:output_type -> api.metadata.v1.LogoutResponse
	5,  // 9: api.metadata.v1.UserService.GetCurrentUser:output_type -> api.metadata.v1.GetCurrentUserResponse
	9,  // 10: api.metadata.v1.UserService.GetNotices:output_type -> api.metadata.v1.GetNoticesResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
